### ISSUE TITLE
Cuphead and HOLLOW KNIGHT without audio

### ISSUE THREAD

**Issue by Robert19589** [skyline-emu/skyline#1009]
Hi. In the nsp version the game runs at about 10 fps however they have audio issues. The same thing happens in the Hollow knight game.

Greetings and thanks for such a valuable emulator.

Dice.
Xiaomi mi 9 android 11. Miui 12.5
6 GB RAM
GPU adreno 640
``

**Comment by UnearthlyGoose** [comment]
sound is not available in unity games, wait some time

**Comment by Enuerone** [comment]
Como consigo los juegos?

**Comment by alberto2098kl** [comment]
> Como consigo los juegos?

Google 💋

**Comment by PixelyIon** [comment]
This is a known issue, it'll be fixed at some point after an `audren` implementation. I'll be closing the issue since this isn't necessarily a bug but the lack of a subsystem that we plan to implement.
