### ISSUE TITLE
It's hard to see the buttons in games!

### ISSUE THREAD

**Issue by AyderProgramic** [skyline-emu/skyline#1027]
Buttons in games are not visible, make a setting so that you can change the transparency of the buttons

**Comment by AyderProgramic** [comment]
![Screenshot_2022-04-15-18-36-34-454_skyline emu](https://user-images.githubusercontent.com/74705634/163591252-6ce8ddba-88a6-414c-8ddc-f8fc5f6fe2a0.jpg)

**Comment by UnearthlyGoose** [comment]
probably your device uses dark theme for all apps, so thats the problem. turn it off

**Comment by AyderProgramic** [comment]
I just checked and it still merges with the game

**Comment by PixelyIon** [comment]
We're actively working on this, it will be fixed.

**Comment by prinxylove** [comment]
Hola. Soy nuevo en esto.. solo para informar el juego SONIC corre bien en samsung note 9 snapdragon 845...
Pero los demas aun no .. CELESTE  ya es jugable pero al abrir no sale completa la pantalla para seleccionar el area donde empezaremos a jugar .. 
Y otra cosa al conectar el control bluetooth no le puedo asignar los botones no me deja ... 
Mi reporte hasta ahora ... saludos... espero con ansias mas actualizaciones 😁
