### ISSUE TITLE
Sonic Mania refresh rate problem (maybe a issue with Samsung devices)

### ISSUE THREAD

**Issue by FensBK** [skyline-emu/skyline#1029]
The option "Use Maximum Display Refresh Rate" does not work properly, the game runs at 120fps even if its unchecked.
My device: Samsung Galaxy S20 FE Snapdragon 865

**Comment by Sovietfowl** [comment]
It's a problem with your os not skyline, you can try switching your refresh rate to 60hz maybe that will fix it . I will be closing this issue because it's not really skyline problem but the os.
