### ISSUE TITLE
Experience with samsung note 9

### ISSUE THREAD

**Issue by prinxylove** [skyline-emu/skyline#1030]
Hello. I am new at this..
Just to inform...
CELESTE runs at 90% has details moving screens..
SONIC MANIA runs at 100%
TINY BARBARIAN runs at 95% sound error..

Bluetooth remote works 100%
My report so far... cheers... looking forward to more updates

GAMES THAT DO NOT RUN:

ZELDA LINKS AWAKENING
CUPHEAD
SPELUNKY 2
SPELUNKY Se ve blanca la pantalla si corre pero se queda en blanco solo hace los sonidos donde escojes las opciones de juego...
FATES OF ORT
THE BINDING OF ISAAC
POKEMON UNITE
NEW POKEMON SNAP
NEW SUPER BOMBERMAN
NEW SUPER MARIO BROS U DELUXE
KIRBY AND THE FORGOTEN LAND

**Comment by JVBATISTA0** [comment]
👍

**Comment by guranu** [comment]
please speak english when making issue in this repository.

**Comment by prinxylove** [comment]
> please speak english when making issues in this repository.

Yes, I changed the language..

**Comment by Irfankhan886** [comment]
Im not spik English sorry

**Comment by Sovietfowl** [comment]
It's already known that some games don't work for now and it's not really an issue so i will be closing this issue
