### ISSUE TITLE
CupHead won't start on Samsung Galaxy note 20 ultra (exynos version)

### ISSUE THREAD

**Issue by huawdinho** [skyline-emu/skyline#1034]
Pls, fix cuphead on Note 20 ultra, other games like Celeste worked normaly, cuphead start and just freeze on start with an black or white black ground
![Screenshot_20220416-180610_Skyline](https://user-images.githubusercontent.com/101912801/163691416-ad249c12-3002-4611-b9bd-6dc76ccabb30.jpg)

**Comment by Aztroloe** [comment]
Normal behavior.

**Comment by huawdinho** [comment]
how this is normal ? the game won't start, keep on this screen forever

**Comment by Sovietfowl** [comment]
Yeah that's normal Cuphead is broken for now

**Comment by huawdinho** [comment]
ohh, what version its working ?

**Comment by Aztroloe** [comment]
Not worth the effort since the framerate is poor, but try 1024 build.

**Comment by Sovietfowl** [comment]
Btw i just noticed you have exynos and most games tend to crash or not work at all on mali devices so the chances are it probably won't work with 1024 build either. Anyways i will be closing this issues because mali crashes are known and will be fixed soon.

**Comment by Dr0bac** [comment]
I have oneplus 6, snapdragon 845 and cuphead also stuck on white screen after launching the game.

**Comment by Aztroloe** [comment]
Outdated drivers, probably.

**Comment by Dr0bac** [comment]
I guess, adreno v402. I'm on android 10. Android 11 is sluggish on oneplus 6.

**Comment by Crytonics** [comment]
yea thats is old drivers

**Comment by Aztroloe** [comment]
I doubt the driver update with Android 11 would work either.

**Comment by Crytonics** [comment]
well you can try root and update drivers but i wouldnt, wait for custom drivers in skyline

**Comment by Aztroloe** [comment]
It's still gonna take a while though.

**Comment by Dr0bac** [comment]
Correction: v408 on android 10. I tried android 11 v502 and some bugs were fixed in celeste (mountain was not red anymore, etc). And cuphead booted past menu in skyline prior versions.. but went back to android 10. Also rooted device but stuck in fastboot after couple of days, no idea why.. so went back to stock..

**Comment by Aztroloe** [comment]
If you're rooted, then why did you not upgrade your drivers?
