### ISSUE TITLE
Hollow knight crash on galaxy tab s7+, SD865+

### ISSUE THREAD

**Issue by Silverdragon122** [skyline-emu/skyline#1040]
So when i open hollow knight in skyline, it just crashes after less than a second and it's just a black screen. If I open it again, the skyline app just crashes. My tablet specs are in the title and I can provide a log if needed ( it won't let me upload a log here.) I have attached a video of what happens when I open the game. 

https://user-images.githubusercontent.com/101513517/163714557-c36a0f24-a8f2-40c0-b1b1-d3377c51a3f0.mp4

**Comment by HalogenGam3r** [comment]
What tablet are you using?

**Comment by Silverdragon122** [comment]
Galaxy tab s7+ as stated in title, snapdragon 865+

**Comment by PixelyIon** [comment]
Sorry but to avoid clutter in GitHub Issues, we've decided to not accept any issue reports on here at the moment. Report on the Discord server instead and I assume you're a tester so you can report to the channel designated for that.
