### ISSUE TITLE
No polish language

### ISSUE THREAD

**Issue by Andrew162x** [skyline-emu/skyline#1053]
Can i (help) translate to polish?

**Comment by pizza-10** [comment]
You can help here https://github.com/skyline-emu/skyline/issues/1053

**Comment by pizza-10** [comment]
You can help here https://github.com/skyline-emu/skyline/issues/37

**Comment by Sovietfowl** [comment]
Yeah we aren't really focusing on translation work for now but when we do we will contact everyone who wants to translate the app. You can comment your name in issue #37 and ask there to translate. As we already have an issue related to translation of skyline to other languages I will be closing this issue.
