### ISSUE TITLE
the game Shakedown Hawaii/Black screen 

### ISSUE THREAD

**Issue by MrEldlich** [skyline-emu/skyline#1054]
So I'm a little confused but why the black screen ? 
I mean shouldn't the emulator working fine with 2D/pixel games or my device is weak like the navy 
And yeah my phone is Samsung A30

**Comment by Sovietfowl** [comment]
Hey there not all 2d games work correctly for now, and yes your device is low end. Talking about shakedown it doesn't render anything for now, you can check the compatibility list in our discord server to check which games are currently supported. Anyways this really isn't an issue so I will be closing this.
