### ISSUE TITLE
On-Screen Controls

### ISSUE THREAD

**Issue by Grarak** [skyline-emu/skyline#106]

**Comment by iloveemulators** [comment]
Hello there when will be skyline fully available to use? Thanks..I'm really waiting for this emulator cause eggns suck gamesir X2 is too expensive for a gamepad..nsp or xci?

**Comment by willfaust** [comment]
> Hello there when will be skyline fully available to use? Thanks..I'm really waiting for this emulator cause eggns suck gamesir X2 is too expensive for a gamepad..nsp or xci?

That is not a valid issue. Also, the development team does not have any ETAs at the moment. If you would like to ask anymore questions of this sort, please ask in the discord server.

Thanks.

**Comment by BlazeXII** [comment]
When will it be fully playable? Egg NS annoying like Damon ps2. By the way Egg NS works fine with midrange mediatek chipsets like helio G series. So can you please optimise this emulator for Mali Gpu and add vulkan api option.
