### ISSUE TITLE
Skyline iOS/iPadOS version

### ISSUE THREAD

**Issue by francexecomb** [skyline-emu/skyline#1062]
I like the Skyline application very much. It would be fantastic if there is also an iOS/iPadOS version.

Currently I have a jailbroken iPad Pro with M1 chipset and an iPhone 12 Pro that also has a jailbreak. If help is needed I would give an iPhone X for free for the developers.

**Comment by PixelyIon** [comment]
Sadly, this is not viable due to several restrictions imposed by iOS and we have no plans to do so in the future. There is a GitHub Discussions feature request which did propose this as well.
