### ISSUE TITLE
Manually sort the overview and some more functions

### ISSUE THREAD

**Issue by francexecomb** [skyline-emu/skyline#1064]
In the overview would like to 

- manually sort the order of the games
- switch to list view
- show folder when a folder is created in the file system and there are games in the folder

**Comment by PixelyIon** [comment]
We have no plans at this point to support manual sorting albeit we will add support for more complex sorting including weighted by recency and playtime at a later date, we also have no plans for categories based on folders. If you think these features may be popular, you can open up GitHub Discussions feature requests for them which people can upvote.

As for list-view, that's already possible by changing the game display layout in settings to list.

**Comment by francexecomb** [comment]
You say that in the future it is possible that more complex sorting is possible.

Can you then also add sort by manufacturer? That would make it much easier for me to find the same game series faster and make it clearer, because you say that manual sorting and folders are not planned.

**Comment by PixelyIon** [comment]
I'll leave that up to @lynxnb, he's likely going to be implementing it when the time comes.

**Comment by francexecomb** [comment]
Ok thanks for the answer hope there is soon a sorting by manufacturer and game series.

Is there also a story about Skyline? Why this name and the beautiful icon would be great if could be written on the main view of github.

**Comment by PixelyIon** [comment]
We will cover them on our website which will go live soon enough, thanks for the suggestions. It is getting fairly off topic from the issue though and the preferred means of communication of this sort is in our Discord server.
