### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Carlosforu** [skyline-emu/skyline#1065]
please could you make it more compatible with android 10 and snapdragon 845?

**Comment by KYM201** [comment]
Compatibilidad para Android 12 también por favor

**Comment by PixelyIon** [comment]
I'm not sure how we can increase compatibility with those targets outside of what we're already doing, the main issue would be older drivers which we will fix with [libadrenotools](https://github.com/bylaws/libadrenotools) integration which already exists but isn't exposed via the UI which will be worked on in the future.

I should add that issues like this are entirely pointless, we work on compatibility with devices and trying to get the most out of them all the time and already have our priorities set in that aspect, asking us to do so doesn't change anything.
