### ISSUE TITLE
Screen

### ISSUE THREAD

**Issue by prinxylove** [skyline-emu/skyline#1071]
Celeste game went off screen again and unable to select area to play
here he left the image where the game area is selected where nothing appears and this had already been solved

![Screenshot_20220423-153522_Skyline](https://user-images.githubusercontent.com/103775397/164945301-1c81ef1a-775c-4984-8712-0a720d0f7a25.jpg)

**Comment by Sovietfowl** [comment]
Can you come to our discord server. It would be easier to easier to solve your problem when you can talk in real time. Also I will be closing this issue.

**Comment by Crytonics** [comment]
old drivers 4xx have that problem in menu, but later world render normal
