### ISSUE TITLE
[Feature Request] Multiple game folders

### ISSUE THREAD

**Issue by Jatoxo** [skyline-emu/skyline#1073]
Support for adding multiple game folders which are scanned for switch games

The reason this is needed is that Switch games can be quite large, and a FAT32 SD-Card can't store larger games that exceed the 32bit file size limit. These games have to be stored on internal storage. Ideally, you could add both your internal storage and your SD-Card game folder simultaneously

**Comment by Benedani** [comment]
You could also use EXFAT on the SD card, it has no such limitation.

**Comment by PixelyIon** [comment]
This has been brought up prior in a GitHub Discussion if I'm not wrong, our stance has not changed since then. If it gets enough upvotes we may consider it but not until then.
