### ISSUE TITLE
FPS droped !!

### ISSUE THREAD

**Issue by yhak22** [skyline-emu/skyline#1074]
hi guys i want to know is this only happens for me,
FPS droped if i don't press on touch controller in some games is this issue ? or not?
i tried even last bulid
My Device 
SD865 with 8gb Ram
thank you .

**Comment by Sovietfowl** [comment]
That is a feature of Android itself when you don't touch the screen cpu freq is lowered to save power, that's why fps drops. As this isn't really an issue so I will be closing this.

**Comment by NielsGx** [comment]
a "feature" ? 
hmmm
go from 45 to 33fps on celeste title screen, sd865

**Comment by Benedani** [comment]
If the screen is on, that's probably thermal throttling actually.

**Comment by NielsGx** [comment]
No.

It will be an issue for anybody using a controller

**Comment by Benedani** [comment]
It's an issue with your hardware, not Skyline. Get a basic cooling fan or something.

**Comment by NielsGx** [comment]
No, it's not thermal throttling smh.

it's because of the cpu governor, you can't change it without root.

and it happens everytime you touch/ don't touch your screen

**Comment by NielsGx** [comment]
Mark our savior will implement a fix for this, but will probably only work on Snapdragon SoC.

Also might not work on some android ROM
