### ISSUE TITLE
Can't copy save files to backup location.

### ISSUE THREAD

**Issue by gregoryprosper** [skyline-emu/skyline#1085]
![Screenshot_20220425-173420_FolderSync Pro](https://user-images.githubusercontent.com/10222923/165178863-ec855677-b583-42be-9ac6-22d254331526.jpg)

**Comment by PixelyIon** [comment]
We're aware of this and moving files to the external private data directory was a temporary stopgap and only helps Android 10/11. We will work on a proper solution such as a `DocumentProvider` later down the line which should fix this issue entirely. As there are no resolutions at the moment I will close this issue.
