### ISSUE TITLE
Support 3D DMA engine copies

### ISSUE THREAD

**Issue by bylaws** [skyline-emu/skyline#1108]
The DMA engine supports the swizzling and deswizzling of 3D texture data, this is used by some games for texture upload.

**Required by:**
https://github.com/skyline-emu/skyline-games-list/issues/25
https://github.com/skyline-emu/skyline-games-list/issues/32
https://github.com/skyline-emu/skyline-games-list/issues/179
https://github.com/skyline-emu/skyline-games-list/issues/182
https://github.com/skyline-emu/skyline-games-list/issues/207
https://github.com/skyline-emu/skyline-games-list/issues/169

**Comment by Crytonics** [comment]
More games:
https://github.com/skyline-emu/skyline-games-list/issues/652
https://github.com/skyline-emu/skyline-games-list/issues/672
https://github.com/skyline-emu/skyline-games-list/issues/705
https://github.com/skyline-emu/skyline-games-list/issues/562
https://github.com/skyline-emu/skyline-games-list/issues/563
https://github.com/skyline-emu/skyline-games-list/issues/414
https://github.com/skyline-emu/skyline-games-list/issues/575
https://github.com/skyline-emu/skyline-games-list/issues/436
