### ISSUE TITLE
Bug graphic

### ISSUE THREAD

**Issue by Miftah35** [skyline-emu/skyline#1111]
![Screenshot_2022-04-27-16-38-29-94](https://user-images.githubusercontent.com/102598893/165489797-b7223410-5e88-49e2-93c3-feb48fc7dc5b.jpg)
I playing on mediatek g70 and after update game graphic is bug

**Comment by HalogenGam3r** [comment]
You have a lower GPU than Snapdragon. I'll advise you to get a better phone.

**Comment by PixelyIon** [comment]
Duplicate of #987.

**Comment by davyson123** [comment]
> ![Captura de tela_2022-04-27-16-38-29-94](https://user-images.githubusercontent.com/102598893/165489797-b7223410-5e88-49e2-93c3-feb48fc7dc5b.jpg) Estou jogando no mediatek g70 e depois de atualizar o gráfico do jogo é bug

Como vc fez isso ?
