### ISSUE TITLE
Games run smoothly but have no sound

### ISSUE THREAD

**Issue by Kelro92** [skyline-emu/skyline#1112]
For example: Streets of Red, Devil's Dare Deluxe and Mercenary Wings: The False Phoenix as well as games which were working well earlier such as Cuphead and Hollow Knight.

**Comment by pizza-10** [comment]
English please?

**Comment by PixelyIon** [comment]
We're aware of the lack of the sound in certain games, this will be fixed later as the games depend on things we haven't gotten to implementing yet. I'll be closing the issue regardless also please open up any issues in English rather than other languages as this is an English-only forum.
