### ISSUE TITLE
Mali GPU Totally broken

### ISSUE THREAD

**Issue by StringLibrary** [skyline-emu/skyline#1155]
In the latest updates or builds it has been noticed that this emulator does not work on other processors in this case I talk about mali since they do not work after having worked progressively Currently the games are like this 
![Screenshot_20220501_151150_skyline emu](https://user-images.githubusercontent.com/103220290/166162990-00113395-5992-4b9a-8d46-a25f7befab8d.jpg)
Others do not work better said or show anything or also stay at 0 fps this if it is bad

**Comment by demonx77** [comment]
only soporte snapdragon:(

**Comment by StringLibrary** [comment]
I think I'm disappointed as to have an emulator that doesn't work well and only works on an exclusive processor

**Comment by mateoalfaro** [comment]
> I think I'm disappointed as to have an emulator that doesn't work well and only works on an exclusive processor

Blame mali

**Comment by Jeff-2612** [comment]
Vocês usa Mali porque querem sofrer,pq só os snapdragon tem o adreno q tem mais compabilidade com vulkan , que é mas essencial na emulação de Nintendo Switch.

**Comment by Sovietfowl** [comment]
You should follow issue #987 for mali related problems instead of making new ones.
