### ISSUE TITLE
Motion (Gyro) Control support

### ISSUE THREAD

**Issue by Eyadplayz** [skyline-emu/skyline#116]
I was think if it is possible to use the phones accelerometer as gyro conrols.
Thanks.And keep up the good work.

**Comment by KingHackerMan** [comment]
> I was think if it is possible to use the phones accelerometer as gyro conrols.
> Thanks.And keep up the good work.

That's probably be further done the line when commercial games are supported, interesting idea but it'll be if no real use

**Comment by iulian204** [comment]
I don't think you should open issues containing suggestions, there are many other ways to give suggestions

**Comment by bylaws** [comment]
As king said, this is something we aim to do in the future after some games work so keep an eye out.

**Comment by iulian204** [comment]
> I was think if it is possible to use the phones accelerometer as gyro conrols.
> Thanks.And keep up the good work.

    I don't think you should open issues containing suggestions, there are many other ways to give suggestions

**Comment by sevketkrmsr** [comment]
Gpu support when ?

**Comment by KingHackerMan** [comment]
> Gpu support when ?

Please don't comment on closed issues

**Comment by willfaust** [comment]
> > I was think if it is possible to use the phones accelerometer as gyro conrols.
> > Thanks.And keep up the good work.
> 
> That'd probably be further done the line when commercial games are supported, interesting idea but it'll be of no real use

Why no real use? Motion controls are a pretty nice feature with switch games.

**Comment by PixelyIon** [comment]
This issue will be closed and subsequently deleted, this is already planned and will be implemented in time. We have much higher priority work at the moment.

**Comment by IvarWithoutBones** [comment]
Disregard the comment above, this issue is not a priority as of now but it is still a valid issue.
