### ISSUE TITLE
The app keeps crashing

### ISSUE THREAD

**Issue by macauley08** [skyline-emu/skyline#1164]
The app keeps crashing when i exit a game but idk if maybe im just not doing it right. Here's proof

https://user-images.githubusercontent.com/104642204/166263254-4044b616-ca82-46c2-b572-10e75e678e31.mp4

If it is a real issue, i hope it will be fixed soon.

Phone specifications:
Snapdragon 778g
8gb/128

**Comment by PixelyIon** [comment]
This is a game-specific issue which you can report with a log on our game issues repository.

**Comment by macauley08** [comment]
> This is a game-specific issue which you can report with a log on our game issues repository. I'll be closing this as it's more or less expected behavior.

um well i played some other games and it still crashes though
