### ISSUE TITLE
Snk heroines 

### ISSUE THREAD

**Issue by JuanL2022** [skyline-emu/skyline#1166]
It boots but text is illegible. Has Major glitches and several black and white screens. It runs up until selecting scenario after choosing characters, after that, it freezes on loading screen and basically deadlocks.

![Screenshot_20220502-132020_Skyline](https://user-images.githubusercontent.com/99209181/166273377-5542904d-54f8-4664-9601-c2c94607a3fa.jpg)
![Screenshot_20220502-132116_Skyline](https://user-images.githubusercontent.com/99209181/166273559-da40637c-69a0-4a65-8577-c22dcd5e891e.jpg)
![Screenshot_20220502-132302_Skyline](https://user-images.githubusercontent.com/99209181/166273701-7aad5eb9-c355-4907-b902-4ca4f0b46666.jpg)

**Comment by Aztroloe** [comment]
@JuanL2022 This is not the place to report game issues. Go to https://github.com/skyline-emu/skyline-games-list.
