### ISSUE TITLE
Can't install Skyline 

### ISSUE THREAD

**Issue by MetalFleetway** [skyline-emu/skyline#1176]
It keeps on saying "couldn't parse apk".

**Comment by mateoalfaro** [comment]
Android version?, remember that to update you need to uninstall previous version

**Comment by MetalFleetway** [comment]
I don't even have it on my phone and it's a samsung galaxy s8 +

**Comment by mateoalfaro** [comment]
> 

Too old

**Comment by MetalFleetway** [comment]
Oh okay.
