### ISSUE TITLE
S22Ultra exynos Dark screen

### ISSUE THREAD

**Issue by S22Ultraexynos** [skyline-emu/skyline#1178]
[loadersklog.zip](https://github.com/skyline-emu/skyline/files/8618958/loadersklog.zip)
Hello, nice work, but for some reasons early skyline versions worked on s22 ultra exynos, new versions have dark screen or crash, I can upload logs if it would help to solve this issue.

**Comment by massimocaste** [comment]
Samsung  s21 ultra exynos 2100 sonic mania the sound works, but the screen remains red. help apk working thanks

**Comment by PixelyIon** [comment]
You can just follow the #987 issue rather than opening a new one.
