### ISSUE TITLE
whitescreen only on cuphead and razion ex game adreno 630

### ISSUE THREAD

**Issue by rosenimcute** [skyline-emu/skyline#1195]
whitescreen only on cuphead and razion ex game adreno 630

**Comment by ZequerVirus** [comment]
What did happen with this issue? It's not work yet. I hope that the next version Cuphead runs in Adreno 630 and it's not show a whitescreen please

**Comment by rosenimcute** [comment]
yup, still not working on my phone samsung s9. shows only white screen. bastion works well but cuphead doesnt work.

**Comment by rosenimcute** [comment]
hope the developers will fix this issue and make skyline run on Adreno 630 gpu. thank you devs Godbless.
