### ISSUE TITLE
Black

### ISSUE THREAD

**Issue by Robert281250** [skyline-emu/skyline#1197]
![Screenshot_2022-05-06-11-40-36-474_skyline emu](https://user-images.githubusercontent.com/104965040/167176039-d21abfaa-b86c-448d-97e1-3f37721b921e.jpg)

k40 gaming edition this happens to me it stays black i tried the cuphead

**Comment by Crytonics** [comment]
You have mali gpu, some games won't work on mali yet and make sure that you use latest build.
