### ISSUE TITLE
Cuphead sound not working

### ISSUE THREAD

**Issue by eggwoos** [skyline-emu/skyline#1199]
using a tab s6

**Comment by Thepowa753** [comment]
Post this issue in: https://github.com/skyline-emu/skyline-games-list/issues

**Comment by Aztroloe** [comment]
> Post this issue in: https://github.com/skyline-emu/skyline-games-list/issues

No need, the game is already on the list.

**Comment by PixelyIon** [comment]
Known issue and not the correct repository.
