### ISSUE TITLE
update app without uninstalling previous versions  

### ISSUE THREAD

**Issue by MD77MD** [skyline-emu/skyline#1218]
I have problem updating skyline... whenever i try to install an updated version from github actions.. it says app did not install. 

the only way is to uninstall previous versions and losing all my data. then install new versions and redo all settings and controllers mapping.

is there a way to to update app without uninstalling previous versions?

**Comment by yhak22** [comment]
Sorry but currently no the app is in experimental state
You can copy ur save data before uninstall 
then after install new one restore ur saved data that you copy before .
The path is in : android/data/skyline.emu
This well fix once the app officially be on google play

**Comment by MD77MD** [comment]
i see... thank you
