### ISSUE TITLE
No compatible con huawei p40

### ISSUE THREAD

**Issue by jjttx** [skyline-emu/skyline#1225]
![Screenshot_20220508_231421_skyline emu](https://user-images.githubusercontent.com/104842287/167334984-9aab2011-d902-41d3-ae11-4916e48d95d0.jpg)
![Screenshot_20220508_231414_skyline emu](https://user-images.githubusercontent.com/104842287/167334987-54d8b359-ea14-44a1-b63b-eb05490fdd59.jpg)
![Screenshot_20220508_231424_skyline emu](https://user-images.githubusercontent.com/104842287/167334996-0d54016a-1f68-49d6-93fe-15405b4bdc27.jpg)
![Screenshot_20220508_231416_skyline emu](https://user-images.githubusercontent.com/104842287/167335007-ca91f0d0-071c-4c1d-9316-0cd4c2803f77.jpg)
![Screenshot_20220508_231421_skyline emu](https://user-images.githubusercontent.com/104842287/167335012-c5a12f67-f62b-45d5-8e04-57b54d6d0e49.jpg)
 Eso es todo lo que hace en el huawey p40 no entra a ningún juego podrían arreglarlo?

**Comment by Darkherman** [comment]
Asi no es que funciona la cosa simplemente reportar error que tiene ya, ellos investigara que pasa recuerada que este emulador esta en estado alpha, aun no entra en fase beta.
No puede exiger que arregle error simplemente el emulador esta fase de prueba, solo queda de hacer es reporte
