### ISSUE TITLE
Docked Mode

### ISSUE THREAD

**Issue by belmont31** [skyline-emu/skyline#1234]
heloo my favorite devolpper team :D 

when iDocked mode is disabled in skyline  : Super mario odyssey can go ingame and we can hear mario jumping and walking around.. but we cant see anything !
but if we enable we can go ingame textures are rendered .. but game crash seconds after that 
her's a pic with mario oddysey with and without docked mode
![docked mode on](https://user-images.githubusercontent.com/104656222/167436177-d4f906ae-2db8-4725-b8a1-94dd48bda0cf.png)

![docked mode off](https://user-images.githubusercontent.com/104656222/167436243-b1762007-d314-4ba4-997b-d1e87f87d440.png)

**Comment by yhak22** [comment]
Yes that expected cause the devs now working hard to make the game playable as soon as they can.
So just wait until they fix it and make it playable
It's not an issue at all cause it's  work in progress

**Comment by PixelyIon** [comment]
This is expected behavior at the moment, there is no need to report this and game reports have their own repository which you should use instead.
