### ISSUE TITLE
Title keys problem

### ISSUE THREAD

**Issue by 7eroo** [skyline-emu/skyline#124]
It's say missing title keys while i have done import the key already.

**Comment by Eyadplayz** [comment]
Click the Refresh Icon.

**Comment by 7eroo** [comment]
But it doesn't have the refresh icon
![Screenshot_2021-02-16-19-34-48-982_skyline emu](https://user-images.githubusercontent.com/79118970/108058079-77a68200-708e-11eb-993d-fef53445c401.jpg)

**Comment by bylaws** [comment]
Gui refactor is wip and may not work properly, you could try swiping down

**Comment by Eyadplayz** [comment]
Oh you are using the UI branch for that just swipe down.
