### ISSUE TITLE
Celeste broken on 1087

### ISSUE THREAD

**Issue by FensBK** [skyline-emu/skyline#1242]
Celeste doesn't boot if a save file is present

**Comment by StringLibrary** [comment]
If you installed the latest update today clearly says error you have to wait for the next one but it also depends on your cell phone if it is mali GPU It's something else

**Comment by FensBK** [comment]
> If you installed the latest update today clearly says error you have to wait for the next one but it also depends on your cell phone if it is mali GPU It's something else

No, it's not mali, it's a S20 FE with snapdragon 865, it was working fine on older versions

**Comment by DanXG790** [comment]
> 

Delete the save file game

**Comment by PixelyIon** [comment]
Thanks for the report, we're looking into this but I should add that we have a dedicated repository for game compatibility tracking. It would be better to comment there rather than creating an issue here.

**Comment by belmont31** [comment]
last 3 buids ( 1093. 1094 1095 ) dont recognize the games pls fixe it :p !

**Comment by Sovietfowl** [comment]
The bug is fixed on the latest build. I will be closing this issue.
