### ISSUE TITLE
CI Build #1090 crashes on all games

### ISSUE THREAD

**Issue by lystt** [skyline-emu/skyline#1246]
Idk why, but every game crashes. Including the working ones.

**Comment by lystt** [comment]
Thanks to you bro :). I always do a test when a new update arrive. Is my way to support. Sorry if i dont write in a correct way, hablo español.

**Comment by finr0y** [comment]
No its fine how you said it i really have to say im happy with how much our community thinks to contribute

**Comment by Pintudada** [comment]
even contra anniversary is also not working

**Comment by 44cK3r** [comment]
> Thanks to you bro :). I always do a test when a new update arrive. Is my way to support. Sorry if i dont write in a correct way, hablo español.

Same here love you all

**Comment by PixelyIon** [comment]
CI Build 1091 should fix all regressions from 1090.
