### ISSUE TITLE
Games not working

### ISSUE THREAD

**Issue by fernaaguaviva** [skyline-emu/skyline#125]
I can't run the games. It's enter in this black windows and then go back to the home screen
![2](https://user-images.githubusercontent.com/79020918/108108579-90536f80-706f-11eb-823b-7889fb020778.jpeg)
![1](https://user-images.githubusercontent.com/79020918/108108580-90ec0600-706f-11eb-8d4e-6a8aefcae0f7.jpeg)
![3](https://user-images.githubusercontent.com/79020918/108108581-91849c80-706f-11eb-9e6f-f1a264282d69.jpeg)

**Comment by bylaws** [comment]
games don't work yet

**Comment by Eyadplayz** [comment]
Let me add details.
We haven't add Graphics in the game so nothing would render
Plus: Only a dozen of games work and they all before 2018 so expect new games to crash or not boot.

**Comment by fernaaguaviva** [comment]
Do you have the list?

**Comment by Eyadplayz** [comment]
No, Tho both Sonic Mania and Super Mario Odyssey work well.

**Comment by KingHackerMan** [comment]
Skyline doesn't run commercial games, at least with graphics. You can use the application at your own discretion with no support provided. The most complete list we have would be in skyline's discord server, specifically the pinned messages in the #development channel

**Comment by fernaaguaviva** [comment]
I'm searching for an emulator for switch games, I thought it's was already done

**Comment by bylaws** [comment]
It's not, best to play on your switch for the moment

**Comment by Ivanmilla** [comment]
> No, Tho both Sonic Mania and Super Mario Odyssey work well.

Im not able to play mario odyssey :(

**Comment by Eyadplayz** [comment]
Cause SMO needs a save data to work.

**Comment by mjcox244** [comment]
SMO lets you play in cap kingdom just fine on [bylaws time-wip fork](https://github.com/bylaws/skyline)
this build isnt fully up to date though

**Comment by deepak7979** [comment]
Not working for pokemon sword going back to home screen

**Comment by PixelyIon** [comment]
See #168
