### ISSUE TITLE
Builds 1089 and 1090 games not showing

### ISSUE THREAD

**Issue by gurukin** [skyline-emu/skyline#1250]
starting build 1089 includes 1090, games list doesnt show only rotating circle, i tried change games location and doesnt work. im android 12 and it was working always till stopped work on build 1089. please help.

Thank you for your hard work.

**Comment by Thepowa753** [comment]
I attached a log about odyssey on it's [game issue](https://github.com/skyline-emu/skyline-games-list/issues/1)
I continue to update the issue for any significant changes

**Comment by PixelyIon** [comment]
Duplicate of #1246.
