### ISSUE TITLE
my device restart

### ISSUE THREAD

**Issue by Affan413** [skyline-emu/skyline#1254]
hello love your work on the emulator but when i downloaded the new version of skyline on my device when and i open any supported game on the emulator my phone freezes and then the phone restart i am kind a worried about my device that why i have uninstalled skyline for now can you please help fix this issue i would deeply appreciate it .My device is a Sony xz3 with snapdragon 845 and 4gb of ram thank for developing this awesome emulator

**Comment by Sovietfowl** [comment]
Best to ask these questions in our discord server no need to open issues here.
