### ISSUE TITLE
Last Build dont revognize games

### ISSUE THREAD

**Issue by belmont31** [skyline-emu/skyline#1258]
![Screenshot_2022-05-11-16-48-41-267_skyline emu](https://user-images.githubusercontent.com/104656222/167893204-018d5a35-0e1b-4290-84e3-81cb5e79c18a.jpg)
The latest builds dont recognize games ( 1093 , 1094 1095) even if i give him prod keys and tittle keys !?

**Comment by Sovietfowl** [comment]
Best to ask these questions in our [Discord server](https://discord.gg/XnbXNQM), there is no need to open issues here.
