### ISSUE TITLE
Black screen in all games 1095#

### ISSUE THREAD

**Issue by HMEDS7** [skyline-emu/skyline#1259]
All the current working games are Black screen With the sound

**Comment by thecreative-beep** [comment]
Tá acontecendo comigo e fiquei procurando o problema e vi se era o jogo, as Keys ou as configurações mas não era

**Comment by PixelyIon** [comment]
That's a `master` build not an `ftx1` build, this is expected behavior. GPU is only implemented on `ftx1` and will be till it is eventually merged into `master`.
