### ISSUE TITLE
Freeze Emulation On Unfocusing

### ISSUE THREAD

**Issue by mjcox244** [skyline-emu/skyline#126]
Hi, I was wondering if you could impment a way to freeze emulation in the background

Atm if I start sonic mania it plays the track it is on then effectively crashes the emu even if i focus on it again

But if I'm in game focusing on it continues gameplay

Wondering if there's a way to stop it from running code in the background

**Comment by mjcox244** [comment]
This appears to have been sorted at some point, as emulation freezes as i'm in other apps and can no longer hear it in BG.

**Comment by PixelyIon** [comment]
Oh yeah, I entirely forgot to close this. It's been indirectly fixed as we pause the audio and most games pause themselves when they can't submit frames or audio.
