### ISSUE TITLE
last 4 ftx1 buils not showing games

### ISSUE THREAD

**Issue by gurukin** [skyline-emu/skyline#1260]
android 12 before worked, now these last 4 ftx1 builds after select games directory, the games dont show and the circle keeps rotating, i checked that skyline doesnt have storage permission because the apk doesnt ask it or doesnt have that function, i checked my mobile permissions manager. i already tried change the games location and still doesnt work.

**Comment by belmont31** [comment]
i got the same problem ... but fixed it by deleting all my game from the phone and copy them again  ! good chance ;p

**Comment by Sovietfowl** [comment]
Best to ask these questions in our [Discord server](https://discord.gg/XnbXNQM), there is no need to open issues here.
