### ISSUE TITLE
Android 10 

### ISSUE THREAD

**Issue by Truenoxdx1** [skyline-emu/skyline#1268]
En el android 10 cuando abro cuphead se pone pantalla blanca y yo se que es por el android 10 podrían arreglar ese error por favor

**Comment by StringLibrary** [comment]
Which cell phone is yours or rather what GPU is it? Oh and write in English so that other people including developers can understand and help you

**Comment by Joraganlas** [comment]
I think what he meant was whether it could fix graphic bugs on Android 10?  thank you

**Comment by Nipunchandika** [comment]
Not install android 10 this apk

**Comment by HMEDS7** [comment]
"hours ago
In android 10 when I open cuphead it gets a white screen and I know it's because of android 10 could you fix that error please" that's what he said

**Comment by PixelyIon** [comment]
This forum is English-only as it is impossible to parse through and moderate otherwise, the APK should install and function on Android 10 given your device has other prerequisites.
