### ISSUE TITLE
Save file operations

### ISSUE THREAD

**Issue by SandeMC** [skyline-emu/skyline#1273]
I'd like to be able to back up save file and then import them within the Skyline UI as on non-rooted device I just keep losing progress. Also, how hard would implementing update system be(game updates, not skyline)

**Comment by SandeMC** [comment]
Also, before that appears, what ways would there be to back up the save file without root?

**Comment by Sovietfowl** [comment]
Best to ask these questions in our [Discord server](https://discord.gg/XnbXNQM), there is no need to open issues here.
