### ISSUE TITLE
Pokémon letsgo Pikachu not loading in Snapdragon 860

### ISSUE THREAD

**Issue by ARG14** [skyline-emu/skyline#1276]
I have seen that the game starts and is playable on several devices but not on my poco x3 pro

**Comment by DanXG790** [comment]
> I have seen that the game starts and is playable on several devices but not on my poco x3 pro

Use the save file, and uncheck the dock option

**Comment by ARG14** [comment]
And how do I use the save file?

**Comment by leopeo-star** [comment]
Get the save file of the game go into Android/data/skyline/files/switch/keep going in until u find 34000 last number and put the save file in their

**Comment by ARG14** [comment]
Thanks a Lot it works
