### ISSUE TITLE
Navigation bar and status appearing

### ISSUE THREAD

**Issue by OreoCrea** [skyline-emu/skyline#1278]
The app exits full screen when tapping the screen when opening the game, and the navigation and status bar appears, I'm using android 11.

**Comment by Sovietfowl** [comment]
This tells nothing you haven't even specified what game you are trying to open. Because this issue is useless I will be closing this.

**Comment by Aztroloe** [comment]
> The app exits full screen when tapping the screen when opening the game, and the navigation and status bar appears, I'm using android 11.

That's likely your ROM issue.

**Comment by Vijaysolanki679** [comment]
Please solve the problem I have sd 888 bit it still not working solve Mali
GPU in next update please 🥺🥺
