### ISSUE TITLE
Project still alive?!

### ISSUE THREAD

**Issue by Kloppis** [skyline-emu/skyline#128]
Hey guys,
I am looking at this Project for a long time now and i am really waiting for it to get ready to a more or less playable beta state.
But the last Git Commits are from November. Is the Project still alive? Is there anything the "community" could do to help you?
I wolud really love to see this project getting released besides yuzu so we can play our games on more platforms.
Espacially Mobiles and Tablets are really nice devices for switch "emulation" because of the same architecture.
So i would say every modern android devices with a decent soc should be a good working devices to do that and that would help a lot with spreading developers for homebrew and switch developement in general.
Would like to hear that everything is fine and you are just busy working on big things to come :)

nice regards from germany, keep it on

**Comment by Jack-Rickwood** [comment]
Yep, work is ongoing! There's a commit from just 2 days ago on the [scheduler branch](https://github.com/skyline-emu/skyline/tree/sched). If you would like to stay up to date on development you could join the discord server in the readme.

**Comment by PixelyIon** [comment]
Hey there,
I was typing this message out but @Jack-Rickwood beat me to it :smile: but I wanted to mention that in addition to the scheduler we also have @bylaws who's working on an implementation of the Time sysmodule on HOS which is crucial for newer games to boot and @Grarak working on the UI Redesign (#110) which massively refactors the entire UI fixing several bugs and making it look significantly better while adding more functionality.

**Comment by Kloppis** [comment]
Nice to hear, that it is just going on. I am really looking forward. If i can help you with whatever, just say it.
I can also code a bit, but i am far away from coding emulators and stuff. I do know a bit of every language and even assambler but its far away from doing such stuff, sadly. But i would really love to support this project if there is any possibility to make this project a bit more finished, just let me know.
I will also join your discord now to keep an eye on you :)
