### ISSUE TITLE
Add Controller Stick Deadzone

### ISSUE THREAD

**Issue by kongmao45678** [skyline-emu/skyline#1281]
When playing "One Piece Unlimited World Red Deluxe Edition" with an Xbox controller, the character will slowly move to the left, and the joystick should not drift.

**Comment by kongmao45678** [comment]
May be the joystick can set the dead zone will solve this problem?

**Comment by PixelyIon** [comment]
We should be reporting the values as-is to the game, any drift is on the controller's end but we could introduce a deadzone potentially.

**Comment by german77** [comment]
The switch doesn't report the values as is. They actually add a deadzone + the game adds another deadzone from 5% to 50%. It's part of one of their solutions for joycon drift

**Comment by luffyraii** [comment]
luffyraii593@gmail.com

**Comment by mateoalfaro** [comment]
> [luffyraii593@gmail.com](mailto:luffyraii593@gmail.com)

![Uploading Screenshot_20220522-103342_Pixel Launcher.png…]()

**Comment by mateoalfaro** [comment]
> [luffyraii593@gmail.com](mailto:luffyraii593@gmail.com)

![Screenshot_20220522-103342_Pixel Launcher](https://user-images.githubusercontent.com/73367365/169706016-9e798488-9f91-4831-b966-22c527cb8c94.png)

**Comment by HalogenGam3r** [comment]
bro posted a email

**Comment by pLoOxEE** [comment]
i have same issue with this game using bluetoot controller hope it will be fix soon

**Comment by lynxnb** [comment]
This might have been fixed by #1954
