### ISSUE TITLE
Pokemon let's go eevee glitch

### ISSUE THREAD

**Issue by Hyujbg** [skyline-emu/skyline#1283]
![Screenshot_20220513_090959](https://user-images.githubusercontent.com/98869140/168207078-4f8f7ace-171d-4394-89f8-08c19fc287a2.jpg)
This how it looks.Does anyone know what's the problem

**Comment by Paulmathes** [comment]
Hi bro can u tell me how to download let's go evee in skyline emu

**Comment by Paulmathes** [comment]
Hi bro how can i download let's go eevee and pikachu?

**Comment by Hyujbg** [comment]
By searching in the internet
