### ISSUE TITLE
Title key?!

### ISSUE THREAD

**Issue by faroukabd000** [skyline-emu/skyline#129]
Greeting noble devs.
I tried to run a game to test the sound i already selected the keys but the emu said that the title key is missing
![Screenshot_20210223-183427~2](https://user-images.githubusercontent.com/64847752/108884599-125f0d80-7607-11eb-9fcf-bab78787a730.png)

**Comment by KingHackerMan** [comment]
Please do not upload decryption keys, that is considered copyrighted content and therefore piracy.

**Comment by faroukabd000** [comment]
@KingHackerMan
I upload it for the devs not for the users
But i removed it so chill😉

**Comment by KingHackerMan** [comment]
The message signifies that you do not have title keys for that specific game, this could be fixed by redumping through the use of Lockpick_RCM

**Comment by bylaws** [comment]
Lmao we Dev have our own switches and our own keys

**Comment by faroukabd000** [comment]
If i got a switch why the hell do i need an emulator
That's a good answer

**Comment by bylaws** [comment]
... you need a switch to use all emulators, Skyline allows you to play these games without the hassle of bringing a switch around everywhere
