### ISSUE TITLE
Add Pro Controller support via OTG

### ISSUE THREAD

**Issue by woyeshizuileye** [skyline-emu/skyline#1312]
Usually pro controls have extremely high latency on Android and do not support USB input, so I ask you to add USB pro control support, like steamlink, plug in OTG to recognize

**Comment by PixelyIon** [comment]
This would be a fairly involved process if even possible via Android APIs, we're likely only ever going to support direct userspace HID drivers for BT controllers and never over USB and even then it's going to be in the far future.
