### ISSUE TITLE
some games have broken progress saving

### ISSUE THREAD

**Issue by Sirox228** [skyline-emu/skyline#1314]
I used to test skyline on a lot of games and some of them, have just broken saving, e.g. cuphead, in it all is normal, just before you'll beat first level, after that all saves are disappearing and almost same bug happens in some games, maybe those games are using not usual saving system with what skyline have some issues. (just reported a bug)

**Comment by yhak22** [comment]
It's known Issues .
Wait for the dev to fix it 
They are working hard to make the emulate better and better.

**Comment by HUNT3R8** [comment]
Did the Deva fix it pls respond

**Comment by HUNT3R8** [comment]
Did the devs fix it pls respond
