### ISSUE TITLE
the wrong color  of some game 

### ISSUE THREAD

**Issue by Albertzhuo123** [skyline-emu/skyline#1317]
the game,<Memories Off History>,the color will be wrong when using skyline
it is correct in YUZU
![1652617931(1)](https://user-images.githubusercontent.com/90180064/168473068-31d2ca6c-299f-46d6-bd34-17ba7446f64a.png)
↑in skyline
![1652618030(1)](https://user-images.githubusercontent.com/90180064/168473118-9b1a4ecb-5dfc-42a9-a5b1-a7ca2aeec421.png)
IN YUZU
I hope it will be slove !
thanks a lot.

**Comment by Sovietfowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.
