### ISSUE TITLE
alot of games don't work on android 10

### ISSUE THREAD

**Issue by guranu** [skyline-emu/skyline#1334]
as the title say alot of games don't work as intended on android 10 for example FEZ on android 11 it looks and runs just fine:
![Screenshot_20220510-212758](https://user-images.githubusercontent.com/103632948/168651031-9c675e40-435c-4d75-a7a7-3b408c74c041.jpg)
but on android 10 it's this:
![Screenshot_20220516-203847](https://user-images.githubusercontent.com/103632948/168651293-eca0c336-bdac-447c-b4cb-b8201001886c.jpg)
i was wondering if there is a way fix this without upgrading to android 11?

**Comment by Emufan34** [comment]
Your android 10 device might be Mali or have old drivers

**Comment by guranu** [comment]
well my android 10 device is not a mali gpu it's an adreno gpu and how do i upgrade the drivers?

**Comment by Emufan34** [comment]
If you have root you can join the discord and ask there for help with it

**Comment by guranu** [comment]
but what if i don't have root?

**Comment by Sovietfowl** [comment]
Best to ask these questions in our [Discord server](https://discord.gg/XnbXNQM), there is no need to open issues here.
