### ISSUE TITLE
 Add a setting to force hide navbar and statusbar.

### ISSUE THREAD

**Issue by brujo5** [skyline-emu/skyline#1336]
Add a setting to force hide navbar and statusbar, Some custom roms like arrow a11 need this because otherwise just by touching the screen the statusbar or navbar appears and it doesn't hide automatically.
![Screenshot_20220516-202856](https://user-images.githubusercontent.com/4172898/168716620-c8116ac4-e379-4a43-921a-a8a8b9d36e4a.png)

**Comment by Thepowa753** [comment]
I can do it

**Comment by PixelyIon** [comment]
This is an OS level issue not a Skyline one, we attempt to force full screen with hidden nav/status bars already.
