### ISSUE TITLE
Yu-Gi-Oh! Legacy of the Duelist : Link Evolution crash after running rom

### ISSUE THREAD

**Issue by sensirou** [skyline-emu/skyline#1338]
I installed pro+tilte..key, ran the app and saw the game icon, but when I stared Yu-Gi-Oh! Legacy of the Duelist : Link Evolution, I saw black sceen in few seconds, and it was closed automaticaly.
My device: s21 ultra 5G

Can someon help me fix this issues, please?
Thank you very much.

**Comment by Sovietfowl** [comment]
Skyline is still very early in development so most games are expected to not work. Also it's better to report game-specific issues in (https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.
