### ISSUE TITLE
When installing the emulator, I have a "play guard"

### ISSUE THREAD

**Issue by AyderProgramic** [skyline-emu/skyline#134]
![IMG_20210305_165200](https://user-images.githubusercontent.com/74705634/110124492-31ae2580-7dd3-11eb-8895-9c1683ec240e.jpg)

Is the emulator safe?
Can you fix it somehow? 
Please 🙏

**Comment by KingHackerMan** [comment]
Google classifies anything not from the play store as unsafe (any apk's installed from a browser and such), as is most open source software Skyline is completely safe.

**Comment by AyderProgramic** [comment]
But what about the Egg ns emulator?

**Comment by AyderProgramic** [comment]
He's not in the store!

**Comment by IvarWithoutBones** [comment]
Unfortunately, we do not provide support for EggNS. We do not endorse using it, as it violates the GPL and steals code. Please ask for assistance with that elsewhere
