### ISSUE TITLE
Suporte pra Midiatek (helio G80)

### ISSUE THREAD

**Issue by Opaitaoff** [skyline-emu/skyline#1352]

**Comment by mateoalfaro** [comment]
Duplicate of a previous thread

**Comment by Opaitaoff** [comment]
Foi mal, não tinha visto

**Comment by GENROGAMER** [comment]
Processador ruim

Em qui, 19 de mai de 2022 22:23, Opaitaoff ***@***.***>
escreveu:

**Comment by Sovietfowl** [comment]
Duplicate of issue #987.
