### ISSUE TITLE
Can't load any game

### ISSUE THREAD

**Issue by Ocelini** [skyline-emu/skyline#1360]
Hi!
I can't open any game. Depending on the game, it stays more or less time. I tried to modify some settings, but nothing, every time crashing.
I gave a Xiaomi Poco X3 GT with 8gb ram and Mtk Dimensity 1100.

I tried with Kirby Star Allies, Kirby and the Forgotten Land and Super Mario Odyssey.

What should I do?

**Comment by Sovietfowl** [comment]
Those games are not currently supported.
