### ISSUE TITLE
Pokemon Arceus 

### ISSUE THREAD

**Issue by Idanror** [skyline-emu/skyline#1369]
Umm...

I downloaded the file of game, the type is NSP and I see the picture of the game and that mean the keys are really work.

But, and that a big 'but' , when I launch the game, I see a black screen and after a few seconds 'skyline' crash

**Comment by Sovietfowl** [comment]
Game is not yet supported.

**Comment by Idanror** [comment]
Uhh so.. all my view on YouTube was a lies??😱😭

**Comment by Idanror** [comment]
> Your views?

All a videos I wathced

**Comment by mrhplss** [comment]
So you got clickbaited. 
Don't trust random youtubers "testing" games.
