### ISSUE TITLE
Optimization on different devices

### ISSUE THREAD

**Issue by Magmanita** [skyline-emu/skyline#1383]
Currently games like hollow knight, metroid dread and pokemon lets go pikachu/eevee are running in a playable way, however this is not the case on high end devices, at least not on my Samsung galaxy note 10+ device, I understand that it is a process, I just wanted to advise of this in case it has not been reported

>

**Comment by Jariel87** [comment]
Why it was closed, it is true those games only go to black screen with good fps except hollow knight which boots, but metroid got sound but black screen with 60fps on oneplus 8 and pokemon goes to black screen

**Comment by Mr-Hopeless** [comment]
Like they aren't aware of it.
