### ISSUE TITLE
Fix samsung Galaxy Tab a7 sm-t500 black screen . Take your time but do the best job you can

### ISSUE THREAD

**Issue by kolp0** [skyline-emu/skyline#1403]
will fix the black screen after the game that does not crash and the samsung emulator card 7 sm-t500 should work
Logs https://drive.google.com/file/d/11S8jzKM-jx-SIA-4wkKqfoqVDl8NNt94/view
fix other bugs so that you can play somehow and write what you can play
take your time but do the best job you can

**Comment by Allatel** [comment]
it has 662 snap lol
