### ISSUE TITLE
dimensity 8100 any chance ?

### ISSUE THREAD

**Issue by momo00o** [skyline-emu/skyline#1412]
is it possible to run switch emulator on dimensity 8100 ?
I tried latest skyline with Super crush KO 
first run crashes second run get stuck in black screen I tried many other games with same results 
same results with egg ns too

realme gt neo 3 12gb ram

**Comment by momo00o** [comment]
[emulation info .sklog.log](https://github.com/skyline-emu/skyline/files/8792776/emulation.info.sklog.log)

[emulation error .sklog.log](https://github.com/skyline-emu/skyline/files/8792778/emulation.error.sklog.log)

[emulation debug .sklog.log](https://github.com/skyline-emu/skyline/files/8792779/emulation.debug.sklog.log)

**Comment by VladimirMihailov** [comment]
Mali support is WIP, maybe will be better one day, but main focus is on adreno gpu's
