### ISSUE TITLE
An additional lower resolution option

### ISSUE THREAD

**Issue by Joemama45** [skyline-emu/skyline#1424]
Lower resolution skyline would be nice, since most games lag a lot, and sometimes crash. So I hope an option is added so games can run and preform better in Frames per second!

**Comment by iniMerchant64** [comment]
We eventually will support mods, that includes resolution mods to my knowledge. Current performance is far from what you could expect which is why id recommend to give it more time

**Comment by edisionnano** [comment]
> We eventually will support mods, that includes resolution mods to my knowledge. Current performance is far from what you could expect which is why id recommend to give it more time

You don't need mods to scale the resolution, see how Ryujinx does it. Also who is "we" and who are you even.

**Comment by Mr-Hopeless** [comment]
> You don't need mods to scale the resolution, see how Ryujinx does it. Also who is "we" and who are you even.

Yeah whatever you say, it'll eventually appear. "We" as in the Skyline Team.
