### ISSUE TITLE
Decrease api level

### ISSUE THREAD

**Issue by ShubhDi** [skyline-emu/skyline#1430]
Hi Bois , I am Pokemon fan and want to play Pokemon let's go Pikachu but I am unable to play as I am having Android 9 , I can update to Android 10 as there is important stuff in my moble , on installing the app ( Skyline ) it shows Parsing error . Please make the app work on Android 9 in future . Please help 🙏 . Thanks for reading , hope you'll help .

**Comment by Sovietfowl** [comment]
This will never happen.
