### ISSUE TITLE
Bug sur Redmi note 8 pro

### ISSUE THREAD

**Issue by Ji-El974** [skyline-emu/skyline#1434]
Hello, I have a redmi note 8 pro and I can't open the games.  When starting the game Sonic mania there is the SEGA logo appearing and sometimes I can hear the word SEGA, but then the app spits out. the same goes for the game the last campfire. 
Thank you

**Comment by Sovietfowl** [comment]
Sonic and some other games don't work for devices with Mali GPU. You should follow issue #987 for any new progress for Mali.
