### ISSUE TITLE
Butcher

### ISSUE THREAD

**Issue by Vertimusmaximus** [skyline-emu/skyline#1435]
Butcher hasn't worked well since build 1109. On build 1128 I was told it works fine. But it doesn't. On build 1152 still it doesn't work. Watch.

**Comment by Vertimusmaximus** [comment]
Video won't post.

**Comment by Vertimusmaximus** [comment]
Converted it updated it whatever. It doesn't run. But if I reinstall the old build I have still it runs.

**Comment by Sovietfowl** [comment]
Skyline is still work wip so things are expected to break and this isn't the right repository to report game-specific issues. [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute). Report them here.

**Comment by Vertimusmaximus** [comment]
Ok
