### ISSUE TITLE
Will there be a version for ios devices in the future?

### ISSUE THREAD

**Issue by AyderProgramic** [skyline-emu/skyline#144]

**Comment by KingHackerMan** [comment]
No, Due to the lack of vulkan support and App store restrictions, also the 36 bit address space limitations which prevent NCE.

**Comment by AyderProgramic** [comment]
Thank you for answering my question.

**Comment by dashboarder** [comment]
For Vulkan, take a look at [MoltenVK](https://github.com/KhronosGroup/MoltenVK), a Vulkan to Metal translator.
There’s no need to put to App Store. There’s 3rd party stores such as for jailbroken devices or [AltStore](https://altstore.io), which has JIT support.
Not sure about address space thingy, maybe also something related to page-size? I see that Android uses 4K, meanwhile iOS uses 16k.

**Comment by bylaws** [comment]
Yup, AS limits and page size make it hard and none of us devs care about it. We are open to others PRing support though
