### ISSUE TITLE
Atomicrops bugs

### ISSUE THREAD

**Issue by Junae9318** [skyline-emu/skyline#1450]
![Screenshot_2022-06-03-01-55-05-478_skyline emu](https://user-images.githubusercontent.com/101065633/171709310-ab82ac1c-37f0-4cb4-81c6-b95e76412ad8.jpg)

**Comment by Sovietfowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.

**Comment by Junae9318** [comment]
Oke sir
