### ISSUE TITLE
Cuphead game no audio/sound

### ISSUE THREAD

**Issue by rosenimcute** [skyline-emu/skyline#1456]
Cuphead game no audio/sound

**Comment by DanXG790** [comment]
@rosenimcute This error is known, do not open useless issues

**Comment by rosenimcute** [comment]
Sorry skyline developer DANXH970 if i dont know about this issue because i recently tried this emulator with that game that i downloaded(cuphead game)

 It works great and i hope skyline devs will fix other bugs because i want to play pokemon games soon. Godbless.

**Comment by DanXG790** [comment]
@rosenimcute I'm not a developer, but you can see the official Compatibility list [here](https://github.com/skyline-emu/skyline-games-list/issues) , or if you wish and have not joined the official Skyline discord [here](https://discord.gg/XnbXNQM)
