### ISSUE TITLE
Option to hide screen buttons when using an external controller

### ISSUE THREAD

**Issue by leveluplen** [skyline-emu/skyline#1461]
Hello, would this be possible? Map the buttons then hide/make them transparent. Or maybe it is already a thing and I'm not seeing it. I can hide them but then the controller won't work. Thanks

**Comment by leveluplen** [comment]
Yes I know that, the problem is that the controller is manually mapped attached to that buttons, if I hide them clicking the eye, they're not working anymore. The question is any other way to make them transparent or something but they're still there so the buttons on the external controller can still work? Sorry if I'm not explaining this well.

**Comment by Mr-Hopeless** [comment]
You can't :p
