### ISSUE TITLE
Adreno 630 GPU, white display on some games

### ISSUE THREAD

**Issue by rosenimcute** [skyline-emu/skyline#1484]
Celeste and Bastion Okay. Cuphead on Adreno 630 GPU white screen only. you can hear the game load and has sound. Snapdragon 845, hope it will be fixed soon. thank you Skyline Devs. God Bless.

**Comment by rosenimcute** [comment]
![Screenshot_20220606-085632_Skyline](https://user-images.githubusercontent.com/104092390/172078183-53836fcb-cb77-49f1-8944-1a2065c6d3d8.jpg)

**Comment by Gonzalomario** [comment]
What Android do you have on your cell phone?

**Comment by rosenimcute** [comment]
> what cell phone do you have

Samsung S9

**Comment by Allatel** [comment]
Wtf this has been closed, wtf this is not planned u said 845 will be supported, you now closing every issue

**Comment by Mr-Hopeless** [comment]
"Will be" being the key word. Skyline is still in its' early stages.

**Comment by Sovietfowl** [comment]
This is probably a driver issue, which will be fixed by skyline providing you an option to choose your drivers in the future. SD 845 is supported don't worry.
