### ISSUE TITLE
CupHead com som ,mas sem imagem

### ISSUE THREAD

**Issue by DarkVaders22** [skyline-emu/skyline#1486]
Snapdragon 845 CupHead está iniciando o jogo e com som 
Mas fica a tela branca

**Comment by Dancristiano** [comment]
Poco X3 Snapdragon 855 Game intro works, but you just start a new game and screen goes black, sound does work well

**Comment by DanXG790** [comment]
> Poco X3 Snapdragon 855 Game intro works, but you just start a new game and screen goes black, sound does work well

Use docked mode
