### ISSUE TITLE
Deponia not reading saves

### ISSUE THREAD

**Issue by GabiAle97** [skyline-emu/skyline#1492]
Saving the game now write saves indeed, but the game can't read them, and I'm not sure why... Saw the log file, but there isn't any useful info as far as I know... Would love to attach the file, But I don't know how 😅

**Comment by Sovietfowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.
