### ISSUE TITLE
Support backup saves

### ISSUE THREAD

**Issue by bilebee** [skyline-emu/skyline#1495]
Sometimes it is necessary to downgrade an app and cause the saves to be lost
may be able to export game saves and emulator settings as one or two files

**Comment by yhak22** [comment]
That's great .
But for now u can zip ur save before delete the app
Then unzip after install new one or old one 
I'm doing this until they add setting for that
But now the important thing is make games playable.

**Comment by bilebee** [comment]
thanks.
There are some brands of phones systems have difficulty accessing data folders.
It is true that i can make a backup by copying the game save files, but the operation is somewhat tedious on some devices.

**Comment by yhak22** [comment]
U can use Zarchiver for that
U can find it on googol play
