### ISSUE TITLE
White block on screen

### ISSUE THREAD

**Issue by sadaqali** [skyline-emu/skyline#1510]
![Screenshot_2022-06-09-19-45-56-67_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/107110808/172900669-a0cd3192-b21f-47a4-8b1b-294d3e544ddd.jpg)

**Comment by Sovietfowl** [comment]
Stop making game-specific issues here. This is not the right repository for them.
