### ISSUE TITLE
White block on screen during gameplay

### ISSUE THREAD

**Issue by sadaqali** [skyline-emu/skyline#1512]
White box pop up during gameplay
![Screenshot_2022-06-09-19-45-56-67_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/107110808/172947473-dabae340-ab47-4d00-a7b2-83c73791f4f1.jpg)

**Comment by yhak22** [comment]
Man we know that u post 3 issues with same game
So please stop post here for games issues and post them in game list here:
https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute
Search for the game then post this there

**Comment by Sovietfowl** [comment]
You repeatedly keep making game-specific issues despite being asked not too. Take it as a warning next time you do so you will temporarily banned.
