### ISSUE TITLE
Android 10, black screen, mapping error

### ISSUE THREAD

**Issue by HanShuishi233** [skyline-emu/skyline#1541]
《Salt and holy land》, black screen, can only see the blood bar, but can see the equipment fence, can hear the sound

《Blasphemy》, can't see the main character's map

  The test phone is one plus 7pro, hydrogen os10 (Android 10)

**Comment by Sovietfowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.
