### ISSUE TITLE
old driver support

### ISSUE THREAD

**Issue by Dave1027** [skyline-emu/skyline#1542]
many game in my phone is not working, like hollow knight is just a black screen doesn't even boot up, cuphead is a white screen and other games like celeste is working just fine except there's a lot of broken texture and other things, i hope you can add support on old gpu drivers, thats all thank you

**Comment by Sovietfowl** [comment]
Eventually skyline will allow you to choose your own drivers in the future, but that will take a while and really isn't something the devs are focusing for now so I will be closing this issue.
