### ISSUE TITLE
I Also want to help

### ISSUE THREAD

**Issue by Beastboysubb** [skyline-emu/skyline#1545]

**Comment by Beastboysubb** [comment]
I can help

**Comment by PixelyIon** [comment]
Skyline is a project which requires a fairly high amount of skill to assist with, given you don't have significant amounts of skill with C++ or Kotlin/Android UI. It is unlikely that you can help, I will be closing this issue as it is effectively spam for us. This isn't the right forum to ask for tips on how to help, our Discord server would be but still it's unlikely that you could unless you are experienced enough.
