### ISSUE TITLE
Multiple game search locations

### ISSUE THREAD

**Issue by nabokie** [skyline-emu/skyline#1555]
Would be a great feature to have multiple game search locations. For example, have 1 search location on a SD-card and another in a folder in the internal storage and have all the games combined on the selection screen. Just in case your SD-card with games gets full you could start adding games to the internal storage as-well. 

Would love to see this added!

**Comment by yhak22** [comment]
i agree with u this will be great .
i hope they consider adding this in the near fueture .

**Comment by Sovietfowl** [comment]
This has been brought up prior in a GitHub Discussion if I'm not wrong, our stance has not changed since then. If it gets enough upvotes we may consider it but not until then.
