### ISSUE TITLE
¿Texturing problem in android 10?

### ISSUE THREAD

**Issue by Helloooo908** [skyline-emu/skyline#1571]
There is a solution for the inverted texture problem in android 10 with SD 865 "I think it is due to the GL 3.2 driver @444"
![Screenshot_2022-06-16-09-02-38-368_skyline emu](https://user-images.githubusercontent.com/107641522/174134322-bddbeeb7-a9f5-40ae-9bb2-a8b8a1e605a5.jpg)

**Comment by dimaxdqwerty** [comment]
It's not problem of android version. Your drivers are old

**Comment by dimaxdqwerty** [comment]
> > No es problema de la versión de Android. Tus drivers son viejos
> 
> But could they solve the problem or not, I want to know or else I would look for a way to update the driver.

It should fix the problem. And pls don't create such issues here

**Comment by Helloooo908** [comment]
> > > No es problema de la versión de Android. Tus conductores son viejos
> > 
> > 
> > Pero podrían resolver el problema o no, quiero saberlo o de lo contrario buscaría una forma de actualizar el controlador.
> 
> Eso debería solucionar el problema. Y por favor no cree tales problemas aquí

Sorry for creating a post here, I wanted to know if they would solve this problem in the future for the old drivers.
