### ISSUE TITLE
Built-in Screen Buttons DON'T HAVE A OPACITY CONFIGURATION

### ISSUE THREAD

**Issue by DanielMMend** [skyline-emu/skyline#1579]
I already posted a Issue with the DPAD using GamePads... But I could easily solve it by using ANY KIND of KeyMapper APP and place the GamePad buttons on top of the Screen Buttons... And it works perfectly!

Except for the fact that I CANNOT put the Screen Buttons at 0% Opacity... And I really don't want to play with them "polluting the image" of my games... If you guys can fix this, the emulator will be MUCH BETTER

**Comment by Sovietfowl** [comment]
You can make the OSC dissapear by changing it in controller settings.
