### ISSUE TITLE
¿Old driver support?

### ISSUE THREAD

**Issue by Helloooo908** [skyline-emu/skyline#1584]
On my phone they don't work, Cuphead is a white screen and other games like Hollin knight works fine. I hope you can add support in old gpu drivers, I hope you answer me to know if there will be a solution in the future, that's all, thanks.

**Comment by Sovietfowl** [comment]
This has already been bought up many times and Skyline will allow you too choose your own drivers for devices with Adreno GPU in the future. But this will happen way in the future and really isn't something devs are focusing on right now, so I will be closing this issue.

**Comment by OtakuMuch** [comment]
Why!?? Compatibility with devices should be more prioritized than availability of number of games to play. What's the point if only devices that are new/rooted can play it... I have a decent chipset (Snapdragon 855) yet I can't even run some 2D games cause of outdated drivers, Sorry for being somewhat rude, it's just I want to say my take on this "way" of prioritizing hoping it might change it. In any case, if 3D games are still the priority then best of luck I guess

**Comment by Sovietfowl** [comment]
Devs do care about compatibility and will allow you too choose your drivers in the future as I said, but this will happen after ftx1 branch is merger into Master.

**Comment by OtakuMuch** [comment]
Thank you for the immediate response, I'll now just patiently wait. Realizing I sounded rude, I have removed my past comment. Sorry for the passive-aggressiveness and again best of luck 👍

**Comment by Sovietfowl** [comment]
Check issue #1587 Adrenotools allow you too choose your own drivers without root but it's not system wide and devs have to implement it in their apps. It's already implemented in Skyline but there is no UI for it so it's not really usable for end users. Keep track of the issue I created to check when the UI will be implemented.

**Comment by OtakuMuch** [comment]
Will do, Thank you very much! ❤️

**Comment by Helloooo908** [comment]
> Verifique el problema #1587 , Adrenotools también le permite elegir sus propios controladores sin raíz, pero no es para todo el sistema y los desarrolladores deben implementar sus aplicaciones. Ya está implementado en Skyline, pero no hay una interfaz de usuario para él, por lo que no es realmente útil para los usuarios finales. Realice un seguimiento del problema que cree para verificar cuándo se implementará la interfaz de usuar

> Verifique el problema #1587 , Adrenotools también le permite elegir sus propios controladores sin raíz, pero no es para todo el sistema y los desarrolladores deben implementar sus aplicaciones. Ya está implementado en Skyline, pero no hay una interfaz de usuario para él, por lo que no es realmente útil para los usuarios finales. Realice un seguimiento del problema que cree para verificar cuándo se implementará la interfaz de usuario.

OK thank you
