### ISSUE TITLE
Update UI to Material You design

### ISSUE THREAD

**Issue by AdyaGD** [skyline-emu/skyline#1588]
I'd like to see the app match the new Android 12 (Material You) design, it will makes the app look more modern.

**Comment by Helloooo908** [comment]
> Me gustaría ver que la aplicación coincida con el nuevo diseño de Android 12 (Material You), hará que la aplicación se vea más moderna.

You're already asking too much, don't you think?

**Comment by bylaws** [comment]
This is planned for sometime in the future

**Comment by AdyaGD** [comment]
> You're already asking too much, don't you think?

how lmao its literally just changing the ui colors

**Comment by PixelyIon** [comment]
@AdyaGD It's actually far more involved than that, it's a fairly complex library update which requires QA testing again to ensure that there aren't any major issues with new components. If it was a simple recolor it would've been done already.

**Comment by HastyRookie** [comment]
@PixelyIon hay una libreria de google creo que se llama material  utils que lo que hace es que apartir de un color proporciona todas sus variantes al estilo material you pueden hacer asi que si solo seria un cambio de color al estilo material you se puede hacer una adaptación de esa libreria y usarla sin la necesidad de usar material3 como libreria o materialcomponents y seguir con appcompat

**Comment by shbzmk** [comment]
I would like to any unique design or neon design that's would be great

**Comment by danielushindi** [comment]
Apk

**Comment by danielushindi** [comment]
Apk

**Comment by danielushindi** [comment]
Noioooooo

**Comment by DavidAriyan** [comment]
Material U is a joke. Why do want anything or any icons in your screen has the same color. Lol.
A customizable color background maybe nicer add to suggest.
