### ISSUE TITLE
Games doesn't work

### ISSUE THREAD

**Issue by omardinasor** [skyline-emu/skyline#159]
When I open any games it closes after 2 seconds try to fix this issue

**Comment by PixelyIon** [comment]
^^ We will have to ban you from the repository if you keep creating these issues as we get notified on every issue.

**Comment by omardinasor** [comment]
> This emulator is in a very early state and can not boot most games due to missing GPU emulation
> 
> why do you keep opening these

I mean try to enable GPU emulation

**Comment by KingHackerMan** [comment]
The developers are working in it.

**Comment by FranklinBartholomewHill** [comment]
> > This emulator is in a very early state and can not boot most games due to missing GPU emulation
> > why do you keep opening these
> 
> I mean try to enable GPU emulation

Oh damn we never thought of this, tysm!

**Comment by Eyadplayz** [comment]
'Try to enable GPU Emulation'
Why don't you try to enable it yourself.
Its not like you can make an emulator in one day with all functionalities.
The developers are working hard but everything takes time to be developed. 
So patience is key.
