### ISSUE TITLE
Purple Screen On Bastion?

### ISSUE THREAD

**Issue by LumpyArbuckle** [skyline-emu/skyline#1594]
The most recent version of Skyline has been bit of a mess but the big issue is that Bastion just displays a purple screen on startup. I can hear the audio just fine, there just isn't any graphics being displayed, any know how to fix this?

Just worth mention that I have no idea what I'm suppose to do with the extra files added in that build so a install issue on my part is possible.

**Comment by mr-hopeless** [comment]
Please use #1200 build.

**Comment by mr-hopeless** [comment]
Yeah. More specifically, the newest one is based on a different branch, which doesn't have graphics output.
