### ISSUE TITLE
Build 1203 cannot play games running on previous build

### ISSUE THREAD

**Issue by rosenimcute** [skyline-emu/skyline#1595]
Build 1203 cannot play some games running on previous build. 

Black screen only on some compatible games.

**Comment by DanXG790** [comment]
> Build 1203 cannot play some games running on previous build.
> 
> Black screen only on some compatible games.

Go back to build 1200, only "ftx1" builds work correctly

**Comment by MrKing202981** [comment]
Build #1203 is based on the `Master` Branch and as such does not have the changes needed to render games.
