### ISSUE TITLE
sir fix this problem please dimensity 1200 processor playable please sir

### ISSUE THREAD

**Issue by Gamexzeus** [skyline-emu/skyline#1599]
sir fix this problem please dimensity 1200 processor playable please sir

**Comment by Sovietfowl** [comment]
Duplicate of issue #987

**Comment by Sovietfowl** [comment]
Resident evil 5 doesn't work yet.

**Comment by mr-hopeless** [comment]
> Duplicate of # which game will play REALME X7 max sir please help me

Take a look at https://github.com/skyline-emu/skyline-games-list.

**Comment by Gamexzeus** [comment]
Sir but which game playable my device realme X7 max please send me name

**Comment by Gamexzeus** [comment]
Duplicate of # Sir but which game playable my device realme X7 max please send me name

**Comment by Sovietfowl** [comment]
Please stop spamming the repository, there is a compatibility list for games which currently work. https://github.com/skyline-emu/skyline-games-list.
