### ISSUE TITLE
Not working after Update NDK to 21.4.7075529 CI #479

### ISSUE THREAD

**Issue by TheNewon** [skyline-emu/skyline#160]
wont open any game like bastion or sonic just blink of black screen and return to menu. Android 11 xiaomi mi 11.

**Comment by PixelyIon** [comment]
This is intended, the stability of nothing aside from [master](/skyline-emu/skyline/tree/master) is guaranteed. Do not report issues for other branches as we're actively work on them and cannot assure that Skyline is functional.

**Comment by TheNewon** [comment]
but one earlier built worked fine. i dont know if is that some kind of bug or not so i just informing u.

**Comment by PixelyIon** [comment]
It isn't a bug, only report issues for a non-master branch when a PR for that branch to be merged into master has been created
