### ISSUE TITLE
Auto close

### ISSUE THREAD

**Issue by Medtoto21** [skyline-emu/skyline#1614]
I downloaded darksiders 3 and when i tried to enter it auto closes i entred production key and title keystill not works ... Btw sonic mania works perfectly.
My phone is android 12 poco x3 pro 8/256.

![Screenshot_2022-06-23-16-47-46-620_com mi android globalFileexplorer](https://user-images.githubusercontent.com/108073459/175341093-7df566e1-f867-4805-8949-7b772b8d46c4.jpg)
 
![Screenshot_2022-06-23-16-45-08-507_com mi android globalFileexplorer](https://user-images.githubusercontent.com/108073459/175340465-de3ac8f6-8987-4cc8-bbd7-bed1b8f49d64.jpg)

**Comment by Sovietfowl** [comment]
Where did you download it from?

**Comment by Sovietfowl** [comment]
You are banned from the repository for piracy.

**Comment by Allatel** [comment]
This is what not joining discord makes with ppl
