### ISSUE TITLE
Add a FPS lock/vsync

### ISSUE THREAD

**Issue by d4n1eu04** [skyline-emu/skyline#1634]
Games runs at screen refresh rate, which causes lighter ones like sonic mania to run in 90 Fps in my phone, and since I can't lower the refresh rate on my phone's system, the game ends running sped up and unplayable.

It would be nice to add a FPS limiter in the settings to prevent this

**Comment by mateoalfaro** [comment]
That exist in settings and should be capping to 60 by default you might be using an old build if you are on MIUI and it doesn't work

**Comment by Sisah2** [comment]
Exynos 2200 have similar (same?) Problem, cuphead, air conflict and hollow knight game speed is too fast, and fps counter dont work. Forcing 60hz refresh rate in system, nor any setting in skyline help here.

**Comment by mr-hopeless** [comment]
Exynos 2200 is the cause of the problem. Blame Samsung.
