### ISSUE TITLE
Skyline crashing

### ISSUE THREAD

**Issue by Markpois** [skyline-emu/skyline#1636]
Everytime when i try to play sonic Mania it just crashes.
I don't know why it crashes.
Is it because my phone, the game or the app?
Whatever it is i just want to know why it's crashing.
There's one version of skyline where it doesn't crash but instead it's just a black screen and audio
I'm confused why that specific version doesn't crashes but instead its a black screen.

**Comment by mateoalfaro** [comment]
Normal for Mali devices (exynos,tensor,etc)

**Comment by Silverdragon122** [comment]
Also next time it would probably be better to ask in the skyline discord ( https://discord.com/invite/skyline-545842171459272705 )
