### ISSUE TITLE
Can you fix black screen on Mali Mediatek 

### ISSUE THREAD

**Issue by kedrick021** [skyline-emu/skyline#1659]
![Screenshot_20220703-143527](https://user-images.githubusercontent.com/76839710/177028166-93cbc3dc-ecbd-4b32-b912-9d0db8f2a566.png)

Plss fix the name is air conflict using Mali gpu

**Comment by Crytonics** [comment]
Mali gpu will be fixed in the future. For more info and updates go here: https://github.com/skyline-emu/skyline/issues/987
