### ISSUE TITLE
Crash when load shader cache on realme 7

### ISSUE THREAD

**Issue by Cholti** [skyline-emu/skyline#1660]
When I begin to run Pokemon let's go Pikachu and Pokemon legend Arceus then during shader cache loding, emulator crashes. I just smile to see that after during lot of update and upgrades.. a problem still remains a problem.
Just tell me "you can't fix it" so that I won't get any hope.

**Comment by Crytonics** [comment]
You have mali gpu, mali is bad for emulation so you need to wait to get fixed by devs. They will fix that problem but no eta when.

**Comment by Crytonics** [comment]
For more info go here: https://github.com/skyline-emu/skyline/issues/987
