### ISSUE TITLE
[Feature request] Declaring app as game

### ISSUE THREAD

**Issue by Manu99it** [skyline-emu/skyline#1664]
Guys what about declare skyline app as game? So we get built in android game bubble (for recording screen and other), less notification because game mode starts  and other features that maybe are built in OS or launcher for categorization, etc. Look for example at Drastic emulator, or AetherSX2, etc.

**Comment by mateoalfaro** [comment]
I'm pretty sure that you can manually add skyline to any game booster manually

**Comment by Sovietfowl** [comment]
You can yeah.

**Comment by Manu99it** [comment]
@mateoalfaro @Sovietfowl you can add it to external game booster, but for example on native Google Pixel android 12 you can't add it to the system one manually. You can't also add it to play games, while most of other emulators are in there, like the aforementioned drastic, dolphin, AetherSX2. Of emulators that I've on phone, only citra and skyline are not declared as games

**Comment by Crytonics** [comment]
> @mateoalfaro @Sovietfowl you can add it to external game booster, but for example on native Google Pixel android 12 you can't add it to the system one manually. You can't also add it to play games, while most of other emulators are in there, like the aforementioned drastic, dolphin, AetherSX2. Of emulators that I've on phone, only citra and skyline are not declared as games

Idk for others game boosters but for MIUI i can add manual app.

**Comment by Manu99it** [comment]
> > @mateoalfaro @Sovietfowl you can add it to external game booster, but for example on native Google Pixel android 12 you can't add it to the system one manually. You can't also add it to play games, while most of other emulators are in there, like the aforementioned drastic, dolphin, AetherSX2. Of emulators that I've on phone, only citra and skyline are not declared as games
> 
> Idk for others game boosters but for MIUI i can add manual app.

I'm aware on MIUI you can. On Google Pixel UI and I think every other "mostly" AOSP based roms you can't
