### ISSUE TITLE
Easier Way To Get Logs

### ISSUE THREAD

**Issue by Silverdragon122** [skyline-emu/skyline#1665]
Hi, So I find it kind of annoying how I have to do the following to get a log for the games list or something else. Either 1. I have to click the log button in the app and email it to myself or 2. Manually Go To The Logs Folder. It would be cool if there was another button to either A. Copy And Paste The Log From The Logs Folder To Downloads Automatically, Making it easier to find and upload it or B. Make A Button in the app that opens the log folder so you can just easily copy and paste the log to downloads for easier uploading. I would prefer A As it seems more convenient. If There is a better way to get logs please let me know.

Thanks!

**Comment by PixelyIon** [comment]
@lynxnb Think we should add save log file to directory functionality? I'd say we can have a default directory in settings that is set on the first usage then have `Share Log`, `Save Log` and `Save Log As`.

**Comment by lynxnb** [comment]
I'd say logs should stay in the skyline folder, but as you said we could add "Save to" functionality.

**Comment by lynxnb** [comment]
Sounds good then, added to the TODO list.

**Comment by Joko1994** [comment]
Freeze on Yu-Gi-Oh game.

**Comment by Silverdragon122** [comment]
> Freeze on Yu-Gi-Oh game.

How is that related to a better log system in any way

**Comment by Joko1994** [comment]
![Screenshot_2022-07-22-12-16-51-135_skyline emu](https://user-images.githubusercontent.com/99770990/180368049-cd196a04-212f-4732-b222-8569cd424009.jpg)
I can playing this game after I change driver. U better make multi driver for official skyline . Actually I use Vulcan 611 driver from egg ns
