### ISSUE TITLE
Emulation stop or hang in realme 7. 

### ISSUE THREAD

**Issue by Cholti** [skyline-emu/skyline#1668]
![Screenshot_2022-07-05-07-50-23-10_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/103896231/177237161-7b17edb0-d24c-4509-b5d1-276c3414c302.jpg)
May be i don't have proper product key title key.
So let me know how to get it.

**Comment by AndresNorm** [comment]
By dumping from your Switch?

Cause thats the only LEGAL way to obtain it.
