### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by tabby-1** [skyline-emu/skyline#167]
![Screenshot_20210504-004839](https://user-images.githubusercontent.com/82579810/116932211-0630a580-ac73-11eb-8132-653385f2cc34.png)
U can hear music but screen is black

**Comment by KingHackerMan** [comment]
This is normal behavior as skyline doesn't yet support GPU emulation.

**Comment by Zi7ar21** [comment]
Perhaps that detail can be added to the Readme for the time of being, when I found this project yesterday it wasn't immediately clear to me either than there is no graphics yet

**Comment by KingHackerMan** [comment]
We don't provide binaries, that acts as a barrier of entry for people using that application. They're required to use the experimental github action builds or compile it themselves.

**Comment by Zi7ar21** [comment]
Sure, but you should make that obvious so that newcomers don't spend time compiling something in hopes that they will already be able to play games

**Comment by tabby-1** [comment]
Zi7ar is right

**Comment by KingHackerMan** [comment]
You should take this up with the Developers, personally don't see much of a point in adding it as GPU emulation will be implemented within the next few months anyways.

**Comment by Zi7ar21** [comment]
We can add it for now and then remove it once the missing parts are added, it's a small change and will prevent pointless issues like this one

**Comment by SANGATAMILnaruto** [comment]
> ![Screenshot_20210504-004839](https://user-images.githubusercontent.com/82579810/116932211-0630a580-ac73-11eb-8132-653385f2cc34.png) U can hear music but screen is blank
Even i have the same problem, so do anyone know to fix this problem?.... and my doesn't support coustom drivers too...wat should I do?
