### ISSUE TITLE
Emulation blackscreen 

### ISSUE THREAD

**Issue by Pramadanu** [skyline-emu/skyline#1679]
When i run cuphead its not showing anything only  blackscreen but the sound is coming out,the other game like sonic mania,and we are doomed are working very well.
![Screenshot_20220707-204422683](https://user-images.githubusercontent.com/68450462/177788745-950c08a0-2012-4e05-a7d7-2bc30a2ae988.jpg)

**Comment by Crytonics** [comment]
If you have questions about emulator go to discrod or ask in discussions tab tnx

**Comment by Crytonics** [comment]
> > What phone do you have?
> 
> Xiaomi redmi s2 with Snapdragon 625 processor,using 64bit custom rom

go to discord for help https://discord.gg/XnbXNQM

**Comment by MuhSlam** [comment]
Cuphead must use docked mode
Same as Rayman legends

**Comment by MuhSlam** [comment]
Also SD 625 are low end 
Even though you can running it 
Your GPU driver must be outdated
What your GPU driver version ?

**Comment by Crytonics** [comment]
> > Also SD 625 are low end Even though you can running it Your GPU driver must be outdated What your GPU driver version ?
> 
> 474.0

well old driver

**Comment by Pramadanu** [comment]
> > > Also SD 625 are low end Even though you can running it Your GPU driver must be outdated What your GPU driver version ?
> > 
> > 
> > 474.0
> 
> well old driver

I don't even know what the latest driver version is,I've installed adreno team driver version 490.0 and it still blackscreen.

**Comment by Ideasguacamayo** [comment]
A mí me pasa que se cierra el juego ni siquiera lo abre tengo un LG v60 snapdragon 865 le instale los keys pero igual se cierra
