### ISSUE TITLE
BE AWARE THAT SKYLINE DOESN'T SUPPORT GRAPHICS IN GAMES

### ISSUE THREAD

**Issue by bylaws** [skyline-emu/skyline#168]
All games will display a black screen or crash. This is not a bug, it just hasn't been implemented yet, please **DON'T** make issues about it.

**Comment by Zi7ar21** [comment]
Perhaps a title not written in all caps would be friendlier?

**Comment by bylaws** [comment]
People would ignore it then :)

**Comment by Zi7ar21** [comment]
Sad but true, people on the internet are careless 😂

**Comment by cobalt2727** [comment]
hi guys why is fortnite not working on skyline the screen is black I can't see anything you should fix this immediately

**Comment by TheNewon** [comment]
i checking github skyline-emu every day i couldn't believe that.

**Comment by KingHackerMan** [comment]
You need to enable the GPU by injecting vulkan.so file.

**Comment by Zi7ar21** [comment]
It's an option when you are setting up gradle
And you enable GPU support with a button before hitting compile
100% real

**Comment by riperiperi** [comment]
Oh really? Then what do you call this?
![byliar](https://cdn.discordapp.com/attachments/546432817962156034/838684400681353256/Screenshot_2021-05-03-13-22-07-67.jpg)

**Comment by Zi7ar21** [comment]
a jpeg

**Comment by FAROK000** [comment]
Ahhhhhh   just buy a console don't burn pixelalone mind

**Comment by Eyadplayz** [comment]
I love how we are adding so many messages to #git channel in the Discord.
