### ISSUE TITLE
Unable to Update /Reinstall

### ISSUE THREAD

**Issue by RobertDeltra** [skyline-emu/skyline#1684]
S21 Ultra

After installing skyline-1181-release back in June the apk installed without issue. I tried to update to the latest build skyline-1237-release there is an option to up however I get the following error " App not installed as package conflicts with an existing package"

I uninstalled the app and tried to scrub the files all skyline installation files however I still get the following error.

![image](https://user-images.githubusercontent.com/107205077/178362282-4c50cbb5-58f1-4ece-8550-a17fc6b9bcbe.png)

![image](https://user-images.githubusercontent.com/107205077/178362313-2b1e12e2-635f-44ea-bcce-6be3ad7ec2be.png)

**Comment by QuackingCanary** [comment]
Hi, I suggest you to install the old build again, uninstall it without keeping data and you'll be able to install the new build from scratch.

**Comment by Y-3domo** [comment]
No working phone Sony Xz2 compact

**Comment by RobertDeltra** [comment]
> Hi, I suggest you to install the old build again, uninstall it without keeping data and you'll be able to install the new build from scratch.

Hi, I tried but was not able to install or update the same error.

Any idea where the config files would be? I found the following folder and deleted it but I am still having issues installing it.

S21 Ultra\Internal storage\Android\data\skyline
![image](https://user-images.githubusercontent.com/107205077/178367077-21d045b0-5dfd-44a7-907a-88d0904337eb.png)

**Comment by Uriel20018** [comment]
Don't work in MediaPad M5 lite or LG k42.

**Comment by mjcox244** [comment]
The app has only recently began being signed, if you aren't using a recent build it won't smoothly upgrade
uninstall the app and install a more recent version.

**Comment by mjcox244** [comment]
> > The app has only recently began being signed, if you aren't using a recent build it won't smoothly upgrade uninstall the app and install a more recent version.
> 
> Hi, I tried but was not able to install or update the same error.

You need to uninstall the app if its giving that error when trying to upgrade.

**Comment by RobertDeltra** [comment]
> > > The app has only recently began being signed, if you aren't using a recent build it won't smoothly upgrade uninstall the app and install a more recent version.
> > 
> > 
> > Hi, I tried but was not able to install or update the same error.
> 
> You need to uninstall the app if its giving that error when trying to upgrade.

Afternoon mjcox 244,

I have uninstalled the app and deleted any files that I could find referencing skyline.
When I do a reinstall I receive an (Update) only option as I am not able to do a clean install.

At this point, I am unsure where the old skyline files are located.

**Comment by mjcox244** [comment]
> When I do a reinstall I receive an (Update) only option as I am not able to do a clean install.

what device/android branch are you using, it appears the app isn't being uninstalled properly
MiUI I know you have to uninstall from the app draw or settings.

**Comment by RobertDeltra** [comment]
> hat device/android branch are you using, it appears the app isn't being uninstalled properly
> MiUI I know you have to uninstall from the app draw or settings.

Galaxy S21 Ultra 
SM-G998U
Andriod 12( Mobile) 
Update June 1, 2022

**Comment by mjcox244** [comment]
> Galaxy S21 Ultra

This might seem dumb, but have you tried pressing the uninstall button in settings.
you might be accidently deleting the shortcut rather than the app itself

swipe up on the home screen and if you can find skyline in the app draw that means you haven't uninstalled it

**Comment by RobertDeltra** [comment]
> > Galaxy S21 Ultra
> 
> This might seem dumb, but have you tried pressing the uninstall button in settings. you might be accidently deleting the shortcut rather than the app itself
> 
> swipe up on the home screen and if you can find skyline in the app draw that means you haven't uninstalled it

Haha Yes, I fully uninstalled it via the app drawer. 
I believe the issue I am seeing is due to me clicking "Save Config Files" I have since removed any config files I could find via ( S21 Ultra\Internal storage\Android\data\skyline).

Unless the files are in ROM/RAM or in a file system I can't access outside of formating my S21 I'm at a hard stop. I just tried to use a 3d party uninstaller it also doesn't show the skyline app installed.

**Comment by StevenBeach33** [comment]
> > > Galaxy S21 Ultra
> > 
> > 
> > This might seem dumb, but have you tried pressing the uninstall button in settings. you might be accidently deleting the shortcut rather than the app itself
> > swipe up on the home screen and if you can find skyline in the app draw that means you haven't uninstalled it
> 
> Haha Yes, I fully uninstalled it via the app drawer. I believe the issue I am seeing is due to me clicking "Save Config Files" I have since removed any config files I could find via ( S21 Ultra\Internal storage\Android\data\skyline).
> 
> Unless the files are in ROM/RAM or in a file system I can't access outside of formating my S21 I'm at a hard stop. I just tried to use a 3d party uninstaller it also doesn't show the skyline app installed.



> > > Galaxy S21 Ultra
> > 
> > 
> > This might seem dumb, but have you tried pressing the uninstall button in settings. you might be accidently deleting the shortcut rather than the app itself
> > swipe up on the home screen and if you can find skyline in the app draw that means you haven't uninstalled it
> 
> Haha Yes, I fully uninstalled it via the app drawer. I believe the issue I am seeing is due to me clicking "Save Config Files" I have since removed any config files I could find via ( S21 Ultra\Internal storage\Android\data\skyline).
> 
> Unless the files are in ROM/RAM or in a file system I can't access outside of formating my S21 I'm at a hard stop. I just tried to use a 3d party uninstaller it also doesn't show the skyline app installed.

Try check in settings -> apps installed
![Screenshot_20220713-064600](https://user-images.githubusercontent.com/107557824/178616869-3b35351c-0ee2-4075-a465-7b23c0fdf1a6.png)
![Screenshot_20220713-064600](https://user-images.githubusercontent.com/107557824/178616869-3b35351c-0ee2-4075-a465-7b23c0fdf1a6.png)
![Uploading Screenshot_20220713-06460 
If you keep data while uninstall, your app still installed but not visible on app drawer

**Comment by RobertDeltra** [comment]
> > > > Galaxy S21 Ultra
> > > 
> > > 
> > > This might seem dumb, but have you tried pressing the uninstall button in settings. you might be accidently deleting the shortcut rather than the app itself
> > > swipe up on the home screen and if you can find skyline in the app draw that means you haven't uninstalled it
> > 
> > 
> > Haha Yes, I fully uninstalled it via the app drawer. I believe the issue I am seeing is due to me clicking "Save Config Files" I have since removed any config files I could find via ( S21 Ultra\Internal storage\Android\data\skyline).
> > Unless the files are in ROM/RAM or in a file system I can't access outside of formating my S21 I'm at a hard stop. I just tried to use a 3d party uninstaller it also doesn't show the skyline app installed.
> 
> > > > Galaxy S21 Ultra
> > > 
> > > 
> > > This might seem dumb, but have you tried pressing the uninstall button in settings. you might be accidently deleting the shortcut rather than the app itself
> > > swipe up on the home screen and if you can find skyline in the app draw that means you haven't uninstalled it
> > 
> > 
> > Haha Yes, I fully uninstalled it via the app drawer. I believe the issue I am seeing is due to me clicking "Save Config Files" I have since removed any config files I could find via ( S21 Ultra\Internal storage\Android\data\skyline).
> > Unless the files are in ROM/RAM or in a file system I can't access outside of formating my S21 I'm at a hard stop. I just tried to use a 3d party uninstaller it also doesn't show the skyline app installed.
> 
> Try check in settings -> apps installed ![Screenshot_20220713-064600](https://user-images.githubusercontent.com/107557824/178616869-3b35351c-0ee2-4075-a465-7b23c0fdf1a6.png) If you keep data while uninstall, your app still installed but not visible on app drawer

Hello StevenBeach33,

Thank you for the feedback, I do not have that option I checked everywhere and in my local system files, I can't find any trace of the skyline app at all.

**Comment by RobertDeltra** [comment]
I was able to fix my issue!!
Here are my steps for anyone having the same issue 

Download the app
APK Installer By Mobile Manager

Then navigate to Manage Apps. Here is where I found the 0 bytes of the skyline.emu file in the app drawer.

![Screenshot_20220712-224303_APK Installer](https://user-images.githubusercontent.com/107205077/178649799-7b36f2ff-e6ce-4fb7-85cb-37e9f628cfc9.jpg)

Once I found this I used the ADB debug mode to uninstall it with the following command
./adb uninstall skyline.emu

![image](https://user-images.githubusercontent.com/107205077/178649919-48de6a70-b919-411b-85ee-ad040fb00e97.png)

You can find the windows platform-tools here https://www.droidwin.com/platform-tools-adb-fastboot-commands/

Once I ran that command I rechecked APK Installer and found the skyline.emu file was gone! 

I was able to install a clean copy of skyline!

![Screenshot_20220712-231302_Package installer](https://user-images.githubusercontent.com/107205077/178650171-cb4128e5-3d2f-44aa-ba73-908ee0a6585a.jpg)



I want to thank everyone who help and offer advice on my issue, if anyone has any questions about my process please let me know. I'll be happy to help!
