### ISSUE TITLE
Android 6.0 compatibly

### ISSUE THREAD

**Issue by Tavish-153** [skyline-emu/skyline#1688]
Make an switch emu for Android 6.0

**Comment by dimaxdqwerty** [comment]
Sure. As you wish

**Comment by mr-hopeless** [comment]
Dreaming!

**Comment by Sovietfowl** [comment]
That's never going to happen I am quite sorry to say.

**Comment by Tavish-153** [comment]
:( never?

**Comment by Allatel** [comment]
Ur phone is weak, and will never have uptodate gpu drivers
