### ISSUE TITLE
Pokémon lets go pikachu

### ISSUE THREAD

**Issue by jolomoto** [skyline-emu/skyline#1711]
![Screenshot_2022-07-21-09-38-13-439_skyline emu](https://user-images.githubusercontent.com/65868960/180111901-2a3397bc-12e6-4a99-b6e6-4945fea9117e.png)

**Comment by KYM201** [comment]
Cómo me gustaría que se pudiese jugar ya bien en mi celular que es poco x3
pro snapdragon 860

**Comment by Sovietfowl** [comment]
This is not the forum to not make these type of requests, additionally it as an English speaking forum so please use it to make any type of issues and comments.
