### ISSUE TITLE
Please support on GPU Mediatek

### ISSUE THREAD

**Issue by mrsluppy** [skyline-emu/skyline#1719]
please the developer fix it as best as possible and give the best in dealing with problems that occur in the mediatek gpu please evaluate it immediately so that you can play and support the mediatek gpu

**Comment by GENROGAMER** [comment]
Sorry no no no

Em seg., 25 de jul. de 2022 04:29, mrsluppy ***@***.***>
escreveu:

**Comment by Allatel** [comment]
not planned xdddddd
