### ISSUE TITLE
Synchronization issue? First ever run results in error.

### ISSUE THREAD

**Issue by IngwiePhoenix** [skyline-emu/skyline#1725]
Long story short:
[emulation.sklog.zip](https://github.com/skyline-emu/skyline/files/9203815/emulation.sklog.zip)

I copied my prod/title keys over and then a game (BDSP) to see if it would run. But after a while of black-screen, it just returns to the menu.

From what I can understand in the log, it's something to do with synchronization. Well I turned off docked mode and disabled tripple buffering.

My phone is a Razer Phone 2 on LineageOS(4microG) 19.1 (Android 12).

Did I miss something?

**Comment by mateoalfaro** [comment]
The game is not compatible yet

**Comment by IngwiePhoenix** [comment]
I see! However, from the logs, this does not seem to be game-specific.

If you find the time, would you mind explaining how the error in the log is related to the game not being compatible?

Thanks!
