### ISSUE TITLE
Bad work on samsung galaxy a12

### ISSUE THREAD

**Issue by Nobiy1** [skyline-emu/skyline#1726]
I don’t really understand why the samsung galaxy a12 phone is not supported by the emulator? and for some reason my FPS is not showing.

**Comment by Silverdragon122** [comment]
Very low end phone

**Comment by Nobiy1** [comment]
Why doesn't it show FPS? Sonic Mania works but no FPS.

**Comment by Silverdragon122** [comment]
You need to turn that on in settings. Ask in the skyline discord next time before making an issue https://discord.gg/skyline-emu

**Comment by Nobiy1** [comment]
No, I have all inclusive. I'm talking about the fact that it shows 0 FPS for me, although I have 30-40 FPS.

**Comment by Nobiy1** [comment]
I would throw off a screenshot but writes not enough memory.

**Comment by Silverdragon122** [comment]
> No, I have all inclusive. I'm talking about the fact that it shows 0 FPS for me, although I have 30-40 FPS.

I have no idea what you're talking about

**Comment by Nobiy1** [comment]
I mean I have FPS display enabled but it shows 0 FPS. When at the actual FPS 30-40.

**Comment by Silverdragon122** [comment]
I told you to ask in the skyline discord server. This is not the place for support. Please actually read my messages :)

**Comment by Nobiy1** [comment]
Ok

**Comment by mateoalfaro** [comment]
> I mean I have FPS display enabled but it shows 0 FPS. When at the actual FPS 30-40.

Exynos devices have issues with fps counter info
