### ISSUE TITLE
Bright Memory Game

### ISSUE THREAD

**Issue by Gauravbodkhe24** [skyline-emu/skyline#1730]
I was trying to run bright Memory Game but it's not loading showing incomplete production keys even I loaded production keys...game is released just few days ago so don't know just want to tell
![Screenshot_2022-07-29-13-55-20-666_com google android documentsui](https://user-images.githubusercontent.com/105633074/181717399-0a3bd75a-99a8-49b8-ad27-5818e3c7720f.jpg)
![Screenshot_2022-07-29-13-55-10-042_skyline emu](https://user-images.githubusercontent.com/105633074/181717410-5ed60634-0571-4f50-827a-71f931a82b0a.jpg)

**Comment by PixelyIon** [comment]
This title isn't supported and GitHub Issues aren't used for reporting game bugs. To request support for any title you'll need to create a game request in GitHub Discussions.

**Comment by Gauravbodkhe24** [comment]
Ok
