### ISSUE TITLE
Bad work on gpu mali-g52.

### ISSUE THREAD

**Issue by Nobiy1** [skyline-emu/skyline#1733]
when I went into the version where it was possible to change the driver for the emulator, I was told that my gpu was not suitable.
Moreover, this could explain the poor performance of the emulator, and the fact that it shows 0fps even in working games.

**Comment by Sovietfowl** [comment]
Adrenotools doesn't support Mali gpus.

**Comment by Nobiy1** [comment]
and you can at least make support through the casts.

**Comment by Nobiy1** [comment]
а можно хотя бы сделать поддержку через костыли.

**Comment by Nobiy1** [comment]
And you can at least make support through crutches.

**Comment by PixelyIon** [comment]
That's not really how things work, we cannot add support without ARM changing how Mali drivers work. If it's showing 0 FPS on working issues, that spells clock issues which exist on really old devices which will not be fixed.

**Comment by Nobiy1** [comment]
I have android 12 on my phone and the phone itself is 2020 so it's not that old.
