### ISSUE TITLE
ps5 d-pad problem 

### ISSUE THREAD

**Issue by MD77MD** [skyline-emu/skyline#1738]
I have a number of controllers and all work fine except the PS5 controller.  for some reason the the d-pad gets stoke to one direction, left, up, right or dwon. shuffling the d-pad buttons makes it unstuck and work again but the problem occurs again after some time.  
Moreover This problem does not occur at the beginning of playing but only after 20 to 30 minutes ... also at first it shows up every 5 minutes or so... then it  start showing up more frequently until the game is no longer playable. 

Closing the emulator or reconnecting the controller does not help either.

It is also worth mentioning that this problem with the PS5 controller only occurs in skyline emulator but works fine on other emulators.

what could be the problem?  will sending log info help?

**Comment by Tiredasfunk** [comment]
Isn't this similar to #1057

**Comment by Joko1994** [comment]
ADD GAMEE SETTING IN GAME PLAY. LIKE DOCK MODE

**Comment by MD77MD** [comment]
Do you mean sklog? if not could you point me to an example to follow

**Comment by Wilsonfilmz** [comment]
Sii se mueve solo tiene problemas  con el mando de ps5 por favor corregir

**Comment by Wilsonfilmz** [comment]
If it moves, it only has problems with the ps5 controller, please correct

**Comment by MD77MD** [comment]
the gamepad is fine ... as i mentioned i use it all day with other games and emulators ... moreover I'm noticing the problem is getting worse 


however i will install skyline on a newer device and see if anything changes

**Comment by MD77MD** [comment]
until i get the newer phone... i tried to install an older version if skyline....i downgraded from v1308 to v1200... interestingly the problem did not disappear, instead it was delayed... in v1200 this problem took about 10 minutes to show up... also this problem would start to show up sooner with every subsequent releases.. to the point where it would show up immediately by v1308

i don't understand how,  but the newer skyline release the worse this problem gets

**Comment by MD77MD** [comment]
I also noticed something wired when making the controller,  sometimes skyline would treat the d-pad buttons as triggers 

![Screenshot_20220814-151518_Skyline](https://user-images.githubusercontent.com/63132171/184537554-f539a7a4-f00a-4b24-bdb0-ef71f9f2d6b4.jpg)

**Comment by MD77MD** [comment]
ok after so many test, i found that clearing the cash for a system app called (download manager)  does help temporarily. after clearing the cash the gamepad would work normal then it's would start to misbehave after a while... will keep testing and update 

download manager - package name: (com.android.providers.downloads)

**Comment by javiermaza** [comment]
The problem this in PS4 too

**Comment by lynxnb** [comment]
This might have been fixed by #1954

**Comment by lynxnb** [comment]
Alright, thanks for testing. It's weird that it doesn't work, does it happen on any game?

**Comment by MD77MD** [comment]
> Alright, thanks for testing. It's weird that it doesn't work, does it happen on any game?


Yes

I tested it on two different SD phones,  However both of them are Samsung (galaxy note10 & s21 to be  purcise) with Android 11 & 12

All my tests and theories above resulted to nothing.  and i have no idea why.  the only thing I'm sure here is despite the many games and emulators  i have,  this problem with the ps5 control only occurs in skyline alone.

**Comment by lynxnb** [comment]
I'm leaving this open, I've added it on my TODO list of stuff to fix. Likely going to work on this next, after I'm done with other stuff.

**Comment by MD77MD** [comment]
Thanks for your interest. I've been doing more test for the past week and I think I'm on to something. i would appreciate it  if you could point me to where I can get old builds of skyine such as build 899 or so.

**Comment by lynxnb** [comment]
Sadly, since old build artifacts are automatically deleted by GitHub, you won't be able to download them after. What you could do is build them for yourself, by checking out the commit the build was performed on, but that's kind of advanced if you're not experienced with git and building from source.

**Comment by lynxnb** [comment]
Nonetheless, I'm going to debug this properly myself soon.

**Comment by MD77MD** [comment]
> Nonetheless, I'm going to debug this properly myself soon.

And I'm ready for testing or anything that might help

**Comment by MD77MD** [comment]
> Thanks for your interest. I've been doing more test for the past week and I think I'm on to something. i would appreciate it if you could point me to where I can get old builds of skyine such as build 899 or so.

unfortunately non of my tests laid to anything useful.  i was expaxting that at some point, something was added to code that triggered this problem.  this assumption is based on that this problem did not exist in the old builds of skyline. 

I dont remember the exact build skyline was on when i first downloaded it. however i was able to finish four stages of Celeste but then after an update not so far away this problem started and keep getting worse.  thats was I was looking for old builds to pinpoint on which update thus problem started or at least narrow them.

if there is a way you could do the build and attach it for me to download and test that would be awesome, for example build 899. anyhow im open for anything that might help.

devices tested on:
- device 1: Samsung note10 @ android 12
- device 2: Samsung S21 @ android 11
- device 3: Samsung note10 @  android 12  freshly formatted 

PS: I'm starting to think this problem is not exclusive to PS5 controller as it did show using another controller.  but this needs conformation by testing other controllers.

**Comment by MD77MD** [comment]
any update on this

**Comment by MD77MD** [comment]
dear @bylaws 

could you reopen as this problem still exists in the lasted builds both normal and edge
