### ISSUE TITLE
when you plan to add support for DLC, will the performance of gpu mali be improved and will the bug be fixed so that the emulator shows 0 fps even in working games.

### ISSUE THREAD

**Issue by Nobiy1** [skyline-emu/skyline#1743]
How will the addition of DLC be implemented? that's all about DLC. the most important question is when and whether there will be optimization and greater compatibility for gpu mali. about compatibility, I want to say that I didn’t start celeste, which goes well with others, but sonic mania started and went in more or less playable fps. and yes, by the way, will the bug be fixed due to which the emulator always writes 0 fps, regardless of whether the game is running or not.

**Comment by Sovietfowl** [comment]
Adding support for DLC won't improve performance in Mali devices, that is a different matter altogether. Talking about fps counter issue it has been discussed about and it a problem with older Mali GPUs and it won't be fixed.
