### ISSUE TITLE
when you plan to add support for DLC, will the performance of gpu mali be improved and will the bug be fixed so that the emulator shows 0 fps even in working games.performance will be improved.

### ISSUE THREAD

**Issue by Nobiy1** [skyline-emu/skyline#1747]
How will the addition of DLC be implemented? that's all about DLC. the most important question is when and whether there will be optimization and greater compatibility for gpu mali. about compatibility, I want to say that I didn’t start celeste, which goes well with others, but sonic mania started and went in more or less playable fps. and yes, by the way, will the bug be fixed due to which the emulator always writes 0 fps, regardless of whether the game is running or not.

**Comment by PixelyIon** [comment]
Stop spamming issues covering the same topics, we've already answered this.
