### ISSUE TITLE
Games don't load, I have prod.keys and title.keys installed.

### ISSUE THREAD

**Issue by DropierTheN00b** [skyline-emu/skyline#1751]
Is there a reason for that my games don't work? I've tried Super Mario Odyssey, Super Mario Maker 2, Super Mario Bros. 35 and Mario Kart 8 Deluxe. What's going on?

**Comment by DropierTheN00b** [comment]
When I try opening a game a black screen shows up and nothing happens, although I can still hide the on-screen controls and close the game.

**Comment by Sovietfowl** [comment]
These games are not supported.

**Comment by DropierTheN00b** [comment]
Which games are supported then?

**Comment by DropierTheN00b** [comment]
Also, in another issue thread they said sonic mania and SMO worked, plus there are lots of videos talking about Odyssey working on Skyline. are you sure that's the reason?

**Comment by DropierTheN00b** [comment]
It says on config. that my GPU isn't supported under the GPU Driver Configuration section.

**Comment by Tiredasfunk** [comment]
what's your device?

**Comment by DropierTheN00b** [comment]
A samsung galaxy A51

Em dom., 7 de ago. de 2022 às 03:22, Tiredasfunk ***@***.***>
escreveu:

**Comment by DropierTheN00b** [comment]
It's a budget phone.

**Comment by Silverdragon122** [comment]
That's probably too low end for most games and those games don't even work
