### ISSUE TITLE
My thread got closed with the reason as that the games weren't supported, even if SMO, was.

### ISSUE THREAD

**Issue by DropierTheN00b** [skyline-emu/skyline#1752]
This is kind of weird and I would like to ask again as I had gotten more information on this error. On the configs page it tells me that my GPU is not supported under GPU Driver Configuration. I have all prod.keys and title.keys installed. If anyone has an actual reason to this instead, I would be grateful. Thanks.

**Comment by Sovietfowl** [comment]
You have a Mali Gpu

**Comment by DropierTheN00b** [comment]
Oh. Well is this the reason that the games won't load?

**Comment by Sovietfowl** [comment]
SMO also doesn't work currently on Mali devices.
