### ISSUE TITLE
Please working for Exynos9611

### ISSUE THREAD

**Issue by gamerm6777** [skyline-emu/skyline#1763]
hi please make skyline work on exynos9611 chipset, i tried to play sonic mania in 9fps and other games can't play

**Comment by Sovietfowl** [comment]
Don't make issues for specific SOCs, this is because you have a Mali GPU and and it won't be fixed for a while.

**Comment by Sovietfowl** [comment]
Adding on to this it's best to open an issue for Mali GPUs.
