### ISSUE TITLE
android 9 compatibility

### ISSUE THREAD

**Issue by deividariel0909** [skyline-emu/skyline#1769]
hello programmers, I have a very powerful cell phone with snapdragon 845, but the company that created the cell phone is not making more updates, it is only on android 9, that is, it does not install on my cell phone (will you get compatibility with android lower, will it improve some app compatibility/performance) my LG G7 Thinq phone

**Comment by Crytonics** [comment]
Skyline only work with Android 10+

**Comment by Silverdragon122** [comment]
Yes It will never work on android 9 and older

**Comment by Sovietfowl** [comment]
Skyline will never support Android 9 or lower. You need Android 10+ to use Skyline.
