### ISSUE TITLE
Games issues

### ISSUE THREAD

**Issue by edenberam** [skyline-emu/skyline#1773]
From versión 1299 some games are having trouble to start like hollow Knight and minoria, and some graphs are missing, pls check this with the beta testers my phone is a poco f3 8gb RAM... 1295 is ok, ramdomly start but ok.

**Comment by Sovietfowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.
