### ISSUE TITLE
Dosbox 3dfx games on exagear Android 

### ISSUE THREAD

**Issue by Plhorror** [skyline-emu/skyline#1774]
Hello 
I want to play Dosbox 3dfx games on exagear Android! But i dont arrived.i think its possible!
Help please?
 i tested since a few week and i dont progress!

**Comment by Crytonics** [comment]
Wrong repo, this is for Skyline.

**Comment by Sovietfowl** [comment]
This is one of the most weird issue I have ever seen, on that note this repository is for Skyline not for Exagear.

**Comment by QuackingCanary** [comment]
Hi @Plhorror, you must be lost. You're on an Nintendo Switch emu on Android repo. Have a nice day! Adrien
