### ISSUE TITLE
Gamepad null pointer error 

### ISSUE THREAD

**Issue by android-1995** [skyline-emu/skyline#1776]
![image](https://user-images.githubusercontent.com/35674533/183799018-8d0a0307-21c8-4658-897b-82f94a2b9585.png)
```
    override fun dispatchKeyEvent(event : KeyEvent) : Boolean {
        event.device ?: return super.dispatchKeyEvent(event)
        //Other original code
    }
    override fun onGenericMotionEvent(event : MotionEvent) : Boolean {
        event.device ?: return super.onGenericMotionEvent(event)
        //Other original code
    }
```
Wouldn't it be better to ignore some empty gamepad events?

**Comment by IvarWithoutBones** [comment]
This was closed by mistake, our apologies.

**Comment by lynxnb** [comment]
Thanks for the report. We're planning a refactor of how input works in skyline and we'll fix this as a result of that.

**Comment by android-1995** [comment]
fine, thanks for your work

**Comment by lynxnb** [comment]
Did you notice any new instances of this error?

**Comment by android-1995** [comment]
No, is there any related code to change?

**Comment by lynxnb** [comment]
Nope, just checking before closing this
