### ISSUE TITLE
Game freeze on log level below info

### ISSUE THREAD

**Issue by Manu99it** [skyline-emu/skyline#1780]
On build 1299+ if you keep logging level below info games freeze at start. On build 1289 can happen as well but it's rarer and happens in game

**Comment by Manu99it** [comment]
> That is normal, because you log more information than "Info"

How that's normal? Shouldn't log level be set by that setting? Or if that option just set how much log is wrote, but in any case the log is created and after just discarded, are you telling me that if I choose to write less log the game should freeze? If I set the log level to debug the game works fine. How can the log level affect the emulation per se?

**Comment by Crytonics** [comment]
Default log is set to "Info", and you should keep it there. What game you try to run and what phone?

**Comment by Crytonics** [comment]
Game freeze prob because of game or your phone.

**Comment by Manu99it** [comment]
Hollow Knight. It never froze before build 1299, and just sporadically on build 1289. But if I set the log level to debug or verbose game starts and run even on build 1299+. The phone is a Google Pixel 5 (snap 765G)

**Comment by Crytonics** [comment]
So when is log level set to "Info" you game freeze?

**Comment by Crytonics** [comment]
Yea we know that issue it will be fixes, tnx for reporting.

**Comment by Sovietfowl** [comment]
Our devs know about this issue and it will be fixed in the future until then I will reopen the issue to keep track of it.

**Comment by edenberam** [comment]
So my issue that was deleted on my edenberam account was rigth...tky sovietfowl :). At least was reopened

**Comment by raviii12** [comment]
Same problem happening with me.also .game always freez in start-up even I reinstalled app

**Comment by leopeo-star** [comment]
Yes same before build 1289 the game does  ot freeze that much its very rare but after build 1289 to 1314 latest the game freezes a lot realme 5 pro and x3 pro as well

**Comment by KacperSteam4** [comment]
I have the same problem with every game,phone is 6 GB RAM,64 GB memory and the name is realme 7

**Comment by javiermaza** [comment]
I have this problem My phone is poco f3

**Comment by Manu99it** [comment]
On build 1332 the problem *seems* solved. Instead of freezing now it just drops frames and recover itself👌🏻

**Comment by codeWorldRookie** [comment]
on xiaomi pad 5 pro has same issue.

**Comment by edenberam** [comment]
Xiaomi poco f3 same issue, no change.

**Comment by DavidAriyan** [comment]
Thanks for opening this issue. This is been bugged me for quite some times.

**Comment by Manu99it** [comment]
@KacperSteam4 realme 7 has a Mali GPU, your problem is not related with this issue. @javiermaza @codeWorldRookie @edenberam @DavidAriyan from build 1332 the bugs seems resolved. Try to clear cache and set debug level on info and start hollow knight

**Comment by DavidAriyan** [comment]
> @KacperSteam4 realme 7 has a Mali GPU, your problem is not related with this issue. @javiermaza @codeWorldRookie @edenberam @DavidAriyan from build 1332 the bug seems resolved. Try to clear cache and set debug level on info and start hollow knight

Hollow Knight already fixed now in 1342.

**Comment by DavidAriyan** [comment]
Maybe sometimes it will be back again, don't know. Other games that works before they're now stop loading, regardless of log level.
