### ISSUE TITLE
Game/Emu freezing

### ISSUE THREAD

**Issue by RUSTYprince** [skyline-emu/skyline#1790]
So i don't have a snapdragon, the emu is made for snap so if want to ignore it its ok
My phone is a Poco M4 Pro 5G
I try changing the config but didn't change nothing, you can see that the emu don't freeze it all but only the game/functions 

[Video](https://youtu.be/HBFryo5QPd4)

**Comment by Sovietfowl** [comment]
Games crash on non-Snapdragon devices this is known. I will change the title off the issue to better reflect this problem.

**Comment by Sovietfowl** [comment]
Well it seems like I don't have the required permission to do that, I will be closing this issue and highly encourage you to make one which encompasses all Mali devices in general.
