### ISSUE TITLE
App not Installing even with 6gb ram and android 10

### ISSUE THREAD

**Issue by KabelReaper** [skyline-emu/skyline#1796]
Hi! I am Brazilian and I have a Note 9C with 6GB RAM and I still can't install the app properly, every time I try to install it appears the phrase "app not installed"

I tried older versions and both of debug and release versions

![Screenshot_2022-08-17-18-51-27-201_com google android packageinstaller](https://user-images.githubusercontent.com/111465188/185249732-7cfe2c3d-f9db-4bb9-8c13-bdf48732fdbb.jpg)

**Comment by Silverdragon122** [comment]
You should not be using debug versions

**Comment by Sovietfowl** [comment]
It's best to come to our discord server and ask for help there instead of opening issues here.
