### ISSUE TITLE
Add a list wich shows compatibility

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [skyline-emu/skyline#1797]
It would be nice to see wich games the emulator is compatible with. A website or a text document would be nice maybe even a user review system like on protondb.com .

**Comment by MD77MD** [comment]
check these out 
https://github.com/skyline-emu/skyline-games-list/issues?q=is%3Aopen+is%3Aissue+label%

https://docs.google.com/spreadsheets/u/0/d/1oFND6f0vcQKsb8dMiVuhrwY-_Tkzf2RyEbjBM64b_eM/htmlview#

**Comment by Crytonics** [comment]
We have on github Skyline Compatibility List https://github.com/skyline-emu/skyline-games-list/issues
You can sort issues by Labels and see what game is running and etc...

I will close this, because there is a list.
