### ISSUE TITLE
Graphics white problem in need for speed prusuit rem

### ISSUE THREAD

**Issue by Ansupro** [skyline-emu/skyline#1807]
I will try again later game is runing but graphics are white looks like 
![Screenshot_20220822_112438](https://user-images.githubusercontent.com/111233427/185850577-0aa50c3f-18bf-4241-85cc-50d296053d26.jpg)
![Screenshot_20220822_112802](https://user-images.githubusercontent.com/111233427/185850599-9cce6b5f-7020-4cea-b44a-3aff16c40305.jpg)
![Screenshot_20220822_112846](https://user-images.githubusercontent.com/111233427/185850623-0f0df154-2a89-49cb-af35-f740367a93b9.jpg)
![Screenshot_20220822_112951](https://user-images.githubusercontent.com/111233427/185850625-0e5d1c3e-1a2f-4ff3-a1a9-fd93d180f403.jpg)
Fix it

**Comment by Crytonics** [comment]
This is not the place to post game related bugs or status. We have repo where you can post info about game https://github.com/skyline-emu/skyline-games-list/issues
