### ISSUE TITLE
[Feature Request] Build number on main screen

### ISSUE THREAD

**Issue by marcemira** [skyline-emu/skyline#1811]
**Scope:**
- 🚀 New Feature

# Summary
- Add support for displaying the build number on main screen, top header.

# Screenshots
![telegram-cloud-photo-size-1-4911382325628086908-y](https://user-images.githubusercontent.com/1788212/186235043-959a62b6-3c89-44e8-a0be-018e18060158.jpg)

**Comment by dimaxdqwerty** [comment]
For feature requests go here https://github.com/skyline-emu/skyline/discussions
