### ISSUE TITLE
Easy way to manage Save data

### ISSUE THREAD

**Issue by JeyKul** [skyline-emu/skyline#1814]
Please make an easy way to manage save data. On Android 13 it will be hard to edit savegame data as of now, since no new way has been discovered to actually access /sdcard/Android/data. (ADB might work, but I woudnt consider that as a solution)

Maybe make it like Citra? Make a action with documents UI to choose where all data like things installed to NAND, or savegames are managed.

Thanks for reading :)

**Comment by DIAVOLOIII** [comment]
Thx

**Comment by lynxnb** [comment]
We already have something like this, it's in `Settings -> View Internal Directory`.

**Comment by MrAnty** [comment]
Yesterday I updated to android 13 not knowing you can't access data. How can I transfer my save data back to skyline now?

**Comment by JeyKul** [comment]
> Yesterday I updated to android 13 not knowing you can't access data. How can I transfer my save data back to skyline now?

Theres a weird new way. Try to use the "FV File Explorer". They found a way to get access to app data on android 13.

**Comment by lynxnb** [comment]
Use this app, it calls the system provided file manager that should theoretically have access to the data folder: https://play.google.com/store/apps/details?id=com.marc.files

**Comment by MrAnty** [comment]
> 

I've already tried that. Again, you can access it, but can't transfer anything in.  I so wish I had of known about this before updating.

**Comment by lynxnb** [comment]
It should most definitely work, what's your device and ROM?

**Comment by MrAnty** [comment]
> 

You can transfer files from data, but not into it. Phone is just a stock Pixel 4.

**Comment by S76042** [comment]
Not working any games on mali GPU all games stuck after open fps stop game crash plz solve this issu now

**Comment by proganime1200** [comment]
> Not working any games on mali GPU all games stuck after open fps stop game crash plz solve this issu now

please create a new issue about your problem your using a mali and please post a specific games that has issues

**Comment by ZoomerVro** [comment]
Use ZArchiver guys

**Comment by noggl** [comment]
might it be possible to specify a save directory in a config file or in the app settings? That's what dolphin and citra do, though their save folders are within their config folders on the root of the sd storage.

**Comment by Gabryxx7** [comment]
I've had some success with Material Files from the Play Store (or any file explorer app that supports mounting external storage).
Just open it -> tap on + add storage from the sidebar -> External Storage -> Tap on Skyline from the sidebar -> "Use this folder".
I have been able to copy the "switch" folder to another location to back it up, and also to paste it in from an older backup, and my save files were all there!

**Comment by lynxnb** [comment]
We'll have an easier way to back up and restore saves in the future. For the time being, what @Gabryxx7 is correct, the `switch` folder contains all saves.

**Comment by michaelphagen** [comment]
Would it be possible to, in the future, have the saves stored in an accessible folder? That way users could use something like OneSync to synchronize the files between devices. The /sdcard/Android/data location is not accessible, but other emulators often give the option of using their own folder on the root of the SD card

**Comment by AbandonedCart** [comment]
I believe https://github.com/skyline-emu/skyline/pull/2297 will resolve this.
