### ISSUE TITLE
Mesa turnip v13 drivers are broken on games that aren't smo or botw

### ISSUE THREAD

**Issue by guranu** [skyline-emu/skyline#1817]
I have no idea why this happens but for some unknown reason the new mesa drivers don't work (by that i mean they run the same way as an adreno 408 drivers) i'm very sorry to be using github to report this issue but unfourtnately no one said anything when i reported this issue in the discord server.

**Comment by Sovietfowl** [comment]
Make issues for Turnip at Mesa repo not here as this is not the place for it.

**Comment by guranu** [comment]
Did you even read the message no one explained why it dosen't work.

**Comment by Sovietfowl** [comment]
Again you don't need to make an issue for it and if you come to our discord server on of our helper has pinged you about this issue actually, you can talk to him.
