### ISSUE TITLE
Games Like Pikuniku Crash/Freeze When The Starting Credits Shows Up

### ISSUE THREAD

**Issue by Thewinbatguy** [skyline-emu/skyline#1818]
Hi!

I Was Going To Play Pikuniku, And When The Devolver Digital Logo Disappears The Game **Fully Freezes**, Not Even The FPS Will Move.

Rarely, That Will Take A Bit More (Time To The SectorDub Logo To Appear)

Can You Guys Fix This?

Thanks.

**Comment by Crytonics** [comment]
Don't make Issues about games, if you have problem with games you can ask in our [Discord](https://discord.gg/XnbXNQM) server in support channel.
