### ISSUE TITLE
Crashes on Mali GPUs on recent versions

### ISSUE THREAD

**Issue by Nobiy1** [skyline-emu/skyline#1820]
I want to report that in versions of the emulator after 1280, the graphics and the launch of games break.
in the latest versions of the emulator, the game just freezes after a couple of seconds and broken graphics are in place with this.
sonic mania: flickering red screen
super mario odysey:
freezes after a few seconds, there are no graphics breakdowns.
celeste: black screen and wind sound.
sonic forces: broken graphics.
just Shapes and beats: black screen and 60 fps.
and I want to repeat, all these games freeze a few seconds after launch.
I want to say a pleasant moment is increased fps and fixing the display of fps.
version 1287 of the game does not freeze, but there are all the above described problems with graphics.
version 1299 has no graphics issues but the game freezes after a few seconds.

**Comment by Maxoper** [comment]
Can confirm on Pixel 6

**Comment by Ignite2022** [comment]
Same here on Xiaomi 11t

**Comment by AdriFarofenix23** [comment]
Same in Xiaomi 11 t

**Comment by Naho-sama** [comment]
Same in Poco X3 GT

**Comment by EmulationChannel** [comment]
Same in Samsung Galaxy S21+ EXYNOS 2100

**Comment by subhagamer** [comment]
Same in Realme X7 max

**Comment by AdriFarofenix23** [comment]
Subhagamer is happens but in other games the launch of the games and the graphics break

**Comment by HarayaDatratama** [comment]
I test game on mali g610 mc6 (realme gt neo 3).
Version 1341, game gun gore and cannoli, sonic mania, super crush ko all stuck on first screen
![Screenshot_2022-09-04-10-01-39-11_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/4675452/188295303-45c0d38d-8809-4a0a-a6a5-f5d70382f724.jpg)

**Comment by Dharmeshjd** [comment]
I try all versions app.. and i run start game 
Game are freez .. let's go pikachu

Snapdragon processor work but mali prosessor not supported.. pleace option Mediatek prosessor 😑

**Comment by nohgg** [comment]
same here on s10e mali G-76

**Comment by Dharmeshjd** [comment]
Mediatek prosessor not properly work skyline and gpu driver not supported

**Comment by subhagamer** [comment]
> Mediatek prosessor not properly work skyline and gpu driver not supported

Works on skyline in ver1280

**Comment by Dharmeshjd** [comment]
![Screenshot_20220906_182413](https://user-images.githubusercontent.com/106524662/188640536-9af198d6-1c88-4261-8c56-b20dbcfb5cdd.jpg)
V1280 run game then freez start-up 😑

**Comment by Dharmeshjd** [comment]
Any play let's go pikachu Mediatek prosessor skyline any version

**Comment by Wolfstar786** [comment]
Redmi 9 prime not working many games

**Comment by accuratesoftware** [comment]
redmi k50 pro, latest version not freezing games is 1287 for me (1288 starts freezing)

**Comment by HarayaDatratama** [comment]
super crush ko on 1288 work in menu but font missing. Mali g610
![Screenshot_2022-09-07-18-24-04-16_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/4675452/188867539-b719cef8-4b41-4e9e-aedc-d77a527f67f2.jpg)

**Comment by Bhood23** [comment]
Mali G57 Sonic Mania Doesn't Go past SEGA logo and It doesn't crash It's on like 80FPS

**Comment by Suenco** [comment]
Can confirm! Not launching any games! Please support Mali gpu gpus.

**Comment by Manish5437J** [comment]
Skyline emu not working on  Mali-G76 MC4 mi note 10s please fix this

**Comment by Manish5437J** [comment]
Please fix this so the mail gpu can rum skyline emu

**Comment by kotx** [comment]
Similar issue on Pixel 6a. Hope (at least partial) Mali support comes with gpu-new soon!

**Comment by Preafericitul** [comment]
Where do I download versions 1280 and early ,as I couldn't find them anywhere...can anyone put a link please? I have an s22 ultra ,exynos and can't run anything ,black screen then crashes . Thank you!

**Comment by Manish5437J** [comment]
[skyline-1280-release.apk.zip](https://github.com/skyline-emu/skyline/files/9856428/skyline-1280-release.apk.zip)
This is the file

**Comment by Preafericitul** [comment]
> [skyline-1280-release.apk.zip](https://github.com/skyline-emu/skyline/files/9856428/skyline-1280-release.apk.zip) This is the file

Thank you!

**Comment by castlenova69** [comment]
Confirm Crash on any game startup, Samsung galaxy note 10 lite

**Comment by AndresNorm** [comment]
![Uploading Screenshot_20221028_181539.jpg…]()

**Comment by AndresNorm** [comment]
![Screenshot_20221028_181539](https://user-images.githubusercontent.com/41192166/199284961-cd0107cf-6ae6-4f30-8366-616a29ad8ce5.jpg)

**Comment by HarshNarayanJha** [comment]
Can confirm on Samsung Galaxy S20 ( for Pokemon Sword)

**Comment by Swizzlefowl** [comment]
Fixed with the merging of the latest PR.

**Comment by subhagamer** [comment]
@AndresNorm do you know which commit has the fixes?
