### ISSUE TITLE
Fix information ui design that make play button invisible

### ISSUE THREAD

**Issue by yhak22** [skyline-emu/skyline#1823]
Hi,
The problem happened if the game has long name .
So the info ui need to be a little bit bigger .
Here is what i mean .
![Screenshot_20220827-145516](https://user-images.githubusercontent.com/23446817/187029176-c4d53283-75b7-4343-b76d-0ea889cc0aad.png)
This problem make the play button and shortcut button 
Invisible .
Thanks devs for hard working 💪💪

**Comment by dimaxdqwerty** [comment]
```
android:maxLines="1" 
android:ellipsize="end"
```
2 lines in game title textview

**Comment by Crytonics** [comment]
@lynxnb

**Comment by lynxnb** [comment]
Thanks for the report.

**Comment by yhak22** [comment]
You can make the text move from right to left instead of changing the box size .
This will solve the long name problem.
👍👍

**Comment by Yugiohgx** [comment]
Good

**Comment by Yugiohgx** [comment]
Nice 👍

**Comment by Yugiohgx** [comment]
Bout full

**Comment by Yugiohgx** [comment]
Wonderful

**Comment by AbandonedCart** [comment]
@dimaxdqwerty `marquee` is much cleaner than ending up with "BANDAI NAMCO Ent..."

**Comment by yhak22** [comment]
@lynxnb 
Last build 1338 increase the problem now the text is hide the buttons completely .
I think the font size must be smaller .
Or make the ui appears in the middle of the screen instead on bottom . 👍👍

**Comment by lynxnb** [comment]
Fixed by #1960
