### ISSUE TITLE
Please Make Skyline Emulator can playable in Mediatek and other

### ISSUE THREAD

**Issue by Hirariserla** [skyline-emu/skyline#1854]
Please Make Skyline Emulator can playable in Mediatek and other. Because I poor to buy nitendo switch, PC or Gamesir x2.

**Comment by Sovietfowl** [comment]
Duplicate of issue #1820.

**Comment by guranu** [comment]
Get a job.

**Comment by Allatel** [comment]
nobody commenting that he has no switch, zulul
