### ISSUE TITLE
Implement In-app "updater" function

### ISSUE THREAD

**Issue by Haprus** [skyline-emu/skyline#1865]
I feel like it's a hassle having to download newer builds manually every time some commits get added.

**Comment by Crytonics** [comment]
Well i don't think they will add that, because they will put Skyline on play store in future

**Comment by dimaxdqwerty** [comment]
> Well i don't think they will add that, because they will put Skyline on play store in future

Then there is no sense in in-app updater. And I don't think it's a good idea to add internet things in emulator because in android you need permission for internet in app (which is not great)

**Comment by AbandonedCart** [comment]
@dimaxdqwerty Too late - https://github.com/skyline-emu/skyline/blob/ftx1/app/src/main/AndroidManifest.xml#L5

**Comment by MrHaplus** [comment]
> Well i don't think they will add that, because they will put Skyline on play store in future

I'm talking about nightly builds, not releases.

**Comment by jin81790** [comment]
I've got the latest update of the skyline emulator and every time I play pirate warriors 3 final chapter dressrosa trembles the game crashes at the end when the credits rolls in

**Comment by lynxnb** [comment]
We plan to release the app on the Google Play Store, as such an updater is not planned.
