### ISSUE TITLE
Animal Crossing:New Horizons stuck in black screen

### ISSUE THREAD

**Issue by 7switchuser7** [skyline-emu/skyline#1870]
Stuck on black screen

Version:1351

Android Version:12

Phone Name:Samsung Galaxy A33 5G

The same issue happens on daijisho emulator because in order to play in daijisho emulator, It requires you to install skyline. 
![Screenshot_20220918-130405_Skyline](https://user-images.githubusercontent.com/113816482/190886701-306cb491-96ee-40f9-9de4-b1ca91f2a857.jpg)

**Comment by Sovietfowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.
