### ISSUE TITLE
Oculus Quest 2 Support(Native file browser)

### ISSUE THREAD

**Issue by JustAHippo** [skyline-emu/skyline#1886]
The Oculus Quest 2 does not have a native file browser/selector and fails to run Skyline because you cannot select keys and game files. Would really like to see this implemented at some point.

**Comment by jin81790** [comment]
Pirate warriors 3 cutscenes are always blank and most of the time it crashes

**Comment by JustAHippo** [comment]
> Pirate warriors 3 cutscenes are always blank and most of the time it crashes

you seem lost lmao. wrong issue?

**Comment by kote2345** [comment]
Update your Quest 2 to the latest firmware and Skyline will work
![com oculus shellenv-20221025-155941](https://user-images.githubusercontent.com/62496056/197768177-7207bd0c-6e3a-44b6-b5ea-44390ebc99dd.jpg)

**Comment by JustAHippo** [comment]
wait no fricking way i just missed that. thats insane!

**Comment by JustAHippo** [comment]
Celeste works on latest with Turnip, I will close this issue since file browser just got added!
