### ISSUE TITLE
git error

### ISSUE THREAD

**Issue by goldug** [skyline-emu/skyline#1905]
When running "git submodule update --init --recursive app/libraries/shader-compiler" I get this error:
```
K:\git\skyline>git submodule update --init --recursive app/libraries/shader-compiler
Submodule 'Shader Compiler' (https://github.com/skyline-emu/shader-compiler.git) registered for path 'app/libraries/shader-compiler'
error: unable to create symlink include/shader_compiler: File name too long
Unable to chekout "a4713982b9e596e8fdebe55c1601758815cd3850" in submodule path "app/libraries/shader-compiler"
```
I've tried multiple times, but to no avail. Any idea why this happens and how to fix it?

**Comment by Sovietfowl** [comment]
Hi! Can you come to our discord instead as it will be way easier to debug this problem there as we have lots community members and devs who might know what's going on.

**Comment by goldug** [comment]
Yeah, never mind. I used Git Bash instead of the Windows command line and it worked. I really should learn to use Git Bash instead of Windows crap...
Closing it myself, but this could maybe help some other noob in the future :)

**Comment by goldug** [comment]
Yeah, never mind. I used Git Bash instead of the Windows command line and it worked. I really should learn to use Git Bash instead of Windows crap...
Closing it myself, but this could maybe help some other noob in the future :)
