### ISSUE TITLE
File permission potentially lost between updates

### ISSUE THREAD

**Issue by AbandonedCart** [skyline-emu/skyline#1911]
Just an FYI type thing that between versions, the permission to the rom folder can get dropped. This results in an instant crash (upon loading a game) that is not actually a problem with the app itself. It can be solved by simply selecting the rom folder again and allowing access. 

The crash traces back to [EmulationActivity.kt#L247-L249](https://github.com/skyline-emu/skyline/blob/ftx1/app/src/main/java/emu/skyline/EmulationActivity.kt#L247-L249). I wrapped 247 - 257 in a try, catch for `SecurityException` locally that prompts to allow the folder again to verify, but that is a super inelegant solution. It would probably be better to verify the permission is still valid before it gets to that point.

**Comment by chostdz** [comment]
Wow

**Comment by AbandonedCart** [comment]
@chostdz ?

**Comment by android-1995** [comment]
I think it would be better to check the search location in MainActivity
```
//MainActivity
    private fun setupAppList() {
        binding.appList.adapter = adapter

        val itemWidth = 225
        val metrics = resources.displayMetrics
        val gridSpan = ceil((metrics.widthPixels / metrics.density) / itemWidth).toInt()

        binding.appList.layoutManager = CustomLayoutManager(gridSpan)
        setAppListDecoration()
        preferenceSettings.searchLocation.let { searchLocation ->
            if (searchLocation.isEmpty()) {
                documentPicker.launch(null)
            } else {
                val searchLocationUri = Uri.parse(searchLocation)
                try {
                    contentResolver.takePersistableUriPermission(searchLocationUri, Intent.FLAG_GRANT_READ_URI_PERMISSION)
                } catch (e : SecurityException) {
                    //clearData
                    preferenceSettings.searchLocation = ""
                    // reauthorize
                    documentPicker.launch(searchLocationUri)
                }
            }
        }
    }
```

**Comment by AbandonedCart** [comment]
@android-1995 Ideally, you wouldn't depend on the exception at all. That is why this was an issue and not a PR. SAF is a dumpster fire, but may have some sort of method to verify similar to the `checkSelfPermission` since they enforce using it.

**Comment by AbandonedCart** [comment]
Actually, upon further investigation, it appears it may be (yet another) bug in Android. Simply catching the exception to ignore it should be enough. https://stackoverflow.com/a/67945576/461982

**Comment by android-1995** [comment]
Well, in fact, I have never experienced the loss of authority.
```
    try {
        //This situation will trigger SecurityException?
        contentResolver.openFileDescriptor(searchLocationUri , "r")
    } catch (e : SecurityException) {
        //clearData
        preferenceSettings.searchLocation = ""
        // reauthorize
        documentPicker.launch(searchLocationUri)
    }
```
