### ISSUE TITLE
ChromeOS Intel CPU

### ISSUE THREAD

**Issue by channelup69** [skyline-emu/skyline#1914]
Since ChromeOS can run Android apps I tried installing the emulator and it did not launch. Just wondering if a Intel Chromebook will be able to run this emulator? Thanks

**Comment by kotx** [comment]
Not an expert, but I believe a factor could be Vulkan support. Does the app VulkanCapsViewer show anything?

**Comment by Swizzlefowl** [comment]
This will probably be never supported as it's a x86-64 CPU and skyline is ARM only.
