### ISSUE TITLE
Skyline crashes when opening game

### ISSUE THREAD

**Issue by daosidfja** [skyline-emu/skyline#1918]
I don't know what to do, I've tried multiple tutorials, dumping keys and even downgrading but every time I try to boot a game, it crashes. Any help? (Samsung Galaxy A12)

**Comment by AbandonedCart** [comment]
Have you tried going to the app settings, selecting search location, picking the folder again (even if you've already done it), and clicking "USE THIS FOLDER"?

**Comment by daosidfja** [comment]
Yes, still crashes on boot.

**Comment by AbandonedCart** [comment]
Thanks for checking. Seems I can't spare you needing a log.
