### ISSUE TITLE
Wrong NpadId &NpadManager::id value in some games

### ISSUE THREAD

**Issue by dimaxdqwerty** [skyline-emu/skyline#1928]
Found the bug (or maybe it's not a bug) in https://github.com/skyline-emu/skyline-games-list/issues/582 and maybe some other games have this bug.  
`NpadId &NpadManager::id` has weird value (see screenshot).
![image](https://user-images.githubusercontent.com/70838468/198828032-447b3f0e-03cd-4ed1-9a08-2b8df0e4afa8.png)
So I made fix something like this (idk if it's hacky or not):
[npad.txt](https://github.com/skyline-emu/skyline/files/9893525/npad.txt)

**Comment by bylaws** [comment]
@german77 what's the expected behaviour here?

**Comment by german77** [comment]
`supportedIds` is just a list of allowed devices. It doesn't need to necessarily match an existing device. All extra values can be safely ignored.

**Comment by dimaxdqwerty** [comment]
fixed in https://github.com/skyline-emu/skyline/pull/1930
