### ISSUE TITLE
There is No Game: Wrong Dimension (Graphics Issue)

### ISSUE THREAD

**Issue by Walegy** [skyline-emu/skyline#1929]
Hello, I have encountered a problem with one of my NSP games, and the game is called, There is No Game: Wrong Dimension. And there's this odd graphical glitch that happens when opening and playing the game. Like everything is black-ish and hard to make out. Is there anything I can do to fix this issue?

![Screenshot_20221029-134344](https://user-images.githubusercontent.com/107286645/198848770-83d16dfe-5270-486c-a511-360f72bc2681.png)

**Comment by Swizzlefowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.

**Comment by Walegy** [comment]
Ah okay, good to know.
