### ISSUE TITLE
Pokémon crash issue

### ISSUE THREAD

**Issue by bobbymc1985** [skyline-emu/skyline#193]
Hi. Pokémon lets go eevee and pickachu. As well sword all crashes at the start. Is there an issue with this? Im using my Xperia 1 ii Snapdragon 865

**Comment by bylaws** [comment]
That's good, seems that the exceptional signal handler is working well!

**Comment by PixelyIon** [comment]
We aren't taking requests for individual games being supported at the moment, it's completely up to a developer if they want to take a look at it or not as #168 and other things take higher priority.
