### ISSUE TITLE
Factorio game is not working

### ISSUE THREAD

**Issue by x1unix** [skyline-emu/skyline#1970]
Sorry, don't know how to properly report compatibility issues but Factorio game doesn't work.

Old (v0) version shows Factorio logo and startup sound but stops there.
A new updated version just shows blank screen.

![image](https://user-images.githubusercontent.com/9203548/200689047-62dac512-c3f8-4ff6-91ed-14949c9940e0.png)

I attached logs to this issue, hope they will be useful.

[logs.zip](https://github.com/skyline-emu/skyline/files/9965704/logs.zip)

Device: Google Pixel 6
OS: Android 13

**Comment by Swizzlefowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.

**Comment by x1unix** [comment]
@Swizzlefowl thank you, moved issue to the games list repo - https://github.com/skyline-emu/skyline-games-list/issues/1185
