### ISSUE TITLE
Bajones de FPS

### ISSUE THREAD

**Issue by GLITCHE-404** [skyline-emu/skyline#1994]
Buenas tardes, quería preguntar por qué el juego de  Cadeceno of Hyrule: Crypt of The NecroDancer featuring The legend of zelda. Me va bien pero de repente se le baja los FPS y hay partes en el mapa del juego que va bien y después de cae los FPS, tampoco se ve las letras. También intenté descargar probar el dark souls remasterizado, pero se queda en negro y no carga el juego. ¿Será mi teléfono o el emulador? 
Mi teléfono es un Infinix NOTE 12, versión de Android 12, CPU de HELIO G96, RAM 8 GB + 5 # @
![Screenshot_20221116-164159](https://user-images.githubusercontent.com/118394541/202289730-4f189e04-fc64-424b-99cf-a10f0516338e.jpg)
![Screenshot_20221116-164154](https://user-images.githubusercontent.com/118394541/202289742-8dcbd334-4689-434b-b04d-984666e0c505.jpg)
![Screenshot_20221116-164144](https://user-images.githubusercontent.com/118394541/202289746-2afdae61-ccee-478b-b767-c6c61bb0b330.jpg)
![Screenshot_20221116-164134](https://user-images.githubusercontent.com/118394541/202289766-eda929de-e976-4b95-a806-80ca8f6efe31.jpg)

**Comment by marcemira** [comment]
Hola @GLITCHE-404 no soy staff member, pero la respuesta sería fácil. El emulador es altamente experimental, es decir que no podés esperar que nada funcione adecuadamente, nada. Tampoco vale la pena quejarse al respecto, los desarrolladores trabajan gratis para hacer lo que les apasiona, funcione un poquito mejor día a día. Paciencia, de a poquito va a ir mejorando 💪🏻

**Comment by Swizzlefowl** [comment]
Please use English as this an English only forum.
