### ISSUE TITLE
Screen freeze 

### ISSUE THREAD

**Issue by jin81790** [skyline-emu/skyline#2002]
I'm using poco x3 pro and it has the Android 11,860 snapdragon,8gb/128gb and no matter what game I play after 10-15 minutes of proper gameplay the screen freezes and I have to exit the game and start again ,this didn't happen with the older builds so any kind of advice would be really really helpful. Thanks.

**Comment by Swizzlefowl** [comment]
These type of questions would be better answered at our Discord server there is no need to make issues for them.
