### ISSUE TITLE
Haptic feedback - Vibration on pressed buttons

### ISSUE THREAD

**Issue by Dougzen** [skyline-emu/skyline#2008]
Hello guys.

Would be interesting to have the Haptic Feedback inside on Skyline emulator.

Thank you for your attention.

**Comment by Swizzlefowl** [comment]
Already done with https://github.com/skyline-emu/skyline/issues/100.

**Comment by Dougzen** [comment]
Sorry, I was not clear enough.

Haptic Feedback is actually for On-Screen buttons.
(Virtual buttons).

I could not find in this emulator.

**Comment by ilabraznikov** [comment]
УДАЛИТЕЕЕ МЕЕЕНЯЯЯЯЯ ОТСЮЮЮЮДАААААА!!!!!!!

пн, 21 нояб. 2022 г., 19:26 Dougzen ***@***.***>:

**Comment by Swizzlefowl** [comment]
@Dougzen Yeah that sounds like a good feature but rather reopening it can you make a new issue and make it more clear you mean Haptic feedback for On-screen buttons.
