### ISSUE TITLE
Haptic feedback - On-screen buttons - Vibration

### ISSUE THREAD

**Issue by Dougzen** [skyline-emu/skyline#2009]
Hello guys.

As recommended, i'm making a new issue:

Would be interesting to have the Haptic Feedback for On-Screen buttons. Vibration feature.

Example:
If the "A" button be pressed On-Screen, you could feel the device vibrating.

Thank you for your attention.

**Comment by Dougzen** [comment]
Okay I guess, someone had recommended me to make a "issue" instead a PR.

**Comment by AbandonedCart** [comment]
@Dougzen Yes, you made the issue and I submitted a PR to add the feature.

**Comment by Swizzlefowl** [comment]
Merged on the latest Build.
