### ISSUE TITLE
SkyLine Emulator Working with video output

### ISSUE THREAD

**Issue by Dominik20074** [skyline-emu/skyline#201]
![Screenshot_20210708_231640_skyline emu](https://user-images.githubusercontent.com/84296396/124991921-92c85d00-e042-11eb-85c5-1f2f37824e98.jpg)

**Comment by Dominik20074** [comment]
Its Not Fake!!!!!!

**Comment by PixelyIon** [comment]
We are aware that SpaceNX runs.. I don't see why this is an issue.
