### ISSUE TITLE
snapdragon 8 +Gen 1

### ISSUE THREAD

**Issue by winsonlau17** [skyline-emu/skyline#2021]
just ask skyline can work Snapdragon 8+ Gen 1 ?phone ROG 6。cant to play pokon let go pikachu...go inside black screen，anyone can help?

**Comment by winsonlau17** [comment]
Uploading 2022-11-24-23-25-13.mp4…

**Comment by LegendAMN** [comment]
There in no proper way of fixing that issue. The emulator needs more development.

Ps i wanted to play Pkmn lets go so bad but had to stick with citra mmj and pokemon USUM.
:(

**Comment by Swizzlefowl** [comment]
Ask these type of questions in our Discord server.
