### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by Ty-TDM** [skyline-emu/skyline#2022]
The message that I received said: 

thread has panicked at 'called 'Result::unwrap()' on an 'Err' value: Custom { kind: Other, error: "Result code: 514" }', src\utils.rs:142:24 

It said that I should send a message to the developers, and I'm relatively new to modding, so is there any advice that you can give me for this issue???

**Comment by Swizzlefowl** [comment]
These type of question should be best asked in our Discord server.
