### ISSUE TITLE
Undertale Glitches

### ISSUE THREAD

**Issue by EliasGerliz** [skyline-emu/skyline#2031]
Hey!
I have some Glitches at Undertale (My device is Redmi Note 10 Pro - Snapdragon 732G - 6 GB RAM)
![Screenshot_2022-11-28-15-06-31-550_skyline emu](https://user-images.githubusercontent.com/114945583/204302497-503f6871-88a4-41f7-b85b-8f9f30f63346.jpg)
How to fix ist?

**Comment by EliasGerliz** [comment]
*it

**Comment by Swizzlefowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.
