### ISSUE TITLE
Implement on-screen stick sensitivity controls

### ISSUE THREAD

**Issue by 777joe** [skyline-emu/skyline#2035]
It would be nice to have better stick settings like sensitivity curves and deadzones. Currently if we want to increase sensitivity of a stick, the only way to do that is to decrease the size of the sticks in the on-screen layout editor, but this will also make other buttons smaller making them difficult to use. Ability to change the size of individual buttons and sticks would also be helpful.

**Comment by Fkprdcg** [comment]
Jxkxc
