### ISSUE TITLE
iOS support possibility

### ISSUE THREAD

**Issue by MaKiPL** [skyline-emu/skyline#2045]
Hi! 
What is the possibility to port the project for iOS support? Does that use a lot of Android-exclusive usage to make it working? Maybe I can be helpful in any way to make it working on Apple platforms?
EDIT: I'm an Apple registered developer so I might be helpful with deployment and preparing the code unless it's heavily Android platform related. Any kind of information is helpful

**Comment by dima-xd** [comment]
Answer is here https://github.com/skyline-emu/skyline/discussions/387#discussioncomment-2171264

**Comment by Swizzlefowl** [comment]
What Dima said pretty much.
