### ISSUE TITLE
Instalação do skyline

### ISSUE THREAD

**Issue by GuilhermeDunkly** [skyline-emu/skyline#2046]
Olá, eu estou tentando instalar o skyline a um tempo, e quando eu baixo o arquivo e tento instalar o app acontece um problema com o instalador disendo que não foi possível analizar o pacote 
*Nota o arquivo do skyline aparece sem foto ,eu também notei que o arquivo pesa menos megabytes do que aparece no github

**Comment by Mononono87** [comment]
você está no Android 9 ou inferior, que não é suportado por este aplicativo, sua única solução é usar uma ROM personalizada para obter o Android 10 ou superior ou um novo telefone.

**Comment by GuilhermeDunkly** [comment]
Se eu baixar o skyline mod,tipo personalizado

**Comment by GuilhermeDunkly** [comment]
É que eu sou usuário de Android 8.1.0

**Comment by Mononono87** [comment]
não temos um mod skyline?

**Comment by Mononono87** [comment]
seu telefone é muito antigo para o Skyline
