### ISSUE TITLE
How much approximately left to wait graphics?

### ISSUE THREAD

**Issue by BIGD15** [skyline-emu/skyline#205]

**Comment by bylaws** [comment]
About 177013 hours, hope that's okay with you

**Comment by IvarWithoutBones** [comment]
We do not have an ETA on this. It'll be a while, but that's all the information we have. 

Also, please don't ask questions like these in the form of github issues, we like to keep them development oriented only. Though we are always open for any questions on our Discord server, linked in the projects readme.

**Comment by xiaoxiaonaonao** [comment]
GO，China！NSemulator！2022，1！
中国开发者在2022年1月份将推出第二个模拟器，现在已经测试可以玩塞尔达，让我们放弃这个废物！来中国吧！中国的百度贴吧社交欢迎你
