### ISSUE TITLE
Game Dev Story save game bug

### ISSUE THREAD

**Issue by rayqusa** [skyline-emu/skyline#2057]
device:
Xiaomi Redmi note 8 Pro
helio G90T 8/128
stock Rom

game dev story, usually after 10 year played suddenly game error and the save game is completely erased. I have experienced this twice. this thing really annoying. does another game have similar issue?

**Comment by Mononono87** [comment]
It may be a game issue,I know some games such as Cuphead had this issue but now are fixed.i would say to wait

**Comment by Swizzlefowl** [comment]
Don't make game-specific issues.

**Comment by rayqusa** [comment]
I think it is skyline bug. sorry
