### ISSUE TITLE
When approximately graphics will appear?

### ISSUE THREAD

**Issue by BIGD15** [skyline-emu/skyline#206]

**Comment by bylaws** [comment]
Please do not spam Isseues. Create another issue and we will be forced to ban your account.

**Comment by xiaoxiaonaonao** [comment]
不要靠这垃圾，唯唯诺诺的废物！GO，China2022，1？NS！？2022年的1月份中国开发者会发布可以玩的NS模拟器第二个，现在已测试塞尔达正常

**Comment by PixelyIon** [comment]
> Do not rely on this garbage, wishy-washy waste! Chinese developers will launch a second emulator in January 2022, now tested to play Zelda, let's give up this crap! Come to China! China's Baidu Post Social welcomes you!

I'd love to see one that doesn't blatantly steal code from other FOSS emulators like Skyline and yuzu :stuck_out_tongue:

**Comment by wmdhs12138** [comment]
> 不要靠这垃圾，唯唯诺诺的废物！GO，China2022，1？NS！？2022年的1月份中国开发者会发布可以玩的NS模拟器第二个，现在已测试塞尔达正常

草泥马比，在这里丢人现眼

**Comment by cohaereo** [comment]
> 
> 
> 不要靠这垃圾，唯唯诺诺的废物！GO，China2022，1？NS！？2022年的1月份中国开发者会发布可以玩的NS模拟器第二个，现在已测试塞尔达正常

动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region

**Comment by XiaFan-Rgr** [comment]
你行你上

**Comment by BIGD15** [comment]
?

**Comment by darkpigeon** [comment]
How about learning to speak English properly? This place ain't no mainland China

**Comment by bylaws** [comment]
Can we not?
