### ISSUE TITLE
Share link prod.keys pls

### ISSUE THREAD

**Issue by ZhakiThePro** [skyline-emu/skyline#208]
How to get prod.keys?

**Comment by strikersix23** [comment]
They cannot distribute to it being a system file, it is illegal to do so.

However you can dump the keys from your switch
https://yuzu-emu.org/help/quickstart/#dumping-prodkeys-and-titlekeys

**Comment by ZhakiThePro** [comment]
Ok sorry,but thanks

**Comment by strikersix23** [comment]
Your welcome

**Comment by AyderProgramic** [comment]
You can find prod.keys in the browser write, but you can and search
