### ISSUE TITLE
[implement]service::csrng

### ISSUE THREAD

**Issue by sepcnt** [skyline-emu/skyline#209]
a scale of game tested require this module(maybe i can make one

**Comment by bylaws** [comment]
Would be helpful if you put a list of games requiring it in the issue, also feel free to join our discord if you feel like implementing it

**Comment by sepcnt** [comment]
i guess that it's a randomize module 
 while titan-size games may crash mainly due to other lacks 
here are some small games that i can CERTAIN that the absence of "csrng" is the arch-criminal

Prison Princess [0100F4800F872000] 
Pokemon Cafe Mix [010072400E04A000]
Paint your Pet[0100AB90129CA000]

crash log frag:
--------------------------------------------------------------------
W377HOS-0GetService: Service has not been implemented: "csrng"
D377HOS-0SignalProcessWideKey: Signalling 0x8038A734C for -1 waiters
W377HOS-0HandleRequest: Cannot find function in service 'am::IApplicationFunctions': 0x16 (22)
--------------------------------------------------------------------

**Comment by sepcnt** [comment]
i guess that it's a randomize module 
 while titan-size games may crash mainly due to other lacks 
here are some small games that i can CERTAIN that the absence of "csrng" is the arch-criminal

Prison Princess [0100F4800F872000] 
Pokemon Cafe Mix [010072400E04A000]
Paint your Pet[0100AB90129CA000]

crash log frag:
--------------------------------------------------------------------
W377HOS-0GetService: Service has not been implemented: "csrng"
D377HOS-0SignalProcessWideKey: Signalling 0x8038A734C for -1 waiters
W377HOS-0HandleRequest: Cannot find function in service 'am::IApplicationFunctions': 0x16 (22)
--------------------------------------------------------------------
