### ISSUE TITLE
exynos CNTFRQ_EL0 problem?

### ISSUE THREAD

**Issue by ikhoeyZX** [skyline-emu/skyline#2105]
Looks like after version "1564 - Work around invalid values in CNTFRQ_EL0 register"
All games run only 1fps with fps counter 60fps(without fps trottling) / 112fps (with fps trottling) in my exynos device (samsung m33 with exynos 1280)

**Comment by gdudehd** [comment]
MAX

**Comment by johan790** [comment]
Xed

**Comment by lynxnb** [comment]
Could you try running this app and post the values reported by the app, using the share button?
https://cdn.discordapp.com/attachments/674488052118323204/893077275455684638/freq-release.apk

**Comment by ikhoeyZX** [comment]
Timer frequency: 3075992275
Estimated frequency: 26005231 (sampling interval: 1s)
Estimated frequency: 26005256 (sampling interval: 2s)
Estimated frequency: 26000793 (sampling interval: 5s)
Estimated frequency: 26000512 (sampling interval: 10s)
Brand: samsung
Model: SM-M336B
Board: s5e8825
SDK: 33

**Comment by ikhoeyZX** [comment]
Tested game: 
https://github.com/skyline-emu/skyline-games-list/issues/1229

**Comment by PixelyIon** [comment]
Seems like it's off, we'll add a fix for this board as well.

**Comment by ikhoeyZX** [comment]
Tested using skyline 1754 and it's still 1fps

**Comment by lynxnb** [comment]
What's happening is, the phone was never powerful enough to run games properly, but before the two fixes it was reporting invalid fps values. Now after the fixes, you get a glimpse of the real performance. The Galaxy M33 is a low end phone with a low end Mali GPU in it. It might run better while we'll improve performance for Mali, but don't expect any heavy games running well out of that phone.
