### ISSUE TITLE
iOS and iPadOS support?

### ISSUE THREAD

**Issue by nougator** [skyline-emu/skyline#211]
I want this just be a discussion, I know, it's an implementation that would be done in the snap of a finger.
A misconception about iOS is that it's too closed to do an emulator. That's not entirely true you probably can't and don't want to publish it on the store but you can publish it on AltStore like Dolphin.

iOS/iPadOS has some advantage over android (like android has some advantage over iOS):
- Better haptic feedback (very close to joycons).
- Good controller support.

**Comment by bylaws** [comment]
Address space limitations imposed by Apple on iOS make this practically impossible without jailbreaking and the GPUs are absolute trash. Android haptic is plenty fine for emulating the switch and controller support is also fine with our mapping tool

**Comment by bylaws** [comment]
We will gladly accept the changes if some other developer does it though

**Comment by nougator** [comment]
I also thought about doing some kind of webassembly recompiler but it would require WebGPU to have good performances. Strongly believe in heavy web emulation, look at [v86](https://github.com/copy/v86). Anyway I was just saying random ideas.

**Comment by bylaws** [comment]
> I also thought about doing some kind of webassembly recompiler but it would require WebGPU to have good performances. Strongly believe in heavy web emulation, look at [v86](https://github.com/copy/v86). Anyway I was just saying random ideas.

Yeah that's not really viable for switch emulation, the overhead from it would be very significant as games often have 100s of MB of code and there are a lot of ops which would be very difficult/expensive to implement considering the limited instruction set provided by webasm.

I should note the main part of skyline is NCE, we can skip any JIT by running the game code directly on the arm64 CPU of phones with just a little patching beforehand, this allows basically having zero CPU overhead.

**Comment by mayweather911** [comment]
For me there should also be an iOS version because there is the alternative altstore and jailbreak now comes out every year!

**Comment by FinaleRoyale** [comment]
They've already given you reasons why they don't want to do it, and why it isn't already being worked on. The amount of code to operate would be too big (100s of MBs), and many ops that would be too difficult to implement on iOS. That being said, if another developer chooses to work on that,  they will gladly accept the changes.

**Comment by PixelyIon** [comment]
@FinaleRoyale effectively purveys our stance on the issue, it is not something we plan on doing at any point so I'll be closing this issue
