### ISSUE TITLE
SSBU crashing, Freezing and infinite loading 

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [skyline-emu/skyline#2147]
Hope  this will be addressed soon also fps drops and stutters, appreciated 

On Edge v24, phone is SD 8 1gen plus with adreno 730, 8gb ram with 8gb ram plus+

Docked mode
615.50 driver
Slot scale 6 
Triple buffer enabled 
Use direct memory 
Force max gpu
Rest default 

Ssbu V13.0.1

**Comment by Swizzlefowl** [comment]
Don't make game-specific issues here.
