### ISSUE TITLE
Add it please 🙏

### ISSUE THREAD

**Issue by pokeholmes001** [skyline-emu/skyline#2148]
It's a CPU and battery temperature meter, but running this app in the background consumes a lot of RAM, so I'd really like to add this to the emulator please 🙏
Translated by Google
![IMG_20230113_211729](https://user-images.githubusercontent.com/97064511/212440798-51c7f260-b371-4b5e-97ea-940b4ebe4b72.jpg)

**Comment by pizza-10** [comment]
Really good idea. There are separate applications for this that ask for money.

**Comment by ArbestRi** [comment]
🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺

**Comment by lynxnb** [comment]
This won't be added for multiple reasons:
* It doesn't fall into the scope of an emulator.
* We'd have to use the same methods that app does to get the readings, that effectively makes it redundant.
* It's not useful at all to know CPU and Battery temperature while playing, it's effectively a gimmick.

A RAM usage indicator might be implemented in the future, depending on if we see it adding value to the debugging experience or not. Those tools are not intended for general use as they don't provide any relevant information that the user can ultimately act upon.
