### ISSUE TITLE
Incompatibilità con Redmi 7a (Android 10)

### ISSUE THREAD

**Issue by Gennarof96** [skyline-emu/skyline#216]
Salve, ho notato dei problemi mentre provo a scaricare l'applicazione sul mio cellulare (nonostante abbia android 10)
Appena estraggo l'apk e la provo ad installare, mi dice sempre app non installata (ovviamente ho sempre controllato la memoria e tutte le altre cose... Ma mi sembra impossibile che non si installa sul mio cellulare)

**Comment by Gamemulatorer** [comment]
> Salve, ho notato dei problemi mentre provo a scaricare l'applicazione sul mio cellulare (nonostante abbia android 10)
> Appena estraggo l'apk e la provo ad installare, mi dice sempre app non installata (ovviamente ho sempre controllato la memoria e tutte le altre cose... Ma mi sembra impossibile che non si installa sul mio cellulare)

Hi, I have noticed some problems while trying to download the application on my mobile (despite having android 10)
As soon as I extract the apk and try to install it, it always tells me app not installed (obviously I have always checked the memory and all the other things ... But it seems impossible to me that it does not install on my mobile)

Maybe your phone does not fullfil the minimum android specs requirements.

**Comment by Gennarof96** [comment]
> > Salve, ho notato dei problemi mentre provo a scaricare l'applicazione sul mio cellulare (nonostante abbia android 10) 
> > Appena estraggo l'apk e la provo ad avere, mi dice sempre app non installato (ovviamente ho sempre controllato la memoria e tutte le altre cose... Ma mi sembra impossibile che non si installa sul mio cellulare)
> 
> Salve, ho notato dei problemi durante il tentativo di scaricare l'applicazione sul mio telefonino (nonostante abbia Android 10)
> Appena estraggo l'apk e provo ad installarlo, mi dice sempre app non installata (ovviamente ho sempre controllato la memoria e tutte le altre cose ... Ma mi sembra impossibile che non si installi sul mio cellulare)
> 
> Forse il tuo telefono non soddisfa i requisiti minimi delle specifiche Android.

Ah ok ok👌🏻👌🏻👌🏻
