### ISSUE TITLE
Every game freeze after short time playing 

### ISSUE THREAD

**Issue by yhak22** [skyline-emu/skyline#2164]
hi , devs.
i want to share my experience the i had starting 2 months ago until today's released ,
so i try most my games and found out that they freeze after about 10 min play.
in previous builds like from 12s to 15s build it was fine even if i play hours but after 15s build most games freeze.
all that on the free version , i don't know if the edge version  has the same problem ,
by the way i have SD865 with 8 ram.
thanks for hard work 😁

**Comment by Swizzlefowl** [comment]
You should probably come to our discord server and we will try to help, this issue is too ambiguous so I will be closing it.
