### ISSUE TITLE
Color screen on Pokemon let's go Pikachu

### ISSUE THREAD

**Issue by AdyAndrews** [skyline-emu/skyline#2165]
Pokemon let's go Pikachu is showing colourful screen on snapdragon 845 and I can't see few things like menu options character etc it's just showing pink , green and white colour can u please fix this problem asap ? Im big fan of Pokemon and always wanted to play on switch u guys  really working great on this project keep it up

**Comment by Swizzlefowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.
