### ISSUE TITLE
Super Kirby Clash Glitch Graphic And Sound Broken

### ISSUE THREAD

**Issue by TheBoxGame1234** [skyline-emu/skyline#2169]
hello, I have a question if it would be possible to fix errors in the game super kirby clash because when starting the game there is no button press sound and the game has a blue screen
![Screenshot_2023-01-28-18-15-33-569_skyline emu](https://user-images.githubusercontent.com/116956029/215280169-883a8c47-722e-4ae6-9cc0-193d633f1376.jpg)

my phone Xiaomi Mi 10T Lite 5G
Snapdragon 750G
Ram 6 GB
Driver: v0.502.0 Qualcom Propriety

**Comment by Crytonics** [comment]
@TheBoxGame1234 This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.
