### ISSUE TITLE
Sonic Mania runs too fast 

### ISSUE THREAD

**Issue by ChronDafter0** [skyline-emu/skyline#2172]
As far as I know, the whole game runs perfectly fine except for the fact that it's unplayably fast. The audio works just fine, sounds perfect, but the animations, it's all running at ~120fps. Is there a work around? I've already tried messing with the settings and nothing seems to have changed. I have a Samsung Galaxy S20, for reference.

**Comment by dusk77** [comment]
set the device refresh rate 60hz

**Comment by Crytonics** [comment]
Try changing system refresh rate to 60 and it should fix that

**Comment by Crytonics** [comment]
And @ChronDafter0  this is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.
