### ISSUE TITLE
Problem in fifa23 

### ISSUE THREAD

**Issue by Ahmed96108** [skyline-emu/skyline#2184]
I tried to open fifa23 in skyline edge and it's work as good. But it jet stuk as this picture
![Screenshot_20230206_063124_skyline emu](https://user-images.githubusercontent.com/124543119/216870430-c6046af0-ebfb-471b-957b-3fe031fbf191.jpg)
![Screenshot_20230206_063136_skyline emu](https://user-images.githubusercontent.com/124543119/216870452-4e3e0846-d2c9-43f9-a5dd-f7a98ee26209.jpg)
![Screenshot_20230206_063248_skyline emu](https://user-images.githubusercontent.com/124543119/216870471-acbdac83-9541-4bc3-87dc-6b32e25152cb.jpg)

**Comment by Ahmed96108** [comment]
My phone is huawei mate 30 pro

**Comment by Swizzlefowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.
