### ISSUE TITLE
Add multiplayer

### ISSUE THREAD

**Issue by BIGD15** [skyline-emu/skyline#219]
To play games like Splatoon 2 through internet

**Comment by bylaws** [comment]
probably wont be done ever or if it is it'll be >5 years

**Comment by sauradipdebnath** [comment]
Try to do that as fast as possible ( if possible)

**Comment by sauradipdebnath** [comment]
reopen this issue

**Comment by Aztroloe** [comment]
No.

**Comment by sauradipdebnath** [comment]
Because it may take long time
