### ISSUE TITLE
Why Screen Rotation and Portrait is required?

### ISSUE THREAD

**Issue by soundsnow** [skyline-emu/skyline#2196]
Rotate 90°, 180°, 270°
Switch is a hybrid console
You can play some special (vertical shooters, homebrew) games with a rotating monitor
But not everyone has those devices
![215977506-2f09608e-d31d-48f3-9a60-084d125608d5](https://user-images.githubusercontent.com/109885044/218616700-fb00bec4-b92d-4217-a9ec-0158dbbab8ab.png)

![dell-la2205wg-4](https://user-images.githubusercontent.com/109885044/218611615-29f18741-3eac-47f4-993d-8f874fbe8581.jpg)

**Comment by Crytonics** [comment]
This issue is the same as #2190 , I will close this issue and you can comment this there to have all in one place.
