### ISSUE TITLE
Portrait: 4 Button Layout Presets

### ISSUE THREAD

**Issue by soundsnow** [skyline-emu/skyline#2197]
It's made for PlayStation consoles
This is comparison
Move Video Screen to Top, Below Status Bar
Buttons Above Navigation Bar

PSVita: Dual Analog Pad (PSP Toggle)
PSP (PSVita Toggle)

Single Analog Pad (Digital Pad Toggle)
Digital Pad (Single Analog Toggle)
![image47](https://user-images.githubusercontent.com/109885044/218624319-ddb6f35a-96e5-48a8-84ff-64260e1aff31.png)

**Comment by Crytonics** [comment]
This issue is the same as #2190 , I will close this issue and you can comment this there to have all in one place.
