### ISSUE TITLE
Metroid Prime Remastered??

### ISSUE THREAD

**Issue by RandomizerGamerRIPLinky** [skyline-emu/skyline#2198]
I'm just curious as to when we might be able to expect to see MPR on Skyline. Already have it on my pc and switch, but would really like to get it on my phone.

**Comment by Crytonics** [comment]
No eta for games, you can ask in discord but devs are working hard.

**Comment by RandomizerGamerRIPLinky** [comment]
Understandable. Was just curious if it was being considered. I'm aware that things like this take tons of time, given the fact that it's going to take tons of coding for games to even work on emulation for android.
