### ISSUE TITLE
Basic Audio Implementation

### ISSUE THREAD

**Issue by PixelyIon** [skyline-emu/skyline#22]
The emulator currently doesn't output any sort of audio. Most basic Switch games use `audout` (https://switchbrew.org/wiki/Audio_services#audout:u) for audio. So, this should be implemented.

**Comment by bitocard** [comment]
How is the development going now and when can it be released

**Comment by Yvar192** [comment]
@bitocard We have no ETA at the moment, but #21 fixes this issue.
