### ISSUE TITLE
Needs UI Friendly way to Remove / Delete NSP / XCI Games/Software/DLC/Updates from Skyline Game Library Menu 

### ISSUE THREAD

**Issue by RFL0WGitPR** [skyline-emu/skyline#2218]
Skyline Emulator could use a UI Friendly way to manage storage data space on installed Games on Skyline Games Library Menu

The software and icon on the HOME Menu will be deleted to manage storage space.

This feature should remove all Game Data /Software Apps/ Screenshots, or videos for related title when user selects / press and holds a Game title on App.

User Presses and Holds Selected Game [contextual Pop Up menu appears] with management options such as Delete

Feature should work with both Touch / Pro Controller / 3rd party Bluetooth controller

**Comment by AbandonedCart** [comment]
Is there some screenshot / video feature I missed? I know the Switch has a share button, but I didn't think the emulator had one specific to the emulator. If it doesn't, it means the screenshots and videos you made are being done through Android and that's not stuff that skyline, as an individual app, has the sort of access to determine belongs to a specific game.
