### ISSUE TITLE
Skyline emulator doesn't start in my Poco F3

### ISSUE THREAD

**Issue by Rinoka84** [skyline-emu/skyline#2224]
Hello everyone! I have a Poco F3 with Android 11 (MIUI 12.5.6.0.RKHMIXM) and tried several versions of Skyline emulator but this doesn't launch. It only shows a black screen and closes. How could Ido in this case?

**Comment by Swizzlefowl** [comment]
Hey, you should ask these type of questions in our discord server, there is no need to make an issue here for it.

**Comment by Rinoka84** [comment]
How could I do it? Excuse my ignorance about this, it's just that I'm not used to the Github site and I find it a little complex to find where the correct place is. Where is this "discord server" you mentioned? Could you provide me with the link to make it easier?

**Comment by Swizzlefowl** [comment]
https://discord.gg/XnbXNQM here.
