### ISSUE TITLE
骁龙855plus宝可梦朱紫 尼尔机械

### ISSUE THREAD

**Issue by ch123en** [skyline-emu/skyline#2237]
skylin eage44宝可梦朱紫 尼尔机械纪元没有画面 skyline eage45依然没有画面宝可梦朱紫进不了游戏 反而出现很多渲染错误问题 卡死 希望优化一下老型处理器

**Comment by ch123en** [comment]
没搜到

**Comment by Swizzlefowl** [comment]
As this is an English only forum so can you make your issues in English, I will be closing this one.
