### ISSUE TITLE
855puls

### ISSUE THREAD

**Issue by ch123en** [skyline-emu/skyline#2238]
Skyline eage44 Baokemeng Zhuzi and Neil Mechanical Age have no pictures. Skyline eage45 still has no pictures. Instead, the original picture can normally enter the dead rendering error

**Comment by Swizzlefowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.
