### ISSUE TITLE
Will the emulator be ported to PC?

### ISSUE THREAD

**Issue by AyderProgramic** [skyline-emu/skyline#224]
I know that there are yuzu and Ryujinx emulator for pc, but I want the emulator to not be designed for only one operating system!

**Comment by bylaws** [comment]
no

**Comment by AyderProgramic** [comment]
Okay!

**Comment by IvarWithoutBones** [comment]
Related issue: https://github.com/skyline-emu/skyline/issues/119

**Comment by Eyadplayz** [comment]
Might if I ask when Windows 11 Releases would the emulator work via android emulation.

**Comment by bylaws** [comment]
No, it's an interpreter
