### ISSUE TITLE
Old on-screen controls

### ISSUE THREAD

**Issue by KoremuMekuro** [skyline-emu/skyline#2240]
Please, give option to return to old style(glassy) on-screen controls.New contorls even with different levels of transparency dosen't look good to me.Noticed this new controls after 1975.

**Comment by MatheusLynar** [comment]
I liked the old ones better too. Can we have the option of which style to use?

**Comment by SohalSaab36** [comment]
you can reconfigure to what you want in setting I also changed hope it helped

**Comment by KoremuMekuro** [comment]
> you can reconfigure to what you want in setting I also changed hope it helped

How and where? Is it in edge builds?

**Comment by KoremuMekuro** [comment]
> no its also in mainline just make touchups with color and opacity you would be able to achieve it

It dosent make on-screen controls the same as they were before. I tried every possible combination.
