### ISSUE TITLE
Inverted colors Portal 2

### ISSUE THREAD

**Issue by tommy-sorce** [skyline-emu/skyline#2249]
![Screenshot_2023-03-10-23-21-27-36_fcf072b9e4efc4ce5ca3e36691a7c3c6.jpg](https://user-images.githubusercontent.com/75146584/224439904-e23bd7ce-fc32-4aee-af66-5c48ca357a6d.jpg)

**Comment by Swizzlefowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.
