### ISSUE TITLE
How can I download Skyline?

### ISSUE THREAD

**Issue by Unknownssiren** [skyline-emu/skyline#225]
Thank you for making this project for all of us! Could you please tell me how to download skyline? Thank you!

**Comment by AyderProgramic** [comment]
You go to the action on github and select the last green action

**Comment by IvarWithoutBones** [comment]
The best way to currently get a build of skyline is just compiling it yourself with Android Studio.

Alternatively, as @AyderProgramic said, you could download one off of Github Actions. Note that the latest green one is likely to be unstable, or straight up won't work. You will want to use the latest green build from the `master` branch.

**Comment by Unknownssiren** [comment]
Thank you so so much! You were both so helpful, thank you!
