### ISSUE TITLE
[cloudpunk]display problem in cloudpunk

### ISSUE THREAD

**Issue by luck71** [skyline-emu/skyline#2280]
hello could i deal this problem by modify config
![Screenshot_20230326164128](https://user-images.githubusercontent.com/86523229/227878573-27ad3e22-0c9a-42c7-b603-9eda86ce00d0.jpg)

**Comment by Swizzlefowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.

**Comment by luck71** [comment]
tanks for your reply
