### ISSUE TITLE
Remarkable Bug when booting heavy games

### ISSUE THREAD

**Issue by supposede** [skyline-emu/skyline#2282]
For example, Ninja Storm trilogy is a game that should run on the SAMSUNG GALAXY S20 FE ONE UI 5 with its SD 865+.

but it crashes when loading and applying the correct settings.

Apparently a workaround is to turn of your screen while the game loads to prevent crash as demonstrated in this video.

https://youtu.be/lb_5NUTwOec

I don't know if it's a OneUI thing or a Skyline problem.

Hope y'all can check it.😥

**Comment by Miles812** [comment]
It's happening just like that for alot of phones with 6gb ram but it seems to be the game issue because I can boot other games fine like bayonetta,re4,dragon dogma
