### ISSUE TITLE
Garbled text in the dialogue and confirm windows

### ISSUE THREAD

**Issue by Inui-senpai** [skyline-emu/skyline#2283]
Device: Poco X3 NFC
Skyline version: 0.0.3 (28.03.2023, 04:31)
Game: Nekopara Vol.3

Sometimes game outputs garbled text, but when I open Command menu, go to Save screen and return to game, the text becomes normal:
![Screenshot_2023-03-29-16-45-33-725_skyline emu](https://user-images.githubusercontent.com/29918546/228499386-b5925e27-1995-42dd-a4dd-2819b1de72fa.jpg)
![Screenshot_2023-03-29-16-45-43-338_skyline emu](https://user-images.githubusercontent.com/29918546/228499442-25aea8ec-e601-4c85-adf2-2167ea3b5e2e.jpg)

Although it doesn't work with Confirm window text:
![Screenshot_2023-03-28-18-00-52-982_skyline emu](https://user-images.githubusercontent.com/29918546/228499642-9ce924cf-b35c-4a17-bf05-11d64c2b9b04.jpg)

Tried both Docked and Portable modes, but I didn't change other settings.

**Comment by Swizzlefowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.
