### ISSUE TITLE
Access keys

### ISSUE THREAD

**Issue by Masterhatter012** [skyline-emu/skyline#229]
How do you get the keys for skyline??

**Comment by KingHackerMan** [comment]
You need to dump them from a homebrewed Nintendo Switch using [Lockpick_RCM](https://github.com/shchmue/Lockpick_RCM)

**Comment by Masterhatter012** [comment]
> You need to dump them from a homebrewed Nintendo Switch using [Lockpick_RCM](https://github.com/shchmue/Lockpick_RCM)

Okie thanks
