### ISSUE TITLE
Latest versions have serious regressions for certain devices

### ISSUE THREAD

**Issue by RaduNastase** [skyline-emu/skyline#2296]
So guys,

Sometimes "after" version 51, something changed in the gfx/driver department, because regardless of the custom driver i use (Rog Phone 3 with default Vulkan 0.502.0), games lock up or just crash, or don't even start.
On version 51 things are still good, audio is good, the emulator works very well even on defaut driver, but after that, on latest versions, it is all a mess, even with the latest Adreno drivers.

Hopefully this is just part of the wip process, and doesn't mean future updates will completely abandon slightly older devices in favour of cutting edge ones.

**Comment by Swizzlefowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.
