### ISSUE TITLE
NSO Loader

### ISSUE THREAD

**Issue by PixelyIon** [skyline-emu/skyline#23]
An NSO file is the primary executable/linkable file used by the Switch and is contained within NCA files. Which are within NSPs/XCIs. Supporting NSOs is a step towards supporting all ROM files.

**Comment by bitocard** [comment]
How is the current development?

**Comment by PixelyIon** [comment]
@bitocard Development is going very well. However, this isn't the right place to ask for development updates. We have a Discord server where most development goes on, you can join and keep up to date there: https://discord.gg/XnbXNQM.
