### ISSUE TITLE
Provide skyline in alternative package name

### ISSUE THREAD

**Issue by javithakthar** [skyline-emu/skyline#2302]
Currently skyline is not identified as "game" with some OEM game launcher applications (e.g, samsung game launcher) so we cannot use game specific optimizations (such as pause USB power delivery).

It would be helpful if skyline is provided in alternative package name like `com.miHoYo.GenshinImpact`.

**Comment by Loganbogan9** [comment]
I think this would be a great idea! Also potentially a high-performance build that uses a package name of a benchmark. I know Dolphin MMJ has an antutu package name version. This kills battery life but significantly enhances performance. I think this could be beneficial for performance, especially for devices like the S23 Ultra, which have different normal application, game, and benchmark performance profiles.

**Comment by AbandonedCart** [comment]
It has nothing to do with the package name. e63108bff1f92da833c2107b88d18d88003503ca marked the app as a game on the emulator side. Samsung's Game Launcher only recognizes apps that are hosted on Google Play. You can, however, manually add it to the list.

**Comment by javithakthar** [comment]
No it doesn't work if manually add the game. That's why raising this issue.

**Comment by AbandonedCart** [comment]
https://www.samsung.com/hk_en/support/apps-services/how-to-delete-and-add-apps-in-the-game-launcher-app/

**Comment by javithakthar** [comment]
Please try it once yourself before copy pasting stuffs from internet. The launcher will technically allows to add any apps to game launcher. But it'll not activate game mode related features. You'll get tost notification like "skyline is not a game. So some features will not work with it".

Basically it allows you to launch an app but doesn't apply any game booster related stufs.

**Comment by AbandonedCart** [comment]
I understand you are frustrated, but the issue isn't with Skyline and isn't even with Game Launcher. What seems to have been taken as a completely random paste from the internet was actually an explanation of why the app _is not identified as "game" with some OEM game launcher applications (e.g, samsung game launcher)_ and included

<details>
  <summary>Multiple ways to contact Samsung for help</summary>

<img width="1440" alt="Screen Shot 2023-04-20 at 6 15 47 AM" src="https://user-images.githubusercontent.com/1173913/233336758-54b7194f-8a1d-48cc-8fcd-2587ead400c9.png">
</details>

https://www.samsung.com/us/support/answer/ANS00079059/

> Game Booster is a **separate app** from Game Launcher, but the two of them work together. Game Booster is a handy menu that appears when you're playing a game and provides helpful tools, so you can get the best performance and play on without interruptions.

So again, here is how to contact Samsung to get help -> https://www.samsung.com/us/support/contact/

**Comment by javithakthar** [comment]
My original request still stands valid. I've raised this issue for tracking such. This issue can be marked as closed if devs are not planning to do this any time in near future. Other emus like Citra mmj provides in alternate package names so that the system treats as benchmarking/known games and applies optimization as needed.

**Comment by AbandonedCart** [comment]
The MMJ versions of Citra, Dolphin, etc are unofficial builds by a private developer. That's why you don't see Citra or Dolphin spoofing the package names of another game, only the modified version.

**Comment by PixelyIon** [comment]
Can confirm that we don't plan to do this, official Skyline package names will be retained for the foreseeable future. We already achieve a similar effect with the "Force Maximum GPU Clocks" option that uses KGSL IOCTLs to force the GPU to maximum clocks on Adreno devices. Additionally, we plan to add support for OS level performance APIs such as Qualcomm's Performance SDK which can give us control over CPU clocks on supported devices so we can achieve complete parity with the vendor solutions while retaining proper package names.
