### ISSUE TITLE
Disable audio output doest not work

### ISSUE THREAD

**Issue by MidNightCola** [skyline-emu/skyline#2305]
As said in the title, the games still have sounds even when it's turned on

Thanks for the great work btw, we all appreciate it

Edit:sorry I made a mistake in the title 😅

**Comment by AbandonedCart** [comment]
Does disabling audio not work at all or does audio not resume when returning to the app?

**Comment by MidNightCola** [comment]
the audio still works with the option enabled, but when you pause the game ( with the pause button in the corner) and resume it then the game continues without the audio

**Comment by AbandonedCart** [comment]
That's the only issue with it, though?

**Comment by AbandonedCart** [comment]
Hopefully that means the changes I am submitting will technically fix it.
