### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by PRIESTOFGAMES** [skyline-emu/skyline#2310]
There's a black screen on the 'witch on the holy night' I tried it on eggns it worked but for some reason there's a black screen in skyline with no sound please fix it

**Comment by PRIESTOFGAMES** [comment]
Why did you close it

**Comment by PRIESTOFGAMES** [comment]
Why did you closed it

**Comment by Swizzlefowl** [comment]
This is not the right repository to report game-specific issues, go to the [Skyline games list repository](https://github.com/skyline-emu/skyline-games-list/#how-do-i-contribute) and report the issue there.
