### ISSUE TITLE
[Suggestion] Resolution changing option 1x 2x or 4x etc.

### ISSUE THREAD

**Issue by Ibrohim112** [skyline-emu/skyline#2339]
I currently noticed internal resolution of all games use is 720p aka 1280x720, so if possible, implementing other 1080p or 1440p etc. would be great as it greatly increases gameplay smoothness and quality.

**Comment by TheASVigilante** [comment]
@Ibrohim112 you can get 1080p resolution by activating docked mode (depends on game).
