### ISSUE TITLE
Bug with IOCTL

### ISSUE THREAD

**Issue by artem8086** [skyline-emu/skyline#248]
First bug in function declaration ZCullGetInfo from [ctrl_gpu.cpp](https://github.com/skyline-emu/skyline/blob/master/app/src/main/cpp/skyline/services/nvdrv/devices/nvhost/ctrl_gpu.cpp):

_line 71:_ `IOCTL_CASE_ARGS(INOUT, SIZE(0x28), MAGIC(CtrlGpuMagic), FUNC(0x2),
                        ZCullGetInfo,       ARGS(Out<ZCullInfo>))`

This function has **OUT** type not an **INOUT**.

Secon bug in sevice [INvDrvServices.cpp](https://github.com/skyline-emu/skyline/blob/master/app/src/main/cpp/skyline/services/nvdrv/INvDrvServices.cpp):

_line 62:_ `auto buf{GetMainIoctlBuffer(ioctl, request.inputBuf.at(0), request.outputBuf.at(0))};`

When you try to get data from an empty buffer, out of range exception is thrown. I try to solve this there [solve INvDrvServices.cpp](https://github.com/artem8086/skyline/blob/merge-ftx1-and-nvdrv-gpu-misc/app/src/main/cpp/skyline/services/nvdrv/INvDrvServices.cpp).

But even despite this, dead lock still occurs here [GraphicBufferProducer.cpp](https://github.com/skyline-emu/skyline/blob/master/app/src/main/cpp/skyline/services/hosbinder/GraphicBufferProducer.cpp).

I really like your project, I will be glad if it helped.

**Comment by PixelyIon** [comment]
Thanks for pointing this out, @bylaws could you check this?

**Comment by bylaws** [comment]
@artem8086 thanks for the feedback! Can you tell me what game is affected by this?

**Comment by artem8086** [comment]
@bylaws simplegfx and 2048 for example from switch homebrew. Early they worked fine.

**Comment by bylaws** [comment]
The GetMainIoctlBuffer one u can fix by using `!request.inputBuf.empty() ? request.inputBuf.at(0) : span<u8>{}`
And the output version as well, for all occurrences, rather than using a vector.
Feel free to pr this together with the other fix

**Comment by PixelyIon** [comment]
I should add, I attempted to reproduce this bug to check for the `GraphicBufferProducer` issue and I couldn't do so with `simplegfx`, none of the bugs showed up for me. It might be due to different versions of libnx utilized to build them.

**Comment by artem8086** [comment]
I did as the @bylaws wrote and still get the error [skyline.log](https://github.com/artem8086/skyline-logs/blob/master/skyline.log).

**Comment by PixelyIon** [comment]
If you're in the Discord, it'd be much more convenient to coordinate there (Send a message in `#development`), I'll be testing the `TicTacToe` homebrew that you linked in the meantime.

**Comment by PixelyIon** [comment]
A commit was made directly to `master` to fix this issue 02bcf98b8cfa2c00f7a8e2b1ede8ae96c70b0549. Thanks for the report!
