### ISSUE TITLE
Latest update implementing HW emulation

### ISSUE THREAD

**Issue by chalebmydia** [skyline-emu/skyline#270]
Not sure if it's important to note, but after this update no sound after trying to run Super Mario Odyssey and it force closes back to the home screen.

**Comment by PixelyIon** [comment]
@bylaws Seemingly cannot reproduce this, do you have a save file for any level? (You can tell depending on if SMO goes to the intro cutscene or the main menu)

**Comment by chalebmydia** [comment]
I've been able to run the game and if you click a it starts the intro cutscenes audio. Now it doesn't do anything. I'm operating on a OnePlus9Pro on Android 11 if that helps at all. Just figured I'd point it out cause I would get audio on SMO up until now.

**Comment by bylaws** [comment]
We found the issue, thanks for the help

**Comment by PixelyIon** [comment]
Just to confirm, could you configure the first controller and set the `Rumble Device` to the `Built-in Vibrator`. SMO should work once you do this.

**Comment by chalebmydia** [comment]
Just tested with the last update and audio is back again. 👍 Appreciating your guys work. Hope you guys blow EggNs out of the water.
