### ISSUE TITLE
Android tv support?

### ISSUE THREAD

**Issue by BIGD15** [skyline-emu/skyline#277]

**Comment by NotAWeeb69** [comment]
There is no way in hell any android tv is capable of running skyline. Most of these run low power 32bit socs

**Comment by PixelyIon** [comment]
What @NotAWeeb69 said is correct also as we requested before, don't use this as a way to pose features, ask the team on Discord or as an "Idea" in GitHub Discussions rather than creating an issue. Doing this any further will result in a ban from the repository.
