### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by BenjittNunu** [skyline-emu/skyline#280]
Yesssir

**Comment by xHaley** [comment]
this isnt even an issue wtf

**Comment by BenjittNunu** [comment]
Hey I'm new user I don't know how to apply anything to my phone help

**Comment by PixelyIon** [comment]
Issues should made on actionable matters that we aren't already doing or plan to do, "update" doesn't classify as such. I'm sorry but you've spammed on the repo way too much and I'll have to do a 7 day block.
