### ISSUE TITLE
Wheres DL?

### ISSUE THREAD

**Issue by SlimeyPro** [skyline-emu/skyline#292]
Where is the dl tell me

**Comment by BIGD15** [comment]
What is DL?

**Comment by NielsGx** [comment]
Where is the "pretty please" tell me

**Comment by PixelyIon** [comment]
GitHub Issues isn't the place for this, please use our Discord server for such simple queries. For the time being, you can get a build from the [Actions tab](https://github.com/skyline-emu/skyline/actions).
