### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by IProXD** [skyline-emu/skyline#297]
Im opening sonic mania then it crash how do i fix this

**Comment by gcoadour** [comment]
Thank you for reading the pinned issue. Skyline emulator does not start any commercial games with graphical currently

**Comment by proganime1200** [comment]
Uhm graphics is not yet implemented wait for announcement

**Comment by PixelyIon** [comment]
This is expected on `ftx1` builds as the pipelines are malformed at the moment due to containing incomplete data.

**Comment by IProXD** [comment]
Can i join discord
