### ISSUE TITLE
Question: Is a Skyline version for M1 Macs possible?

### ISSUE THREAD

**Issue by patrickmetz** [skyline-emu/skyline#299]
Greetings everyone,

I'm curious: 
could Skyline realistically be modified to run on M1 Macs, 
which use the ARMv8.4-A-instruction-set?

And if so: do you perhaps have any plans to do that?

Bests

**Comment by PixelyIon** [comment]
We do eventually plan to do an ARMv8 Linux version and you could likely use it with Asahi Linux but past that we'd have to deal with Metal and we have no plans of ever doing that.

**Comment by bylaws** [comment]
We would accept PRs for it though if someone wanted to add support

**Comment by patrickmetz** [comment]
> We do eventually plan to do an ARMv8 Linux version and you could likely use it with Asahi Linux but past that we'd have to deal with Metal and we have no plans of ever doing that.

I see. That's a pity. 
Thanks for clarifying that.

**Comment by patrickmetz** [comment]
> We would accept PRs for it though if someone wanted to add support

It sure would be great, if someone would do that. 

The RPCS3 team currently adds M1 support, by letting MoltenVK translate Vulkan calls to Metal. 

So perhaps that would be an appropriate strategy for Skyline, too.

**Comment by PixelyIon** [comment]
MoltenVK is inadequate for Switch emulation, a Metal backend would be required and considering Skyline is not backend agnostic whatsoever at the moment, that's a tall order. You can attempt to run it on the M1 using Android Emulator which does use MoltenVK as far as I know and it did work on some homebrew but it will likely stop working at some point after it does something that Metal can't handle.
