### ISSUE TITLE
Screen flickering on Mali GPUs

### ISSUE THREAD

**Issue by sauradipdebnath** [skyline-emu/skyline#300]
It's a previous and the present image blinking 
 Can you fix it to smooth motion

**Comment by Allatel** [comment]
Another one :)

**Comment by Infinity-Loops** [comment]
This is a Vulkan Driver problem with non Adreno GPU's

**Comment by SxDVibes19238e** [comment]
Hello @Infinity-Loops so is there any fix for non adrenal GPUs

**Comment by chiko28** [comment]
Blinking images and graphic delays on android 10, infinix hot 10, specifically.
![Screenshot_20220106-214613](https://user-images.githubusercontent.com/20987937/148392976-f6438c75-df76-4860-b4f5-2ee4f2da3c08.png)

**Comment by SxDVibes19238e** [comment]
Oh mine is Android 10 (I guess)

**Comment by PixelyIon** [comment]
This is a known issue on Mali GPUs, it'll be debugged by @lynxnb who can reproduce it on an Exynos S9. Usage of Skyline is not recommended for people with photosensitive epilepsy due to the potential for visual glitches.

**Comment by SxDVibes19238e** [comment]
Oh soo there will be a fix soon?

**Comment by sauradipdebnath** [comment]
> This is a known issue on Mali GPUs, it'll be debugged by @lynxnb who can reproduce it on an Exynos S9

**Comment by sauradipdebnath** [comment]
> Oh soo there will be a fix soon?

Yess there must be a fix

**Comment by sauradipdebnath** [comment]
On new update no graphic output is there

**Comment by chiko28** [comment]
https://user-images.githubusercontent.com/20987937/148640080-e9c1f0b8-af4d-47b2-a414-d04b7026e7e4.mp4

Flickering gone but, stays on being blackscreen even though theres sounds and can click buttons of game.

**Comment by PixelyIon** [comment]
That is on `fmt-consteval` not the `ftx1` branch, only report issues regarding graphics on the `ftx1` branch. The other one doesn't have the GPU implementation and is an entirely different branch.

**Comment by ChrisM20** [comment]
Fixed in kirin 980

**Comment by Bibiloux98** [comment]
Last update fixed the Mali issues ! Thanks guys

**Comment by chiko28** [comment]
Congrats for flickering and blacksreen fix, although the fps stays at 14-18fps even when skyline setting is using max 60fps option. Therefore the game is very slow.

**Comment by Bibiloux98** [comment]
> Congrats for flickering and blacksreen fix, although the fps stays at 14-18fps even when skyline setting is using max 60fps option. Therefore the game is very slow.

It depends on your phone, what phone do you have ? With a Pixel 6, I have constant 45fps

**Comment by chiko28** [comment]
I have android 10, infinix hot 10.

**Comment by lynxnb** [comment]
Same issue as #313 and #301, which have been fixed.

**Comment by Tiredasfunk** [comment]
7 months huh time flies by

**Comment by moises0000** [comment]
Drivers MALI ,PLEASE

**Comment by Dekuzearou** [comment]
> Drivers MALI ,PLEASE

This will never happen

**Comment by AdriFarofenix23** [comment]
Then fix Mali egg ns is best with Mali GPU fix Mali in skyline
