### ISSUE TITLE
Graphics in Kirin 980

### ISSUE THREAD

**Issue by ChrisM20** [skyline-emu/skyline#301]
Hello, this is a breakthrough for the application but without snapdragon you have graphics problems, when using normal mode the graphics are a little more stable without blinking so much, at maximum performance it is more unstable as well as sometimes the image freezes, the Music goes without problems, also when closing the game sometimes the application is usually exited.
![Videoframe_20220106_100656_com huawei himovie overseas](https://user-images.githubusercontent.com/60308449/148413038-f251a6e0-c07c-4084-be58-103d867e0fd4.jpg)

![Screenshot_20220106_100315_skyline emu](https://user-images.githubusercontent.com/60308449/148413040-4e316da5-fc4c-4fd7-ab5c-2d3a8c819f3a.jpg)

![Screenshot_20220106_094855_skyline emu](https://user-images.githubusercontent.com/60308449/148413041-f9b38958-4273-4575-98ff-a86b0f5ad3db.jpg)

**Comment by PixelyIon** [comment]
This is likely the same issue as #300, I'll keep this open just in-case a fix for that issue ends up not fixing this one.

**Comment by sauradipdebnath** [comment]
No graphic on Oppo F11 pro

**Comment by ChrisM20** [comment]
Now bug fixed

**Comment by PixelyIon** [comment]
Thanks for the report!
