### ISSUE TITLE
lost save after update

### ISSUE THREAD

**Issue by TheNewon** [skyline-emu/skyline#305]
hi can u tell where games are saved and how to back up them before updating.

**Comment by TheNewon** [comment]
Can u make saves go to skyline folder pls?

**Comment by PixelyIon** [comment]
This is not something that's exposed as a user-accessible directory at the moment, they're in `/data/data/skyline.emu/files/` but will be moved to another directory in the future with a [Document Provider](https://developer.android.com/reference/android/provider/DocumentsProvider).

**Comment by TheNewon** [comment]
so if i understand i need root for now. Thank you for answer.

**Comment by BIGD15** [comment]
You can use x-plore from play store

**Comment by gcoadour** [comment]
To extract file from data/data/skyline.emu/file you can use developpeur mode with debug apk

**Comment by sauradipdebnath** [comment]
Where is save now
