### ISSUE TITLE
No graphic output after update

### ISSUE THREAD

**Issue by sauradipdebnath** [skyline-emu/skyline#308]
Fix fast

**Comment by sauradipdebnath** [comment]
On sonic Mania

**Comment by sauradipdebnath** [comment]
Black screen after update

**Comment by sauradipdebnath** [comment]
With sound

**Comment by sauradipdebnath** [comment]
On Oppo F11 pro

**Comment by PixelyIon** [comment]
Don't spam the repository with issues like this and make 5 pointless messages when you can put it into a single one, the previous issue #300 is valid and you have no grounds to demand a faster fix. It'll be fixed when a developer gets to it, on top of that, we already have one assigned to the issue.

**Comment by chiko28** [comment]
https://user-images.githubusercontent.com/20987937/148639606-fe898a52-12c4-43de-ac8b-4912cac43d5b.mp4
Flickering gone but, stays on being blackscreen even though theres sounds and can click buttons of game.
