### ISSUE TITLE
No sound when recording screen

### ISSUE THREAD

**Issue by chiko28** [skyline-emu/skyline#309]
When i use screen recorder both builtin and 3rd party app(az screen recorder) on infinix hot 10 - android 10, wont register internal sound recording.

**Comment by PixelyIon** [comment]
Noted, reports from anyone else who can reproduce would be appreciated.

**Comment by edisionnano** [comment]
I'm on android 11, using the stock screen recorder and it has sound. It's probably your problem. Can you record other apps with device sound? 3rd party apps cannot record sound unless you are rooted

**Comment by chiko28** [comment]
Yes i could record in app sound via internal sound recorder from other games, like mobile legends. Try az screen recorder you only need android 5+ not rooted.

**Comment by bylaws** [comment]
Not a skyline issue, your phone doesn't support recording low latency audio sources
