### ISSUE TITLE
Super Mario 3D World + Browsers Fury Crash

### ISSUE THREAD

**Issue by customswitch** [skyline-emu/skyline#311]
When I start the game i come back to the skyline menu. Ist the game supported? I use the latest version. I have the Keys.

**Comment by Lamzas1234** [comment]
Currently **Only** Sonic Mania is supported.

**Comment by PixelyIon** [comment]
It isn't supported, as @Lamzas1234 said only Sonic Mania is at the moment that too not in `master` and only `ftx1`.

**Comment by customswitch** [comment]
Okay.
