### ISSUE TITLE
Android 9 (pie) Support 

### ISSUE THREAD

**Issue by Bhood23** [skyline-emu/skyline#315]
Most devices run on pie so I don't see why not

**Comment by Metinkam05** [comment]
wasn't written in 4pda:"android version higher than 10 , no 32 bit " for obvious reasons?

**Comment by PixelyIon** [comment]
We will not be supporting Android 9, you need a high-end device with a recent GPU driver to run Skyline and this is another way to enforce that while allowing us to directly use features on Android 10 without having to write a shim for older versions.
