### ISSUE TITLE
Any way to update the app without uninstalling?

### ISSUE THREAD

**Issue by ChrisM20** [skyline-emu/skyline#318]
Hello, when downloading the app I see that it cannot be updated, since it has to be uninstalled and reinstalled, it would be very good if it could be updated as yuzu or citra mmj in future updates without having to uninstall, as well as not lost game progress

**Comment by lynxnb** [comment]
We plan to drop Skyline on the Google Play Store when we will deem it ready. Until then, the only ways to get Skyline are either to compile it yourself or get it through Github Actions. Keep in mind that these are development builds and are in no way meant to be used by the general public. As a result of this, I'll be closing this issue.
