### ISSUE TITLE
All games crashes with last ftx1 build

### ISSUE THREAD

**Issue by ericsonia** [skyline-emu/skyline#321]
Tested on Asus Zenfone 5z, snapdragon 845, 6 gb ram, android 10

https://user-images.githubusercontent.com/55049420/149270917-34a2d8e0-3e6e-4586-aa50-ca53bbedf8ea.mp4

**Comment by bylaws** [comment]
Why would a video of a crash ever be useful, get a log

**Comment by ericsonia** [comment]
No logs were created during the last run

https://user-images.githubusercontent.com/55049420/149285252-17bf60ae-cd58-4734-99cd-a0a2f740916b.mp4

**Comment by JerryM33** [comment]
![Screenshot_20220113_154207](https://user-images.githubusercontent.com/97395782/149287066-d7f1a499-7199-4c08-8506-2549be2af2b2.jpg)

**Comment by ericsonia** [comment]
Thank you! With this ftx1 new build today https://github.com/skyline-emu/skyline/actions/runs/1694239307 no crash anymore on my device. Now i can close this.
