### ISSUE TITLE
Galaxy A12 runs game at perfect speed with perfect sound but no image or graphics

### ISSUE THREAD

**Issue by Andvirtualmachines1** [skyline-emu/skyline#327]
Device info
Samsung galaxy A12
Sm-A125M
Android 11
Game:sonic mania
Version:https://github.com/skyline-emu/skyline/actions/runs/1471381086
The emulatir runs fine but no graphicd

**Comment by Andvirtualmachines1** [comment]
2 inportant details
1.i have rooted device with magisk so you can try to create modules to update drivers(if you can)
2.here are logs
I926EmuMainCreateDevice: Vulkan Device:
Name: PowerVR Rogue GE8320
Type: IntegratedGpu
Vulkan Version: 1.1.131
Driver Version: 1.386.1368
Queues:
* 2xGCT--: TSB0 MIG(1x1x1) <--
Extensions:
* VK_KHR_incremental_present (v0.0.1)
* VK_GOOGLE_display_timing (v0.0.1)
* VK_KHR_sampler_mirror_clamp_to_edge (v0.0.3)
* VK_IMG_format_pvrtc (v0.0.1)
* VK_KHR_shader_draw_parameters (v0.0.1)
* VK_KHR_maintenance1 (v0.0.2)
* VK_KHR_maintenance2 (v0.0.1)
* VK_KHR_descriptor_update_template (v0.0.1)
* VK_KHR_push_descriptor (v0.0.2)
* VK_KHR_get_memory_requirements2 (v0.0.1)
* VK_KHR_swapchain (v0.0.68)
* VK_KHR_bind_memory2 (v0.0.1)
* VK_KHR_sampler_ycbcr_conversion (v0.0.14)
* VK_KHR_device_group (v0.0.4)
* VK_KHR_shader_float16_int8 (v0.0.1)
* VK_KHR_16bit_storage (v0.0.1)
* VK_KHR_8bit_storage (v0.0.1)
* VK_EXT_scalar_block_layout (v0.0.1)
* VK_KHR_dedicated_allocation (v0.0.3)
* VK_KHR_relaxed_block_layout (v0.0.1)
* VK_KHR_variable_pointers (v0.0.1)
* VK_KHR_storage_buffer_storage_class (v0.0.1)
* VK_KHR_external_memory (v0.0.1)
* VK_KHR_external_memory_fd (v0.0.1)
* VK_EXT_external_memory_dma_buf (v0.0.1)
* VK_KHR_external_semaphore (v0.0.1)
* VK_KHR_external_semaphore_fd (v0.0.1)
* VK_KHR_external_fence (v0.0.1)
* VK_KHR_external_fence_fd (v0.0.1)
* VK_KHR_multiview (v0.0.1)
* VK_KHR_maintenance3 (v0.0.1)
* VK_EXT_vertex_attribute_divisor (v0.0.3)
* VK_EXT_debug_marker (v0.0.4)
* VK_EXT_debug_report (v0.0.9)
* VK_EXT_debug_utils (v0.0.1)
* VK_KHR_draw_indirect_count (v0.0.1)
* VK_KHR_shader_float_controls (v0.0.4)
* VK_EXT_blend_operation_advanced (v0.0.2)
* VK_KHR_driver_properties (v0.0.1)
* VK_KHR_create_renderpass2 (v0.0.1)
* VK_KHR_vulkan_memory_model (v0.0.3)
* VK_ANDROID_external_memory_android_hardware_buffer (v0.0.3)
* VK_KHR_depth_stencil_resolve (v0.0.1)
* VK_EXT_conditional_rendering (v0.0.2)
* VK_EXT_host_query_reset (v0.0.1)
* VK_EXT_queue_family_foreign (v0.0.1)
* VK_EXT_buffer_device_address (v0.0.2)
* VK_EXT_separate_stencil_usage (v0.0.1)
* VK_KHR_image_format_list (v0.0.1)
* VK_EXT_index_type_uint8 (v0.0.1)
* VK_EXT_texel_buffer_alignment (v0.0.1)
* VK_EXT_pipeline_creation_feedback (v0.0.1)
Quirks:
* Supports Last Provoking Vertex: false
* Supports Logical Operations: true
* Supports Vertex Attribute Divisor: true
* Supports Vertex Attribute Zero Divisor: true
I1043EmuMainVkValidation:Device[0xB400007CB8D07800]:I0:L1951495332: Validation Information: [ VUID-NONE ] Object 0: handle = 0xb400007cb8d07800, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x745174a4 | Cannot open shader validation cache at //tmp//shader_validation_cache.bin for reading (it may not exist yet)
I1175EmuMainLaunching ROM content://com.android.externalstorage.documents/tree/primary%3ASkylineroms/document/primary%3ASkylineroms%2FSonic%20Mania%20%5B01009aa000faa000%5D%5Bv0%5D.nsp
I1299EmuMainLoadExeFs: Loaded 'rtld.nso' at 0x800000000 (.text @ 0x800001000)
I2457EmuMainLoadExeFs: Loaded 'main.nso' at 0x800007000 (.text @ 0x800008000)
I2539EmuMainLoadExeFs: Loaded 'subsdk0.nso' at 0x801390000 (.text @ 0x801391000)
I2950EmuMainLoadExeFs: Loaded 'subsdk1.nso' at 0x8013D5000 (.text @ 0x8013D6000)
I4869EmuMainLoadExeFs: Loaded 'subsdk2.nso' at 0x801580000 (.text @ 0x801582000)
I4914EmuMainLoadExeFs: Loaded 'subsdk3.nso' at 0x801CE7000 (.text @ 0x801CE8000)
I6823EmuMainLoadExeFs: Loaded 'sdk.nso' at 0x801D1A000 (.text @ 0x801D1C000)
I6972HOS-0ICommonStateGetter: Switch to mode: Docked
I41853HOS-0MainThread: desiredLanguage: en-us
E42165GPFIFOCallMethod: Called method in Maxwell 3D: 0x47 args: 0x0
E42165GPFIFOCallMethod: Called method in Maxwell 3D: 0x48 args: 0x0
E42165GPFIFOCallMethod: Called method in Maxwell 3D: 0x45 args: 0x0
E42165GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x4744351
E42165GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x708215
E42165GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x4041
E42166GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x20390021
E42166GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x41
E42166GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x41
E42166GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x41
E42166GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x41
E42166GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x4180021
E42166GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x10041
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x4041
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x841
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x1841
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x41B0021
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x40440C1
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x1041
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x47 args: 0x1
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x48 args: 0x10
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x45 args: 0x10
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x210C4212
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x819215
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x19027
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x19D0021
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0xFFFFD211
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x841
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0xFFFF5097
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x1000911
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x91
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x11
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x47 args: 0x2
E42167GPFIFOCallMethod: Called method in Maxwell 3D: 0x48 args: 0x1A
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x45 args: 0x1A
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x1230215
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x19027
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x19D0021
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0xFFFFD211
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x841
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0xFFFF5097
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x1000911
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x91
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x11
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x47 args: 0x3
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x48 args: 0x23
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x45 args: 0x23
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x34A4215
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x45210
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x11027
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x652C8071
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x34A40A1
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x841
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x91
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x11
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x47 args: 0x4
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x48 args: 0x2B
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x45 args: 0x2B
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x110071
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x7400451
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x301
E42168GPFIFOCallMethod: Called method in Maxwell 3D: 0x46 args: 0x41
E42168GPFIFOCa

**Comment by NotAWeeb69** [comment]
You are using a build from 2 months ago, one that does not have the enough of gpu done to run games. Please uninstall it and download newest ftx1 branch build (which can be found here : https://github.com/skyline-emu/skyline/actions/runs/1694239307)

**Comment by Andvirtualmachines1** [comment]
The latest build crashes when running game
This is log
https://drive.google.com/file/d/1D9YNk_jiIFuHJZENyHzp1oJ2kDIt8Vwb/view?usp=drivesdk
I read it and it says vulkan not supported
If so why the other version works with no sound 
Please see the issue
I have root with magisk so you can craft a module to patch drivers

**Comment by NotAWeeb69** [comment]
Other version would work due to lack of gpu implemented obviously. Im afraid that your phone does not meet the requirements for skyline in general. Even if youd patch the drivers the performance of helio p35 wouldnt be enough to run even sonic mania. Our current minimum is sd845 while your soc isnt even comparable to snadragon 660

**Comment by lynxnb** [comment]
What has already been said is true, your GPU (PowerVR GE8320 MP2) lacks hardware features required for switch emulation. Unfortunately, your device is very low end and won't ever be supported by Skyline.
