### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by Triggerhero3758** [skyline-emu/skyline#337]
After i download and extract the APK i tried to download the apk but they said that there was a problem parsing the package i tried to download it but it didn't work please fix this

**Comment by LalithGamer** [comment]
Ya

**Comment by AbyssDemons** [comment]
I have the same problem

**Comment by Bibiloux98** [comment]
What build are you trying to use?

**Comment by bylaws** [comment]
Your device is unsupported
