### ISSUE TITLE
High graphics games are not working 

### ISSUE THREAD

**Issue by ugfreefire1** [skyline-emu/skyline#338]
Like Pokemon let's go Pikachu
When we open it crush the game

![Screenshot_20220117_174510](https://user-images.githubusercontent.com/97873382/149767941-f062eee0-cc9b-4eaa-8b9f-4fd22d72468e.jpg)
![Screenshot_20220117_174515](https://user-images.githubusercontent.com/97873382/149767962-04b4da65-28b2-424d-ae19-6916d73f6aaa.jpg)

**Comment by NotAWeeb69** [comment]
Please do not open issues without asking in discord server first. The fact that 3d games dont work yet is normal. We got Sonic Mania working about 2 weeks ago and you shouldnt expect any 3d games anytime soon

**Comment by Justchillin100p** [comment]
That's obvious the project takes time and effort and the 3d games aren't gonna be the first thing you should expect.

**Comment by sauradipdebnath** [comment]
Refer to #372
