### ISSUE TITLE
Need optimazation

### ISSUE THREAD

**Issue by D-06** [skyline-emu/skyline#341]
Maybe now it can not be don't due to the early stage of development but hopefully in the future a lot of game can be play with better fps

**Comment by NotAWeeb69** [comment]
Please do not open issues for such things. If you want to say/ask anything do so in a discord server. Current framerate is pretty much useless. Its not an indicator of what performance you can expect anyhow

**Comment by PixelyIon** [comment]
Thanks for the issue, we didn't think of optimizing the application ourselves. We were planning to make Skyline work at 1 FPS forever but thanks to you, we might try to get that number up.
