### ISSUE TITLE
Smashing button make fps go higher (only visual)

### ISSUE THREAD

**Issue by D-06** [skyline-emu/skyline#342]

**Comment by PixelyIon** [comment]
I believe you've been warned enough in the past to use other channels such as Discord and not GitHub Issues to communicate information of this manner (Something we're aware about in 99% of cases). As a result of failing to follow this advice multiple times, I'll be banning you from the repository for a month.

**Comment by etitone83** [comment]
No need for that

Emile Titone
Email: ***@***.***
Cell: 646-549-3922
