### ISSUE TITLE
Which games are working?

### ISSUE THREAD

**Issue by PatrikPepega** [skyline-emu/skyline#343]
Hello, i want to play some games, but i don't know which games are working on skyline. Can someone tell me which games are working? Thanks

**Comment by BIGD15** [comment]
God of war 4, horizon forbidden west and anonimus prime

**Comment by julssama** [comment]
GTA:V Enhanced edition and DOOM Eternal

**Comment by BIGD15** [comment]
Crysis infinite, Minecraft 2.0 and Pokémon:nomekop

**Comment by Lamzas1234** [comment]
****Actually,**** Sonic Mania, VVVVVVVV and a few others is working. If you want to see any of games working at the moment, check out this compatibility list:

https://docs.google.com/spreadsheets/d/1oFND6f0vcQKsb8dMiVuhrwY-_Tkzf2RyEbjBM64b_eM/edit#gid=0

**Comment by PatrikPepega** [comment]
Thanks a lot

**Comment by Bibiloux98** [comment]
Please do not open GitHub issues. What's you're asking for is not an issue. Refer to the Discord server of Skyline, you'll find everything you want and even more

**Comment by Sumit1ne** [comment]
I want to play need for speed hot pursuit 🥺🥺

**Comment by Bibiloux98** [comment]
The "issue" is closed. Use Discord instead to ask for games

**Comment by lynxnb** [comment]
> I want to play need for speed hot pursuit 🥺🥺

And I want a billion dollars 🥺🥺
