### ISSUE TITLE
Cant Install app after cache backup

### ISSUE THREAD

**Issue by xt2345** [skyline-emu/skyline#344]
hi, i made a backup of the apps cache and its still asking me if i want to install the app even though i deleted the app, and now i cant install it.

**Comment by Ibrahim4210** [comment]
Yeah I have the same problem

**Comment by Lamzas1234** [comment]
You must delete the app data from the old update you're using.

**Comment by xt2345** [comment]
> You must delete the app data from the old update you're using.

but how exactly do i do that?

**Comment by xt2345** [comment]
> You must delete the app data from the old update you're using.

i dont see a way to delete the app data, ive deleted the cache partition and everything.

**Comment by xt2345** [comment]
i even tracked down the old update i was using and its still refusing to install.

**Comment by Bibiloux98** [comment]
Just reinstall the previous build you uninstalled and this time delete everything. You'll be able to install a newer build

**Comment by xt2345** [comment]
i tried to install the previous build and its not letting me

**Comment by xt2345** [comment]
![Screenshot_20220123-041614_Package installer](https://user-images.githubusercontent.com/97930353/150672048-3e055737-718f-4623-8a9e-2a5c380fdb07.jpg)

**Comment by xt2345** [comment]
![Screenshot_20220123-041625_Settings Suggestions](https://user-images.githubusercontent.com/97930353/150672057-40d4a08a-4f03-44a8-a735-32013f183de9.jpg)

**Comment by xt2345** [comment]
![Screenshot_20220123-041720_Package installer](https://user-images.githubusercontent.com/97930353/150672075-e2b47722-3e10-46e7-a650-abe3169606df.jpg)

**Comment by Bibiloux98** [comment]
Are you that you're trying to reinstall the exact same version you had? Not the last build you got?
This shouldn't ask you if you want to update the app, but only install it

**Comment by xt2345** [comment]
Yes thats what ive been doing

**Comment by xt2345** [comment]
Android asked me if i wanted to make a cache backup and i enabled it, and thats what caused the issue

**Comment by Bibiloux98** [comment]
I had the same problem and just by reinstalling the build I had uninstalled that worked

**Comment by xt2345** [comment]
![Screenshot_20220123-042420_Package installer](https://user-images.githubusercontent.com/97930353/150672301-235ec47e-9226-47d0-8a81-f5401c39bc33.jpg)
heres an example but from a different app

**Comment by lynxnb** [comment]
This is getting fixed soon, in the meantime go to android settings, go to the list of installed applications and uninstall skyline from there, no need to install an older version.

**Comment by xt2345** [comment]
![Screenshot_20220123-043022_Settings](https://user-images.githubusercontent.com/97930353/150672472-9ee7676a-6848-464a-a49d-ea106a2e0872.jpg)

**Comment by xt2345** [comment]
not showing up there

**Comment by Bibiloux98** [comment]
The app doesn't remain in the installed apps, that's why I told him to reinstall the build he just uninstalled with saving data @lynxnb

**Comment by lynxnb** [comment]
Weird, it always stayed in the installed apps list for all devices I tested. I suggest you go to our discord so we can resolve this quicker.

**Comment by xt2345** [comment]
the phone im using meets the min specs fyi; samsung note 9 (snadpragon 845).

**Comment by carlos432D8** [comment]
Download skyline

**Comment by PixelyIon** [comment]
I will be closing this issue since it's not on our end and will be resolved on other platforms.

**Comment by bylaws** [comment]
it is on our end, we need to disable the flag

**Comment by lynxnb** [comment]
It is not on our end, if OEMs do a shitty job at handling that flag it's not our fault.

**Comment by Techguy791** [comment]
@xt2345 I found that using ADB to push the app fixes this problem. See #352
