### ISSUE TITLE
Implement CreateContextRegistrar and IContextRegistrar services

### ISSUE THREAD

**Issue by MK73DS** [skyline-emu/skyline#345]
Lots of games made after HOS 11.0.0 use [this service](https://switchbrew.org/wiki/Glue_services#ectx:aw). For example:
- Metroid Dread
- Pokémon Brilliant Diamond/Shining Pearl
- Mario Party Superstars

`W976HOS-0GetService: Service has not been implemented: "ectx:aw"`

**Comment by lynxnb** [comment]
I have a staging branch which stubs this service making games that require this work. I'll make a PR soon.
