### ISSUE TITLE
confused

### ISSUE THREAD

**Issue by MRGalaxy507** [skyline-emu/skyline#348]
because there are versions that go up that the image is not seen and they run with more fps while the one that gives a low image I use the mali gpu the one that does not give an image runs at 50 fps and the one that gives an image of the sonic game runs at 9 fps for true, I use a mediatek dimensity 800u processor, could you answer or help me with my question?

**Comment by Allatel** [comment]
Graphics only in ftx1 branch, no graphics = better fps

**Comment by MrKing202981** [comment]
As @Allatel explained, Builds ok the Master branch do not display graphics but have better performance compared to ftx-1 builds, which do support graphics.
