### ISSUE TITLE
I'm really living in Niger you damn racists!

### ISSUE THREAD

**Issue by BIGD15** [skyline-emu/skyline#350]
Why do you hate my race?!?

**Comment by PixelyIon** [comment]
I apologize for banning you for something that clearly wasn't a blatantly racist comment and rather a good faith commentary, I quote "Uwuweuweuwe onetweuweuwe ugwemubwem osas" after saying "I'm Richard from Niger". 

My heart goes out to you, it's just that my hand slipped and it just does that sometime. I apologize once more.

**Comment by PixelyIon** [comment]
Oops, my hand slipped again. My deepest condolences, I really do mean it..
