### ISSUE TITLE
Cannot Reinstall App

### ISSUE THREAD

**Issue by Techguy791** [skyline-emu/skyline#352]
I think this is a duplicate, but I'm not entirely sure, so I'm going to try anyway.
Last time I went to upgrade Skyline, I ununstalled the app as per usual. I'm running Android 10, so I was prompted with the ability to keep the app data so I didn't have to re-setup the keys (which was kinda silly, because it takes literally 5 seconds to do). Now I can't reinstall the app. I tried reinstalling the same build, it didn't work. I tried using Revo Uninstaller, and it didn't detect the leftover data. Is there a tool I should use to delete the cached data? Am I missing something in the settings? Thank you for taking the time to read my issue.

**Comment by xcv1** [comment]
thanks

**Comment by Techguy791** [comment]
> 

Thanks for what?

**Comment by bolshoytoster** [comment]
@Techguy791 if you have a terminal emulator on your android could you send the output of `find / -name '*skyline*'`.

**Comment by Techguy791** [comment]
> Sure, but it will be awhile before I can.

**Comment by Techguy791** [comment]
> @Techguy791 if you have a terminal emulator on your android could you send the output of `find / -name '*skyline*'`.

It just gave me a bunch of "access denied" errors. Does this need to have root for it to work?

**Comment by bolshoytoster** [comment]
@Techguy791 you can append `2>/dev/null` to it to suppress the warnings. i.e. `find / -name '*skyline*' 2>/dev/null`

**Comment by PixelyIon** [comment]
Sorry for the late response but try looking in your app list in Settings (not in the app drawer), you'll have Skyline in there. Once you uninstall it from there, that's when it'll work. If you can't find it try reinstalling the exact same build that you installed earlier.

**Comment by Techguy791** [comment]
> Sorry for the late response but try looking in your app list in Settings (not in the app drawer), you'll have Skyline in there. Once you uninstall it from there, that's when it'll work. If you can't find it try reinstalling the exact same build that you installed earlier.

I already tried both. I tried reinstalling every build from the last 2 weeks, and none of them worked. I tried searching the app list when I first noticed the issue and...![20220205_155008.jpg](https://user-images.githubusercontent.com/69944483/152661585-2de44a22-c6f9-4c89-a5fa-34144fd50e02.jpg)

**Comment by PixelyIon** [comment]
You'll want to go manually through it as searching doesn't always work.

**Comment by Techguy791** [comment]
> You'll want to go manually through it as searching doesn't always work.

 I did that, and found nothing. I also tried re-running the find command. Nothing showed up. And yet...![Screenshot_20220205-163503_Package installer.jpg](https://user-images.githubusercontent.com/69944483/152662545-b4129993-9583-450a-b8a2-fe6d3f992c17.jpg)

**Comment by PixelyIon** [comment]
Sorry, but I'm not sure why you can't find it in the installed apps list as it should be in there. The last resort I can propose is using `adb uninstall skyline.emu` but you'll need to use ADB for that.

**Comment by Techguy791** [comment]
> Sorry, but I'm not sure why you can't find it in the installed apps list as it should be in there. The last resort I can propose is using `adb uninstall skyline.emu` but you'll need to use ADB for that.

There's one thing I haven't tried yet... I think I've still got ADB on my PC. I saw this was an ongoing issue, I think I saw someone else who couldn't reinstall after doing a cache backup. And updating in-place hasn't worked... ever.

**Comment by bolshoytoster** [comment]
@Techguy791 if you send the output of `find / -name '*skyline*' 2>/dev/null` you can see any files/directories left relating to skyline.

**Comment by Techguy791** [comment]
> @Techguy791 if you send the output of `find / -name '*skyline*' 2>/dev/null` you can see any files/directories left relating to skyline.

I did that, and it returned nothing. I tried using 2 different terminal emulators.

**Comment by Techguy791** [comment]
I wonder if it's Android's built-in package manager that's the problem... I'm gonna try pushing the latest build from ADB if Pixelyon's suggestion doesn't work.

**Comment by bolshoytoster** [comment]
@Techguy791 you could try `grep -rn skyline /` but it might take a while and will return a lot of stuff.

**Comment by Techguy791** [comment]
So, I got it fixed. Turns out pushing the latest APK from ADB worked just fine. If anyone else has this problem from now on, I suggest telling them to use ADB instead of Android's built-in package manager.
