### ISSUE TITLE
Problème d'installation 

### ISSUE THREAD

**Issue by MisterDyl** [skyline-emu/skyline#353]
Erreur survenue lors de l'analyse du package pendant l'installation

**Comment by Lamzas1234** [comment]
Quelle version Android utilisez-vous?

**Comment by Bibiloux98** [comment]
Tu essayes d'installer quelle version ? Est-ce que tu essaies de mettre à jour l'application ou d'installer pour la première fois une des versions ?

**Comment by Techguy791** [comment]
@Lamzas1234 On peut avoir Android 10 ou version ultérieure

**Comment by PixelyIon** [comment]
I'm going to assume this issue was resolved, in any case, our GitHub issues should only be in English as the moderation overhead of handling multiple languages is too much.
