### ISSUE TITLE
Incompleto producto keys

### ISSUE THREAD

**Issue by zyankali83** [skyline-emu/skyline#360]
### Discussed in https://github.com/skyline-emu/skyline/discussions/359

<div type='discussions-op-text'>

<sup>Originally posted by **Oiram6912** February  1, 2022</sup>
How can I solve this problem? the keys are installed</div>

**Comment by Allatel** [comment]
dont create an issue, ask in discord. second, dont pirate

**Comment by Bifrostfan** [comment]
Ok . Thanks for telling ,☺️☺️

**Comment by Myckaelryan043** [comment]
Baixar a versão mais recente do skyline mais quando vou abrir o sonic mania plus da som mais 
Não da video

**Comment by Myckaelryan043** [comment]
Baixei a versão mais recente do skyline mais quando vou abrir o sonic mania plus o jogo da som mais não video
