### ISSUE TITLE
It doesn't Run games yet

### ISSUE THREAD

**Issue by fransoplo** [skyline-emu/skyline#364]
I was trying with nsp and nro but doesn't run. I tried with title keys, i add homebrew NxQuake but i can run any game yet. Someone can help me?

**Comment by MrKing202981** [comment]
Skyline is still in it's infancy and as such; cannot run the vast majority of the Switch's library, homebrew included. You're more than welcome to upload a log in our discord server for us to better deduce the issue.

**Comment by fransoplo** [comment]
Oh understand, so which games can i play with Skyline?. (i tried with lego marvel to test the app). I'll search discord server!. Thank you

**Comment by Techguy791** [comment]
> Oh understand, so which games can i play with Skyline?. (i tried with lego marvel to test the app). I'll search discord server!. Thank you

Sonic Mania and Celeste are the only commercial games that work right now AFAIK, and even those run too slowly to be playable (at least Mania does, I haven't tested Celeste yet)

**Comment by NielsGx** [comment]
Sonic Mania is playable, on high-end SD phones.
TBOIR also works, really slowly, like Celeste
