### ISSUE TITLE
Praising problem while installing 

### ISSUE THREAD

**Issue by Fahad2100** [skyline-emu/skyline#368]
When ever i try to install the app there is a praising problem with pkage occur i open the unknown installer to but the error is still there

**Comment by NotAWeeb69** [comment]
Most likely due to the fact you dont have the required version of android. Skyline runs on android 10 and up

**Comment by lynxnb** [comment]
Your device isn't supported, as @NotAWeeb69 said we require Android 10 as a minimum.
