### ISSUE TITLE
GUI Translations

### ISSUE THREAD

**Issue by Ilithy** [skyline-emu/skyline#37]
[Édit]
**If you would like to participate in the translation that will be done later, please let us know here;**

**You will be contacted by the developers when the time comes.
thank you.** 

List of proposals and volunteers for translation: _(thanks for their kindness)_

@V6ser - **Italian** [IT] and _maybe_  **Brazilian Portuguese** [PT-BR]

@Kegri - **Turkish** [TR]

@Jatoxo - **German** [DE]

@Afk-82 - **Simplified Chinese** [zh-CN] and _maybe_  **Traditional Chinese**  [zh-Hant]

@FAROK000 - **Arabic** [AR] and **Japanese** [JA]

@ImCaillou - **Brazilian Portuguese** [PT-BR]

@resendex - **European Portuguese** [PT-EU]

@bugthug - **Hebrew** [HE]

@NotAWeeb69 & @Gocodeyrself & @ClearStaff _(As a backup translator)_ - **Polish** [pl-PL]

@FranklinBartholomewHill - **Finnish** [FI]

@denys767 _(Discord: Denis767#1070)_ - **Russian** [ru-RU] and **Ukrainian** [uk-UA]

@Ilithy - **French** [FR]

Hello;
Is it too early in development to start translating?
I would like to volunteer to translate the
Skyline interface into French.

~~Hoping not to disturb by posting here rather than on discord
(if so, please delete my request without hesitation)~~ 

Good day and good luck.

**Comment by Yvar192** [comment]
Hey there, translations are definitely something we want to support sooner rather than later, and we appreciate the offer. There currently isn't any system in place to easily do this, but it's somewhere we definitely want to support in the future.

**Comment by Ilithy** [comment]
Thank you, that's nice to hear,
if I may say so, [Crowdin](https://crowdin.com/) has a very handy interface (for the translators at least)
When it's on the way, I'd be willing to participate, with pleasure.

In the meantime, thank you for your work, it's a very interesting project, and very complicated.

Have a good day

**Comment by faroukabd000** [comment]
Me too i want to help for both Japanese and Arabic

**Comment by Ilithy** [comment]
Hello;
 I took the liberty of translating the XML files (files from folder /values/),
but I can't propose a pull request to add them to the /res/ folder,
can I propose them? (I can share them in any way you like.)
 Or is this a misunderstanding at the moment?

Thank you.

**Comment by PixelyIon** [comment]
Hey there,
We haven't forgotten about this issue but it's far too early to work on translations at the moment. UI development is very much in-progress and due to this the are constant additions/deletions to the list of strings. So, working on translations now leads to a lot of unnecessary work and keeping a track of constant changes. 

We also want a proper framework for translation submission, we'll likely end up using [Crowdin](https://crowdin.com/) (As you suggested) or [Transifex](https://www.transifex.com/) which'll allow for a smooth workflow for translation.

We'll be coming up for our Play Store release sometime next year, that's primarily when we'll want translations (We've got several other translators for various other languages as well). UI components will be in far less of a flux by then but at the moment we have a few major components we want to add (Exit error dialogs, game compatibility assesment, in-game emulator menu, etc) and a couple of components we want to remove which would lead to a lot of iterations for the translations and a bit of overhead managing everyone to keep their translations up-to-date.

As for your current work, I recommend keeping that around as a good bit should be retained for release still. I apologize for the late reply and I cannot state this enough but we really do appreciate your vested interest in the project and willingness to contribute :smile:

**Comment by bylaws** [comment]
Yup, especially with the current ui rework, after that is merged I'll set up a transifex probably

**Comment by PixelyIon** [comment]
We'll discuss when we want to go ahead with the translations internally and let you know

**Comment by Ilithy** [comment]
Thank you very much for this quick answer, for your kindness, and especially your clear explanations.
I was thinking of doing the refactoring during development, but, with the huge amount of work you're doing, I totally understand your reasons, and it makes perfect sense (especially with multiple translation feeds, on top of everything else);
 I'll keep that in reserve, of course.

Thanks again to both of you for everything. ♥️

**Comment by PixelyIon** [comment]
We've decided to go ahead and delay it until just before release when UI isn't in a flux. We'll set everything up and contact you after that. We're really grateful to have people like you wanting to contribute to the project and deliver the best product we can to all users 😌

**Comment by Ilithy** [comment]
It is I who am grateful, I remain at your disposal, have a good trip 😘

**Comment by Krish096** [comment]
Hey guys I really appreciate your efforts on this emulator but it's not responding to Pokemon sword game, I'm waiting to play this on android for about 5 months, you guys make me hope it's gonna work but its not working please clear that,

**Comment by PixelyIon** [comment]
@Krish096 The emulator is currently work-in-progress, games will be supported as we get to them. I request refraining from commenting on unrelated issues or opening up new issues. We'll get to everything in time.

**Comment by sevketkrmsr** [comment]
Gpu support when?

**Comment by PixelyIon** [comment]
@sevketkrmsr I request you to refrain from asking questions on unrelated issues, there are no ETAs regarding GPU support and needing to deal with people asking about it only causes development to go slower.

**Comment by V6ser** [comment]
If you don't have any other volunteers, I can translate the app to Italian (it) and Brazilian Portuguese (pt-br).
I decided to inform you here rather than creating another PR.
When you're ready, hit me up! It'll be a pleasure to contribute to this project.

**Comment by bylaws** [comment]
> If you don't have any other volunteers, I can translate the app to Italian (it) and Brazilian Portuguese (pt-br).
> I decided to inform you here rather than creating another PR.
> When you're ready, hit me up! It'll be a pleasure to contribute to this project.

Thanks for offering! We'll message those interested after we have translation support and the UI is mostly stable

**Comment by higornaitt** [comment]
Yes

Em qui, 28 de jan de 2021 05:31, Billy Laws <notifications@github.com>
escreveu:

**Comment by kegri** [comment]
Hello there, if you don't have any other Turkish volunteers, I can translate the app to Turkish language (TR) if you want.

**Comment by Jatoxo** [comment]
I'd be eager to help translate to German (de) when the time comes

**Comment by Afk-82** [comment]
If you don't have any other volunteers to choose, I can translate the app to Simplified Chinese [zh-CN] (maybe Traditional as well).
Since I am not a developer and won't check out github frequently, it may becomes a bit of problem to contact me when the time comes.

**Comment by Ilithy** [comment]
_(I'm not a developer either, I specify)_ 

Hello,
 I would like to thank you for your very kind offer, I have added you to the list.

If you want to follow the evolution, you can pin the issue and be notified by email of any new message, this can be a way,
otherwise one of the devellopers will find a more adequate solution.

Have a nice day

**Comment by davyson123** [comment]
o skyline está sem vídeo. vai demorar muito para realizar esta tarefa ?

**Comment by Afk-82** [comment]
Got it. Thanks for the tip. @Ilithy 
And... 
You should create a new issue to ask instead of off-topicing here. @davyson123

**Comment by FAROK000** [comment]
Arabic & Japanese is here too

**Comment by ImCaillou** [comment]
If you need help with translations in PT-BR, I am willing to help too! 
best regards from São Paulo-Brazil

**Comment by zeresende** [comment]
I would also love to kindly help with Portuguese-Portugal or European-Portuguese (PT-PT or PT-EU) translations for Skyline Emulator because I've always felt this was a huge lack of support language in most emulators and games.

**Comment by bugthug** [comment]
I would also like to volunteer to translate the interface to Hebrew.

Note that Hebrew, like Arabic, Japanese and others is written right-to-left, and not left-to-right like most latin languages. Please be mindful of that when implmenting right-to-left languages, and thank you for your amazing work!

**Comment by Ilithy** [comment]
@resendex Hi, thank you for your very kind offer;
may I ask: do you have a preference for the language indication? Portuguese Portugal [PT-PT] or European Portuguese [PT-EU]?

 Thank you all for your support.

**Comment by resendex** [comment]
Hi @Ilithy I think PT-EU it's better 🇵🇹
😄

**Comment by NotAWeeb69** [comment]
Id love to do the translating to Polish. Much love and thanks for your hard work

**Comment by FranklinBartholomewHill** [comment]
I can do translating to Finnish if that language has enough demand for you all to want to add it.

**Comment by Gocodeyrself** [comment]
> Id z miłością robią tłumaczenia na polskie. Dużo miłości i dzięki za ciężką pracę

Hi, If you need help with translation to PL, I am at your disposal. cheers

**Comment by Gocodeyrself** [comment]
> Id love to do the translating to Polish. Much love and thanks for your hard work

Hi, I can also help with the Polish translation. cheers

**Comment by ClearStaff** [comment]
> > Id love to do the translating to Polish. Much love and thanks for your hard work
> 
> Hi, I can also help with the Polish translation. cheers

Hi, please add me under polish translators as a backup just in case :)

**Comment by denys767** [comment]
> [Édit]
> **If you would like to participate in the translation that will be done later, please let us know here;**
> 
> **You will be contacted by the developers when the time comes. thank you.**
> 
> List of proposals and volunteers for translation: _(thanks for their kindness)_
> 
> @V6ser - **Italian** [IT] and _maybe_ **Brazilian Portuguese** [PT-BR]
> 
> @kegri - **Turkish** [TR]
> 
> @Jatoxo - **German** [DE]
> 
> @Afk-82 - **Simplified Chinese** [zh-CN] and _maybe_ **Traditional Chinese** [zh-Hant]
> 
> @FAROK000 - **Arabic** [AR] and **Japanese** [JA]
> 
> @ImCaillou - **Brazilian Portuguese** [PT-BR]
> 
> @resendex - **European Portuguese** [PT-EU]
> 
> @bugthug - **Hebrew** [HE]
> 
> @NotAWeeb69 & @Gocodeyrself - **Polish** [pl-PL]
> 
> @FranklinBartholomewHill - **Finnish** [FI]
> 
> @Ilithy - **French** [FR]
> 
> Hello;
> Is it too early in development to start translating?
> I would like to volunteer to translate the
> Skyline interface into French.
> 
> ~Hoping not to disturb by posting here rather than on discord (if so, please delete my request without hesitation)~
> 
> Good day and good luck.

Greetings, I want to participate in translation of Skyline emulator to russian and/or ukrainian

**Comment by Ilithy** [comment]
You have all been added to the future translators, let me thank you for your offers

**Comment by 9ii** [comment]
Hi.i gonna to undertake Chinese translation (both simple and traditional )

**Comment by kegri** [comment]
Developers can contact me on Discord when it is done. I'm not very active on GitHub. Kegrine.#0777

**Comment by Lazthedude** [comment]
I might be able to help out with a Spanish translation
Discord: Laz 🌈#9549

**Comment by hruban** [comment]
Hi,I can translate Skyline  emulator into tamil language

**Comment by localgirllaz** [comment]
I might be able to help out with a Spanish [ES] translation
Discord: Laz 🌈#9549

**Comment by AyderProgramic** [comment]
I may also be able to translate it into Russian [RU]

**Comment by TheOG00** [comment]
The OG is here 
French, Arabic, Japanese, Korean

**Comment by hackerstudios** [comment]
I can do Arabic [AR]

**Comment by Mathias-Boulay** [comment]
Hey there @Ilithy 
I can translate in French, I know there is already someone here but another pair of eyes cannot hurt 👍

**Comment by GEGAKE** [comment]
I would love to translate elements of the emulator into german [DE]

**Comment by sannoob** [comment]
Hello, I can translate Skyline Emulator to Korean (ko-KR).

**Comment by BillisC** [comment]
Greetings, I'm able to translate skyline to Greek (el-GR)
Discord: NitroFM#6102

**Comment by l0nkDev** [comment]
I'd like to help with a Spanish translation. I just joined the Discord server as @l0nkDev#3275 so lmk what i can do to help :)

**Comment by Nablesss** [comment]
I'd like to help with the German[de] translation.

**Comment by UnearthlyGoose** [comment]
Hi, i would like to help with Russian translate (ru-RU), my discord - UnearthlyGoose#7970

**Comment by Bibiloux98** [comment]
Hello, I can help to translate the application in French (fr). My discord : Adrien#2327

**Comment by david082321** [comment]
I can help translate Traditional Chinese(Taiwan) [zh-TW] or Traditional Chinese [zh-hant].

And maybe a little Simplified Chinese(China) [zh-CN] or Simplified Chinese [zh-hans].

ps. I can't translate Traditional Chinese(HongKong) [zh-HK].

**Comment by itwell-dev** [comment]
> 

Yo tambien puedo ayudar a traducir al español

**Comment by galiagacandia** [comment]
Yo puedo ayudar a traducir a español latinoamericano es-ES

**Comment by jatijay** [comment]
Hi, I can help translate to Indonesian/Bahasa Indonesia [id-ID].

**Comment by Brrrruh** [comment]
Hi i can be a translator for persian [fa] if you want. discord:Taziye Lion#9326

**Comment by MalseMakreel** [comment]
I could do the Dutch translate if needed?

**Comment by mateoalfaro** [comment]
I could help with Spanish translations in the future #mateoalfaro11

**Comment by Andrew162x** [comment]
I can translate to Polish (PL)

**Comment by BabanKurd** [comment]
Hello, I can translate Skyline Emulator to
Central Kurdish [ckb]
(Discord: Bn#1484)

**Comment by Machannn** [comment]
I can help with Indonesian/Bahasa Indonesia [ID]!

**Comment by Miles-Endeavour** [comment]
> [Édit] **If you would like to participate in the translation that will be done later, please let us know here;**
> 
> **You will be contacted by the developers when the time comes. thank you.**
> 
> List of proposals and volunteers for translation: _(thanks for their kindness)_
> 
> @V6ser - **Italian** [IT] and _maybe_ **Brazilian Portuguese** [PT-BR]
> 
> @kegri - **Turkish** [TR]
> 
> @Jatoxo - **German** [DE]
> 
> @Afk-82 - **Simplified Chinese** [zh-CN] and _maybe_ **Traditional Chinese** [zh-Hant]
> 
> @FAROK000 - **Arabic** [AR] and **Japanese** [JA]
> 
> @ImCaillou - **Brazilian Portuguese** [PT-BR]
> 
> @resendex - **European Portuguese** [PT-EU]
> 
> @bugthug - **Hebrew** [HE]
> 
> @NotAWeeb69 & @Gocodeyrself & @ClearStaff _(As a backup translator)_ - **Polish** [pl-PL]
> 
> @FranklinBartholomewHill - **Finnish** [FI]
> 
> @denys767 _(Discord: Denis767#1070)_ - **Russian** [ru-RU] and **Ukrainian** [uk-UA]
> 
> @Ilithy - **French** [FR]
> 
> Hello; Is it too early in development to start translating? I would like to volunteer to translate the Skyline interface into French.
> 
> ~Hoping not to disturb by posting here rather than on discord (if so, please delete my request without hesitation)~
> 
> Good day and good luck.

Hi, I could help with the Italian translation, in the future.
(Discord: Tails#7552)

**Comment by Miles-Endeavour** [comment]
Hi,
I could help with the Italian translation in the future.
Just let me know when my contribution will be needed.
(Discord: Tails#7552)

**Comment by matigodoy** [comment]
Hi! i can do Spanish (Latin-American) [es-LA]

**Comment by Jo580rn3** [comment]
Hello, I'll gladly help with the French translation if still needed.

**Comment by Ilithy** [comment]
@matigodoy, @Machannn, @BabanKurd  @Andrew162x, @jatijay, @AmrIKhudair @Sannoob3144, @hackerstudios, @bugthug, @ImCaillou :
Thanks to all of you for these kind proposals, I would like to ask those who don't mind to participate in the translation of a nice android launcher: _(the amount of elements to translate is not huge)_ [Olauncher CF](https://github.com/jooooscha/Olauncher) into your language would be (very) greatly appreciated.

Again, sorry for the inconvenience and off topic.
with kind regards

From France with love

**Comment by Machannn** [comment]
> @matigodoy, @Machannn, @BabanKurd @Andrew162x, @jatijay, @AmrIKhudair @Sannoob3144, @hackerstudios, @bugthug, @ImCaillou, @FAROK000:
> 
> Thanks to all of you for these kind proposals, I would like to ask those who don't mind to participate in the translation of a nice android launcher: _(the amount of elements to translate is not huge)_ [Olauncher CF](https://github.com/jooooscha/Olauncher) into your language would be (very) greatly appreciated.
> 
> Again, sorry for the inconvenience and off topic. with kind regards
> 
> From France with love

Oh thanks.. but what should i do first to help you with the translation? Sorry I'm new here so I don't know how to do it :) my discord tag is Machan#0295

**Comment by Ilithy** [comment]
Thank you very much for your answer, [look at this](https://github.com/jooooscha/Olauncher/issues/70) , it should answer your questions ;-)

**Comment by Y-3domo** [comment]
? Not working skyline emulator for Sony xpria Xz2 compact snap dragon 845

**Comment by Crytonics** [comment]
Hello i can translate to Hrvatski (Croatian).
Discord: Crytonics#0756
