### ISSUE TITLE
skyline

### ISSUE THREAD

**Issue by Bggggggggggg** [skyline-emu/skyline#373]

**Comment by NotAWeeb69** [comment]
Very informative. I shall notify the devs of this crucial knowledge immedietly. Thank you for your very through explanation of this unknown just discovered issue!

**Comment by PixelyIon** [comment]
Out of concern for how important this issue is to the world as a whole and my inadequacy in addressing it, I will be closing this issue. Please bring the issue up in the next UNSC session as it is more fit for discussion there.
