### ISSUE TITLE
Where is the download button

### ISSUE THREAD

**Issue by Lolbg83** [skyline-emu/skyline#374]
Please tell me

**Comment by NielsGx** [comment]
Actions tab, latest one from **ftx1** branch
download release, open the zip, open the apk in it, install it.

Needs Android 10, won't install otherwise.

**Comment by pizza-10** [comment]
Please, do not leave issue about this or why your game is not running. Use the Discord Skyline server and the downoad location is in Actions. I recommend CI #860 because it is the latest and most stable update.
