### ISSUE TITLE
Me gusta

### ISSUE THREAD

**Issue by alexiscastr** [skyline-emu/skyline#375]
Me gusta mucho

**Comment by xHaley** [comment]
SHUT THE FUCK UP

**Comment by xHaley** [comment]
WHY DID YOU MAKE THIS MF

**Comment by alexiscastr** [comment]
Mira disculpa yo solo quería descargar el emulador

**Comment by xHaley** [comment]
FUCK YOU, SPEAK ENGLISH

**Comment by PixelyIon** [comment]
Sorry, we don't accept issues that aren't in English as translation ends up adding barriers and makes it harder to moderate. As I understand it though, you said you like the project and thanks but this isn't the right forum to do it in, it is specifically for reporting issues regarding Skyline. If you want to convey your appreciation or want to keep tabs on the project, I'd recommend joining our Discord server (which is also English-only for the same reason).

Also, @xHaley was very aggressive for no reason and will be receiving a temporary ban for it. I don't think that kind of behavior is acceptable in any case. I apologize on their behalf.

**Comment by sauradipdebnath** [comment]
Please block xHaley

**Comment by PixelyIon** [comment]
@Allatel There is no need to be rude about people not knowing English, I'll be locking this issue to prevent further comments.
