### ISSUE TITLE
Android 9 Support?

### ISSUE THREAD

**Issue by Bhood23** [skyline-emu/skyline#394]
The app would not install on my phone so I tried side loading via ADB then its failed because the binaries are for Android 10 or Later so any news on that?

**Comment by lynxnb** [comment]
We will not be supporting Android 9, you need a high-end device with a recent GPU driver to run Skyline and this is another way to enforce that while allowing us to directly use features on Android 10 without having to write a shim for older versions.

_Originally posted by @PixelyIon in https://github.com/skyline-emu/skyline/issues/315#issuecomment-1009875811_
