### ISSUE TITLE
BE AWARE THAT SKYLINE SUPPORTS ON ANDROID 10

### ISSUE THREAD

**Issue by sauradipdebnath** [skyline-emu/skyline#396]
Please don't make issues about android 9 support and if you have android 9 Upgrade to Android 10+ however possible and download skyline on the new version

**Comment by ubiii** [comment]
Please tell me how to download Skyline emulator from here

**Comment by ubiii** [comment]
And yeah can i play Pokemon let's go Pikachu and eevee on this emulator

**Comment by NotAWeeb69** [comment]
No you cannot. This emulator booted its first game a month ago. Itll take a while before it matures. Please do not comment under random issues for support. Join the discord server instead

**Comment by ubiii** [comment]
Tell me how to download it

**Comment by NotAWeeb69** [comment]
And i kindly asked for you to ask in the discord server instead. Issues isnt a place for that

**Comment by sauradipdebnath** [comment]
Those who have android 9, just upgrade to Android 10 or buy a new phone

**Comment by VoidOfficial421** [comment]
Kind of excited that skyline is going on the Play Store

**Comment by ShadowBlakc** [comment]
> Those who have android 9, just upgrade to Android 10 or buy a new phone

My phone does not have to update the Android, and there is no money

**Comment by Bibiloux98** [comment]
> > Those who have android 9, just upgrade to Android 10 or buy a new phone
> 
> My phone does not have to update the Android, and there is no money

We're truly sorry for you :(

**Comment by ShadowBlakc** [comment]
They say that if you wish bad things on someone, bad things will happen to the one who wished it.


I wish Skyline ## d#### ## ### ###### #######,
¦3
Now let's see how long it will take for misfortune to arrive for me,


F### world

**Comment by sauradipdebnath** [comment]
Pokemon games still don't work

**Comment by Aztroloe** [comment]
> > Those who have android 9, just upgrade to Android 10 or buy a new phone
> 
> My phone does not have to update the Android, and there is no money

If you have a snapdragon device, then you're good to go.

**Comment by EliEron** [comment]
> > > Those who have android 9, just upgrade to Android 10 or buy a new phone
> > 
> > 
> > My phone does not have to update the Android, and there is no money
> 
> If you have a snapdragon device, then you're good to go.

That's inaccurate. Skyline requires Android 10 at a minimum, regardless of what CPU you have. So a snapdragon device stuck on Android 9 for example won't be able to run Skyline.

**Comment by Aztroloe** [comment]
> > > > Those who have android 9, just upgrade to Android 10 or buy a new phone
> > > 
> > > 
> > > My phone does not have to update the Android, and there is no money
> > 
> > If you have a snapdragon device, then you're good to go.
> 
> That's inaccurate. Skyline requires Android 10 at a minimum, regardless of what CPU you have. So a snapdragon device stuck on Android 9 for example won't be able to run Skyline.

That is not what I'm trying to imply here. I'm talking about custom ROMs.

**Comment by sauradipdebnath** [comment]
People on internet are careless. Still you closed the issue. Reopen this issue forever
