### ISSUE TITLE
Skyline 

### ISSUE THREAD

**Issue by davyson123** [skyline-emu/skyline#40]
friends hello.  friends would like to know if they will update the skyline emulator later this month.  obg 😊👍

**Comment by Jack-Rickwood** [comment]
Desculpe se você não pode me entender bem, estou usando o google translate. Acredito que este mês foi o objetivo, no entanto, quase certamente não vai acontecer. A v0.4 provavelmente será lançada no próximo mês.

**Comment by davyson123** [comment]
but the day is already set friend.

**Comment by bylaws** [comment]
We do not provide ETAs but hope v0.4 to release sometime next month.

**Comment by bylaws** [comment]
In the future please ask on the discord, the issue tracker is only for code bugs and features
