### ISSUE TITLE
Black Screen On Mobile

### ISSUE THREAD

**Issue by MKGAMES6** [skyline-emu/skyline#400]
I have a Realme C11 And The Emulator Is Just Pinch Black Please Fix The Problem,The Audio Is Working Great I Have 23-54 FPS Pre-second.

https://user-images.githubusercontent.com/100344024/155515114-dbbe7688-47e6-484a-8142-159a4f8fb15b.mp4

This is a video☝️ not tho a sounds of a real game.

**Comment by MKGAMES6** [comment]
Also I tried to play sonic mania.

**Comment by NotAWeeb69** [comment]
Yeah that will never work. Snapdragon 450 doesnt have the required vulkan extensions to run skyline and it never will. There is no workaround for that

**Comment by sauradipdebnath** [comment]
S22 ultra 1TB can overcome this
