### ISSUE TITLE
Sonic Mania Black Screen Error

### ISSUE THREAD

**Issue by MightyTheGamer** [skyline-emu/skyline#401]
So when i played sonic mania it was just a black screen audio and fps is op but not the screen can yall help me fix this i seen others play it fine what is happening pls tell me but 
can yall close this after the big answer pls bc of new comers

**Comment by Lamzas1234** [comment]
U might have a wrong bulid, check ftx1. It should work.

**Comment by MightyTheGamer** [comment]
Whats that in actions tab

**Comment by Lamzas1234** [comment]
FTX1 is the correct bulid.

**Comment by MightyTheGamer** [comment]
Ok

**Comment by MightyTheGamer** [comment]
Thank you for fixing this respect
