### ISSUE TITLE
Celeste black screen

### ISSUE THREAD

**Issue by Ollll1** [skyline-emu/skyline#404]
Hello, when I run Celeste on Skyline the audio works and the frame rate is fine however the screen is black. I'm using a S21. Is there something I'm doing wrong? I installed the ftx1.

Thank you

**Comment by NotAWeeb69** [comment]
Would you be able to tell whether your phone is the snapdragon or exynos variant?

**Comment by Ollll1** [comment]
It's the Snapdragon 888. Thank you for the fast reply.

**Comment by NotAWeeb69** [comment]
In that case, have you tested other games? This could potentialy be a driver bug if you actually use the right bug. Provide log if you could. Its the button next to settings

**Comment by Ollll1** [comment]
I haven't tried other games yet. Sorry I'm new to Skyline. I see the log button but how do I export it?

**Comment by NotAWeeb69** [comment]
If you have an option to do so, join the discord server and send it in general

**Comment by Ollll1** [comment]
Okay. Thank you for your help!
