### ISSUE TITLE
(Weh)

### ISSUE THREAD

**Issue by GEGAKE** [skyline-emu/skyline#409]
## (Weh)

![image](https://user-images.githubusercontent.com/59895096/155892035-59985e7f-e09c-451f-8db2-a095ec08817e.png)

**Comment by NotAWeeb69** [comment]
I agree. Weh indeed

**Comment by pizza-10** [comment]
Please post this in the discord server, not here.

**Comment by MrKing202981** [comment]
Please do not open unrelated/irrelevant issues here.
