### ISSUE TITLE
Emulated 

### ISSUE THREAD

**Issue by davyson123** [skyline-emu/skyline#41]
mine does not run a rom why is it?  🤔🤔🤔

**Comment by FearlessTobi** [comment]
Sorry, Skyline only works on Ios devices. Please buy the Iphone XR Pro Max.

**Comment by IvarWithoutBones** [comment]
Hi there, Skyline currently does not support commercial games. At the moment only NRO homebrew work, we have a fair few tested roms available in our discord server, in case you're interested.

**Comment by davyson123** [comment]
OK friend.  friend there was a guy there with equal with me.  tell him that God loves them amen 🙂
