### ISSUE TITLE
App not installing

### ISSUE THREAD

**Issue by Ibrahim4210** [skyline-emu/skyline#414]
I have a problem where they skyline APK doesn't download. When I try to download it, it says app not installed. I deleted the skyline APK and wanted to download the newest version but I can't. Can anyone help me.

**Comment by PixelyIon** [comment]
Seems like a similar issue as #352, refer to that issue and if it still doesn't work ask in the [Discord server](https://discord.gg/XnbXNQM) rather than using GitHub Issues.
