### ISSUE TITLE
Game is too fast

### ISSUE THREAD

**Issue by benoe77** [skyline-emu/skyline#415]
When my phone is set to 120Hz refresh rate (Samsung Galaxy S20 FE) the game (Sonic Mania) also runs at 120fps. This is too fast.

**Comment by PixelyIon** [comment]
We use a system API to throttle frame submission, it's likely that some system setting forces it to ignore that and draw at refresh rate (120Hz) regardless. There's not a lot we can do about it, the system is breaking the API contract with us and the only solution is to disable it at a system level somehow.

**Comment by benoe77** [comment]
Already created a bixby routine to change to 60hz when Skyline runs. Nice job, btw :)

**Comment by bylaws** [comment]
> We use a system API to throttle frame submission, it's likely that some system setting forces it to ignore that and draw at refresh rate (120Hz) regardless. There's not a lot we can do about it, the system is breaking the API contract with us and the only solution is to disable it at a system level somehow.


I wouldn't expect Samsung to fuck up here, are we sure?

**Comment by PixelyIon** [comment]
We are, they're ignoring the desired presentation time and presenting at refresh rates. This is a system level issue that we can't control from our end without artificially throttling which would lead to poor frame pacing as submissions would've been last minute.

**Comment by bylaws** [comment]
Can we not just change the display refresh rate to 60hz? That'll work somewhat better at least? If not we should report to smasung

**Comment by benoe77** [comment]
Skyline isn't registered in the "Game Launcher" function, "Game Booster" doesn't start when I launch Skyline. With all my other games and emulators it does. Maybe, if this game launcher recognizes Skyline as a game, it allows the needed api function. This is just a theory, I can try to investigate it further.

**Comment by PixelyIon** [comment]
We already do so by setting `preferredDisplayModeId` but it's possible that using `Surface#setFrameRate` will potentially resolve this.

**Comment by PixelyIon** [comment]
@benoe77 I have pushed a potential fix https://github.com/skyline-emu/skyline/commit/342dbc555c46172922a721f466a961c32b99bb08, you can test it out once it's done building and report back it it works. If it doesn't then the only option would be to artificially throttle which isn't going to be implemented in the near future.

**Comment by benoe77** [comment]
Seems to be working correctly with this fix. At this stage "Use Maximum Display Refresh.." settings doesn't do anything, "Disable Frame throttling" does as it says

**Comment by sauradipdebnath** [comment]
It becomes fast and crashes

**Comment by benoe77** [comment]
> Disable Frame throttling

I only experienced this crash when I enabled "Disable Frame throttling"

**Comment by PixelyIon** [comment]
@benoe77 Sounds good then, other reports indicate that the issue has been fixed too.

**Comment by sauradipdebnath** [comment]
Please add fast forward as a option

**Comment by sauradipdebnath** [comment]
Remember that the fast forward is experimental

**Comment by sauradipdebnath** [comment]
Please add fast forward as an option
