### ISSUE TITLE
Segmentation fault while compiling shaders

### ISSUE THREAD

**Issue by Mohamad2008same** [skyline-emu/skyline#416]
Plsss fix mali gpu crash

**Comment by Bibiloux98** [comment]
That'll be done at some point. Please avoid to open issues until you have an unknown issue to submit

**Comment by ChrisM20** [comment]
The last update, I have tried to run sonic mania but it takes me out of the emulation when it worked correctly

**Comment by ndemeyvan** [comment]
I also had the same problem, I have a heliog95, I was able to play celeste,
but Sonic mania and hollow knight crash when I try to play it

**Comment by DarxGamer** [comment]
I have the same problem, Sonic Mania crash and I was able to launch it a couple of days before
GPU: Mali-G76
CPU: Kirin 990
Huawei P40

**Comment by PixelyIon** [comment]
We will look into this sometime next week when one of our developers can access their Mali device.

**Comment by sauradipdebnath** [comment]
Are Devs working on that

**Comment by sauradipdebnath** [comment]
Don't forget to fix it

**Comment by sauradipdebnath** [comment]
Please fix it some time if possible

**Comment by PixelyIon** [comment]
We are working on it, we were unable to find the time to do it last week so it'll probably be done this week.

**Comment by Themailkid** [comment]
Nice thx guys

**Comment by PixelyIon** [comment]
I wanted to add an update, we did figure out what the issue is and I will work on while I'm working on an in-memory shader cache which is what I'll be working on after what I'm working on right now.

**Comment by ibmeto** [comment]
> I wanted to add an update, we did figure out what the issue is and I will fix it while I'm working on an in-memory shader cache which is what I'll be working on next.

Thanks, looking forward for the update

**Comment by Long0602** [comment]
大力支持这款模拟器，我有switch这款设备，但是我依然支持做模拟器的作者，因为我的朋友就是因为在我电脑上玩过yuzu上的马力欧奥德赛才觉得买的正版

**Comment by PixelyIon** [comment]
@Long0602 Hey there, we appreciate the kind words but this is an English-only forum as it's extremely hard to moderate when people are speaking many different languages.

**Comment by sauradipdebnath** [comment]
Everyone is asking for Mali GPU Support. So Fix it when you finish working Mario Odyssey and BOTW

**Comment by sauradipdebnath** [comment]
Now you can fix it. DON'T Try to drop Mali GPU Support

**Comment by PixelyIon** [comment]
This should potentially be fixed by e036935ac137e815efc1d8e15534c11f2af609cc, I'd recommend testing on that and reporting back if this has been fixed.

**Comment by ibmeto** [comment]
> This should potentially be fixed by [e036935](https://github.com/skyline-emu/skyline/commit/e036935ac137e815efc1d8e15534c11f2af609cc), I'd recommend testing on that and reporting back if this has been fixed.

I tested the build and it still is the same

**Comment by sauradipdebnath** [comment]
Find more commits to fix more crashes or even Mali crash

**Comment by ChrisM20** [comment]
Last update without repair yet, it kicks me out of gaming (sonic mania) on a huawei mate 20

**Comment by ibmeto** [comment]
Any updates on the mali gpu fixes?

**Comment by Meet97244** [comment]
I have crash on Pokemon Sword by going in Motostock city
