### ISSUE TITLE
Add this game to the supported list

### ISSUE THREAD

**Issue by SpacedSkyzofficial** [skyline-emu/skyline#417]
This isn't necessarily a issue. But can you please make (The Elder Scrolls V: Skyrim supported on this emulator. I would like to have the experience of the amazing skyrim rpg open world in my pocket while I'm away from my pc.

**Comment by PixelyIon** [comment]
We aren't accepting game requests at the moment but we will target PC ports at some point as there's a fair bit of interest in running those on mobile.

**Comment by SpacedSkyzofficial** [comment]
Thanks for your reply. Most people are interested in TES V Skyrim. Many
people have asked me in the description of someone's yt video. On how to
install the emulator. They said is Sonic mania available to run? I said yes
it is. But about 80% of people (98 people) asked md if skyrim works. And i
said im unsure. And i installed the nsp. And ran the game but it didn't
work. And i replied to the people that asked me "Ill ask one of the skyline
devs for their request. But since ur not doing any game reqs. I'll see what
will happen in the future - SpacedSkyz

**Comment by sauradipdebnath** [comment]
It will take long time
