### ISSUE TITLE
Skyline force closes on AYN Odin

### ISSUE THREAD

**Issue by Djbrotherson** [skyline-emu/skyline#420]
Log - https://pastebin.com/pY6N3pd0

**Comment by PixelyIon** [comment]
The log does seem to be incomplete, can you provide a more complete log? also I think this might be on you @bylaws. We'd appreciate it if you could come over to the [Discord server](https://discord.gg/XnbXNQM) as real-time communication is preferred.

**Comment by Takiiiiiiii** [comment]
[linker64.zip](https://github.com/skyline-emu/skyline/files/8202174/linker64.zip)
@bylaws as requested.

**Comment by Ninoh-FOX** [comment]
I have the same problem in odin pro.

[https://mega.nz/file/b4xD3KYY#0QDeOM1acjvOehhDIYbFmyx1XFUU4EQDtV4yMfcRjMo](url)

**Comment by Djbrotherson** [comment]
This issue seems to have been resolved bruv

**Comment by Ninoh-FOX** [comment]
> This issue seems to have been resolved bruv
> 
> https://youtu.be/u_22zAFOp0A
> 
> Seems to work after OTA update for me but idk if it was the Devs

what game, i am tested Wonder Boy III, but maybe is much game for now.

**Comment by Djbrotherson** [comment]
Sonic, Celeste, Axiom Verge and a few other games can run but not many atm so don't expect much bruv

https://docs.google.com/spreadsheets/d/1oFND6f0vcQKsb8dMiVuhrwY-_Tkzf2RyEbjBM64b_eM/edit#gid=0

**Comment by PixelyIon** [comment]
The latest commit https://github.com/skyline-emu/skyline/commit/0886e793abe727fa9fceaa41a66587d1fe96c6e8 seeming fixed issues with AYN Odin, the source of the issues was apparently that [`libadrenotools`](https://github.com/bylaws/libadrenotools/) didn't work correctly when SELinux was permissive.
