### ISSUE TITLE
Failed to import keys

### ISSUE THREAD

**Issue by leopeo-star** [skyline-emu/skyline#424]
I have dumped keys but it says failed to import keys i tried everything and there is nothing to fix this before i could do this but now it just says failed to import keys any solution for that?

**Comment by PixelyIon** [comment]
The key files you're using are corrupted, they should work as there have been no changes to that code if they worked on an older version. I'll be closing this issue as I've double checked code and can safely say that there should be no issue with key file parsing in Skyline at this point.
