### ISSUE TITLE
Android 12, App won't open

### ISSUE THREAD

**Issue by Tyl02** [skyline-emu/skyline#458]
That's crash log https://bin.kv2.dev/~62295717410e7c32e669a455

**Comment by PixelyIon** [comment]
This is an OS-specific issue where a component we require is missing, contact whoever created your ROM and ask them to add support for the `OPEN_DOCUMENT_TREE` Intent. We can't do much about this at the moment, so I'll be closing this issue.

**Comment by PixelyIon** [comment]
> Better say that the emulator only works on high-end cell phones. 
> Before they said that it would also serve in low range, F

@ShadowBlakc We've always stated fairly high requirements, a Snapdragon 845 or above running Android 10 or above. None of which even relates to the current issue since it's a SAF implementation bug in the OS and doesn't relate to how powerful the device is nor is it something in our control.
