### ISSUE TITLE
What games does it support 

### ISSUE THREAD

**Issue by SpacedSkyzofficial** [skyline-emu/skyline#469]
Does Skyline Support Gta trilogy edition? If not what games does it support?

**Comment by NotAWeeb69** [comment]
Please do not open issues to ask questions. Go to server and ask there instead. Currently skyline can play somewhat only a couple of games. Namely Sonic Mania, VVVVVV and Celeste (with fps drops)

**Comment by sauradipdebnath** [comment]
Refer to #366

**Comment by SpacedSkyzofficial** [comment]
Alright thanks
