### ISSUE TITLE
Skyline crashes on vivo v2043

### ISSUE THREAD

**Issue by sussyimpostor420** [skyline-emu/skyline#470]

**Comment by edisionnano** [comment]
You should have opened the issue if it worked.

**Comment by PixelyIon** [comment]
That just isn't a device we will ever support, it's not even remotely powerful enough to emulate the Switch.

**Comment by sussyimpostor420** [comment]
Aww man..

**Comment by sauradipdebnath** [comment]
It's trash please buy s22 ultra 1tb

**Comment by sauradipdebnath** [comment]
In S22 ultra, it will work be sure to buy SD 8 gen 1

**Comment by EliEron** [comment]
The S22 Ultra 1TB literally costs about 8 times what the vivo v2043 does...

People don't buy low end phones because they aren't aware better phones exist, they do it because they don't have enough money to buy a high end device, far less a flagship like the S22 Ultra.
