### ISSUE TITLE
Sonic Mania stays on black screen with no sound on Android 10

### ISSUE THREAD

**Issue by IWantPokemonSwordOnMyPhone** [skyline-emu/skyline#471]

**Comment by Techguy791** [comment]
Are you using an ftx1 build?

**Comment by IWantPokemonSwordOnMyPhone** [comment]
Yes, lastest one so far

**Comment by PixelyIon** [comment]
Just to be sure, you'll want to install [this APK](https://github.com/skyline-emu/skyline/suites/5626147435/artifacts/183347360) and if it still doesn't work send over a log.

**Comment by IWantPokemonSwordOnMyPhone** [comment]
Where can I get the log? Also it doesn't crash it just stays on the screen forever so not sure if I can get a log

**Comment by NotAWeeb69** [comment]
Keep the game open for like 10 seconds then. Its the button next to settings

**Comment by IWantPokemonSwordOnMyPhone** [comment]
App freezes when I attenmp to close the sonic

**Comment by Techguy791** [comment]
Something similar happened to me yesterday, I paused the game and Skyline crashed when I attempted to unpause it.

**Comment by IWantPokemonSwordOnMyPhone** [comment]
Is there any other way for me to get the log? The app freezes when I close the sonic game so I can't get the log
