### ISSUE TITLE
Skyline Emulator Not Working On Mi 11T

### ISSUE THREAD

**Issue by danussus** [skyline-emu/skyline#472]
whenever I open game (like sonic mania,and the binding of Isaac rebirth)It's just shows Black screen for a second,and the crashes in emulator homescreen!
Please fix this!

**Comment by rohithshahal** [comment]
Uploading Screenrecorder-2022-03-14-12-33-25-240.mp4…

Its crashing

**Comment by Trdracer21** [comment]
im having this same issue with newest build

**Comment by 6444514581** [comment]
Ggyu
