### ISSUE TITLE
Sonic mania framerate too high to play

### ISSUE THREAD

**Issue by ifcbayle** [skyline-emu/skyline#476]
Hello guys, how's it going?

I've just installed Skyline on my Galaxy S20 FE and, after putting the keys and sonic mania to test I found out the framerate is too high to play (around 120fps), which makes the game unplayable and I didn't find an option to lower the game FPS.
Can you help me?

**Comment by PixelyIon** [comment]
This issue seems to be the same as #415. It's an OS-level bug which we can't fix on our end, you'll have to manually lower the refresh rate or use a utility which can automatically do so for you. I'll be closing this issue as we have no other issue resolutions at the moment.

**Comment by sauradipdebnath** [comment]
Add fast forward in skyline title meta

**Comment by PixelyIon** [comment]
@sauradipdebnath That doesn't make any sense? How is that related to `title-meta` and why are you requesting a feature in an unrelated issue.

**Comment by sauradipdebnath** [comment]
Add fast forward some point in the skyline
