### ISSUE TITLE
My Issue got weirder

### ISSUE THREAD

**Issue by IWantPokemonSwordOnMyPhone** [skyline-emu/skyline#480]
Few days ago Sonic Mania freeze on black screen with no sound. With the latest skyline version it got changed. Now it starts with a black screen, shifts to blue then white with sega sound playing but no logo to be seen. Then the app crashes

**Comment by PixelyIon** [comment]
What device do you have? This does sound like a GPU bug

**Comment by IWantPokemonSwordOnMyPhone** [comment]
Samsung A9. My GPU is Adreno 512

**Comment by PixelyIon** [comment]
That should be the issue, we need an Adreno 6xx GPU at the very minimum. It's likely that a driver that old is broken or the GPU can't handle it. As this is intended behavior due to not supporting Adreno 5xx, I'll be closing this issue.
