### ISSUE TITLE
Hollow knight crash on startup

### ISSUE THREAD

**Issue by zihadttttttttttt** [skyline-emu/skyline#484]
hollow knight dosen't work

**Comment by NotAWeeb69** [comment]
Thats normal. Its a unity game which means itll likely work in a good while but not anytime soon

**Comment by PixelyIon** [comment]
Not an issue, upvote the discussion about Unity games if you want Hollow Knight to work eventually. I'll be closing this.

**Comment by sauradipdebnath** [comment]
You Ignored again

**Comment by PixelyIon** [comment]
@sauradipdebnath There is no need to reply if one has already been made.
