### ISSUE TITLE
Start flash back

### ISSUE THREAD

**Issue by ciwei2018** [skyline-emu/skyline#488]
XiaoMi9
Android 11
Can you repair it?thank you

**Comment by NotAWeeb69** [comment]
Uhm, this does not at all explain what the issue is. Could you perhaps provide a more throughout explenation or maybe a log?

**Comment by sauradipdebnath** [comment]
You have to send a log

**Comment by PixelyIon** [comment]
@sauradipdebnath I feel most of your comments on issues are pointless, they generally reiterate what has already been said.

**Comment by ciwei2018** [comment]
> Uhm, this does not at all explain what the issue is. Could you perhaps provide a more throughout explenation or maybe a log?

No log，I installed the app and clicked start to flash back，There are no problems with the previous versions

**Comment by PixelyIon** [comment]
A crash at startup, could be related to #420. Just track the status of that issue and if it is fixed and your problem isn't then report back here.

**Comment by ciwei2018** [comment]
Uploading Screenrecorder-2022-03-18-17-14-04-713.mp4…
