### ISSUE TITLE
Pokemon legends arceus does not open

### ISSUE THREAD

**Issue by antonio783** [skyline-emu/skyline#490]
Im using a s20+ and when oppen the game i get Black screen nothing happen

**Comment by NotAWeeb69** [comment]
This game is currently not supported. Please do not pointlessly open issues. Ask for help in discord server instead next time

**Comment by sauradipdebnath** [comment]
Refer to # 372

**Comment by sauradipdebnath** [comment]
#372

**Comment by PixelyIon** [comment]
If you want to request support, open a discussion in the Game Requests category. I'll be closing the issue as we don't accept game requests or reports as issues at the moment.
