### ISSUE TITLE
NSP Loader

### ISSUE THREAD

**Issue by theman480** [skyline-emu/skyline#5]
First I have to thank you for the amazing Idea.
It's not possible to add .nsp yet right? 
I have roms on the /sdcard then I tap the refresh button and nothing happens.

**Comment by Yvar192** [comment]
This is on our to-do list.

**Comment by IvarWithoutBones** [comment]
#60 implemented decrypted NSP loading, which means we are now pretty close to actually loading (encrypted) NSPs. This issue wasn't meant to be closed just yet, our bad.

**Comment by aecarvalho** [comment]
So just for clarity, NSP can be loaded but won't load for commercial games right? I tried for Pokémon Mystery Dungeon: Rescue Team DX and the thumbnail loaded perfectly but the game closed and went back to titles screen on pressing play.

**Comment by PixelyIon** [comment]
@aecarvalho That is unrelated to the implementation of the NSP loader as the games are loaded in properly, it's just that they still need components which we haven't yet worked on and by extension the games won't actually work.

**Comment by aecarvalho** [comment]
Yes I understand, excellent work so far though, the interface of the emulator is awesome
