### ISSUE TITLE
How to install on Android

### ISSUE THREAD

**Issue by KClaassen** [skyline-emu/skyline#53]
HI weird question maybe, but clicking on download latest build brings me to this project, however how can I install it onto my Android device?

Many thanks

**Comment by KClaassen** [comment]
Sorry found it at the bottom of the release page

**Comment by bylaws** [comment]
You can fetch the latest build from CI here: https://github.com/skyline-emu/skyline/suites/625439868/artifacts/4995070
I would recommend joining the discord for test ROMs and progress updates.

**Comment by PixelyIon** [comment]
Hey there, I should add that isn't the most up-to-date release. Our current system of releasing isn't optimal as they're only released after huge leaps in progress. We will later replace this with a rolling release system so the version isn't extremely old. In addition to a Google Play Store release that's always kept up-to-date.

So, till we fix that I would recommend joining our [Discord](https://discord.gg/XnbXNQM) or checking out the latest CI builds here: https://github.com/skyline-emu/skyline/actions

**Comment by KClaassen** [comment]
That’s what I call quick support, many thanks for all the info! Really appreciate it! :)

On 30 May 2020, at 13:13, ◱ PixelyIon <notifications@github.com<mailto:notifications@github.com>> wrote:

https://github.com/skyline-emu/skyline/actions

**Comment by KClaassen** [comment]
Hi, what type of ROM’s work with the app? I have installed the app and I got a rom (ops) file for Pokemon Sword, but the skyline app can’t seem to find it.
Am I missing something?

Thanks

On 30 May 2020, at 14:17, Kevin Claassen <claassenk@outlook.com<mailto:claassenk@outlook.com>> wrote:

That’s what I call quick support, many thanks for all the info! Really appreciate it! :)

On 30 May 2020, at 13:13, ◱ PixelyIon <notifications@github.com<mailto:notifications@github.com>> wrote:

https://github.com/skyline-emu/skyline/actions

**Comment by PixelyIon** [comment]
Yeah, we don't actually run commercial games at the moment only homebrew that doesn't use the GPU. We're currently working on input and after this the loaders for commercial game formats (XCI and NSP), and will focus on getting a few commercial games to work after that :)

**Comment by KClaassen** [comment]
Aah ok no worries, so at the moment there is no way for me to play this I am guessing? Also not another emulator? I tried with Yuzu before via Parallels on MAC but that wasn’t supported either

On 31 May 2020, at 17:46, ◱ PixelyIon <notifications@github.com<mailto:notifications@github.com>> wrote:



Yeah, we don't actually run commercial games at the moment only homebrew that doesn't use the GPU. We're currently working on input and after this the loaders for commercial game formats (XCI and NSP), and will focus on getting a few commercial games to work after that :)

**Comment by PixelyIon** [comment]
You could try [Ryujinx](https://ryujinx.org/) but this is somewhat out of the scope of Skyline itself, you can't on Skyline at the moment.

**Comment by Atharvabh** [comment]
> HI weird question maybe, but clicking on download latest build brings me to this project, however how can I install it onto my Android device?
> 
> Many thanks

**Comment by SD9779** [comment]
Need to allow for unknow installation then it will do then turn off allow
unknown installl to protect against unknown installation

**Comment by Anosvoldygold** [comment]
Why can't I play? I already download a rom?
