### ISSUE TITLE
OPEN SOURCE

### ISSUE THREAD

**Issue by AlstonHollingsworthWaterhouse** [skyline-emu/skyline#753]
You're doing it for free, trannies.

DELET THIS.

**Comment by AlstonHollingsworthWaterhouse** [comment]
> Sorry, our Skyline™ Emulator Developers will only see your message if it is created with an account that is not an Obvious Throwaway. Please bundle your slurs with your Full Name, Address and Credit Card Information so that our filters can properly forward it to the appropriate developer for their consideration. Thank you for your comments.

I will now transfer da data,  sir

6 Lubiri Ring Rd
Kampala
Uganda 

Albert Mugubu Moses

Pastor

**Comment by riperiperi** [comment]
Thanks for your response. Our automated system has run all the numbers, and determined you fall into the followibg category:

12 YEAR OLD

Unfortunately, this disqualifies you from communication with the Skyline™ Emulator Team. If you would like to repeat your inquiry in

6 YEARS

please do not hesitate to do so.

**Comment by AlstonHollingsworthWaterhouse** [comment]
> Thanks for your response. Our automated system has run all the numbers, and determined you fall into the following category:
> 
> 12 YEAR OLD
> 
> Unfortunately, this disqualifies you from communication with the Skyline™ Emulator Team. If you would like to repeat your inquiry in
> 
> 6 YEARS
> 
> please do not hesitate to do so.

Sir,  you do have the gay, massive gay in fact. I will now ask the demon to leave,  go away demon,  leave this innocent soul and return to tha devil. By the Lord jesus christ.

**Comment by PixelyIon** [comment]
There's more than one version of gay? Seems like you're an expert in the field of homosexuality, alas even though it hurts me to close this issue created by this "gay expert" who does exorcisms on the side apparently. I am forced to do so because it isn't related to Skyline.
