### ISSUE TITLE
How many times

### ISSUE THREAD

**Issue by AlstonHollingsworthWaterhouse** [skyline-emu/skyline#754]
Are you going to get destroyed by the CCP.

Trannies on suicide watch, while Mao makes the real emulator.

**Comment by Sovietfowl** [comment]
It seems you have an illness called not touching grass . I will pray for your swift recovery. 🙏

**Comment by AlstonHollingsworthWaterhouse** [comment]
> Are you completely nuts? Please leave and stop talking nonsense

Greetings from EggNS, haha 🏳️‍🌈🏳️‍⚧️🔫🇨🇳

**Comment by QuackingCanary** [comment]
EggNs will be soon dead. That's a piece of trash using and that's a weird way to promote this thing

**Comment by AlstonHollingsworthWaterhouse** [comment]
> EggNs will be soon dead. That's a piece of trash and that's a weird way to promote this thing

Version 3 will release soon, it's over for you.

你永远不会成为一个真正的女人。
