### ISSUE TITLE
Graphical issues (in all games, including Sonic mania)

### ISSUE THREAD

**Issue by lystt** [skyline-emu/skyline#796]
With the new versión celeste doesn't work anymore, the graphics don't show, but, its run like 50fps very estable, and crash nitro kart runs, but like celeste Is doesn't see, same case Salt and sanctuary and sonic mania. I always test any versión on my phone (poco X3 pro)

**Comment by magrinzika** [comment]
Estou tendo o mesmo problema com a nova build (poco x3 pro)

**Comment by Misaelias** [comment]
Sonic Mania showed graphics until 0886e79 (Update Adrenotools version). Later versions seems to play fine (Stats show 50-55 FPS on Moto G8 Power but black screen) Tested on Poco X3 Pro also.

**Comment by Cristobal15** [comment]
> With the new versión celeste doesn't work anymore, the graphics don't show, but, its run like 50fps very estable, and crash nitro kart runs, but like celeste Is doesn't see, same case Salt and sanctuary and sonic mania. I always test any versión on my phone (poco X3 pro)

Only "ftx1" versions display graphics.  The different emulator branches are not yet merged.
