### ISSUE TITLE
Android don't have taiko so hope this will work on skyline

### ISSUE THREAD

**Issue by ygemu** [skyline-emu/skyline#801]
Android don't have taiko so hope this will work on skyline
Also this is a 2D game

_Originally posted by @D-06 in https://github.com/skyline-emu/skyline/discussions/573_

**Comment by edisionnano** [comment]
Please don't open an issue for this

**Comment by julssama** [comment]
> Android don't have taiko so hope this will work on skyline Also this is a 2D game
> 
> _Originally posted by @D-06 in #573_

Android HAS taiko, its a part of the game called osu Lazer, go give it a try

**Comment by D-06** [comment]
I have tried but its only press the don note

**Comment by PixelyIon** [comment]
This shouldn't be an issue? I don't see why it was made one
