### ISSUE TITLE
Latest build CI #939: All games black screen issue on Samsung Note 9 (Exynos Variant)

### ISSUE THREAD

**Issue by ibmeto** [skyline-emu/skyline#807]
Great progress so far to the devs, Congrats!

Just waiting for the issues to be fixed,

Thanks

**Comment by PetteriLah** [comment]
Only ftx1 builds works

**Comment by ibmeto** [comment]
Tried ftx1 CI #931 build. Still black screen even sonic mania. An older build works better

**Comment by Lamzas1234** [comment]
You might have a Mali GPU, a fix is coming soon. 

> Tried ftx1 CI #931 build. Still black screen even sonic mania. An older build works better

**Comment by ibmeto** [comment]
> You might have a Mali GPU, a fix is coming soon.
> Great to know thanks

**Comment by PixelyIon** [comment]
You can just track #416, I'll be closing this issue.
