### ISSUE TITLE
Not installing On Fire Tablet (Fire HD 10 11 Generation) Or Less (Dont Ask Why Im on fire tablet)

### ISSUE THREAD

**Issue by Joshuaj970** [skyline-emu/skyline#830]
So Evertime When I install it this happens
![Screenshot_20220323-182245](https://user-images.githubusercontent.com/84782130/159806286-20d21908-57fe-4424-9757-fc23be56dd34.png)

Yea I Don't Know Why That Happens but I know

**Comment by NEWLuigi64** [comment]
First of all, Are you on Android 10? And if so, explain your problem.

**Comment by MrKing202981** [comment]
Amazon HD Fire tablets run on 32-bit variants of Android, and are therefore unsupported by Skyline. It's hardware is far too under-powered to emulate the switch even if it was running a 64-bit OS.

**Comment by Joshuaj970** [comment]
> 

Oh
