### ISSUE TITLE
RomFS Implementation

### ISSUE THREAD

**Issue by PixelyIon** [skyline-emu/skyline#84]
A lot of games pack a filesystem inside their ROM file that they access during execution, this is done so that they can stream in data from persistent storage in an intuitive manner. We need to decode this data and complete the interface to provide RomFS access to the underlying applications.

**Comment by bylaws** [comment]
The game isn't actually exposed to the romfs as a filesystem, just as a storage region. The only reason we implement parsing is for reading icons etc, and eventually layeredFS.
