### ISSUE TITLE
Bastion freezes in game loading

### ISSUE THREAD

**Issue by Hyujbg** [skyline-emu/skyline#859]
Heres what i mean
![Screenshot_20220331_115113](https://user-images.githubusercontent.com/98869140/160989916-7cc03ea6-f91d-48c4-bd64-3e76fe0a6ae7.jpg)

**Comment by ezequielbsb25** [comment]
That's weird. Bastion is working with no problem on my Poco X3 Pro on average of 20fps a

**Comment by Hyujbg** [comment]
It opens but when i click on normal or no sweat mode,it freezes

**Comment by PixelyIon** [comment]
There's a chance this is caused by #416 but I'll leave this issue open until it's been proven. Check if this issue still exists after that one has been fixed.

**Comment by Gvenkzi** [comment]
Yeah, same here, before the game play, always black screen for no reason

**Comment by haradox0** [comment]
@PixelyIon 
-sd860 /runs good
-sd660 /slow without any crash
so it's mali 100%

**Comment by ericsonia** [comment]
Sd 845, gpu driver v415 also freezes

**Comment by ezequielbsb25** [comment]
Yeah, with the lastest update I'm getting black screen

**Comment by ezequielbsb25** [comment]
> It opens but when i click on normal or no sweat mode,it freezes

Yeah, with the lastest update I'm getting black screen

**Comment by Bububgithub** [comment]
Bastion bug graphic in my sd660., With black screen bin a part of area
