### ISSUE TITLE
Celeste freezes before even getting to menu

### ISSUE THREAD

**Issue by AjaxS21** [skyline-emu/skyline#875]
![Screenshot_2022-04-01-19-15-47-50_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/101979421/161320470-4166fa67-75b9-49d9-9ede-d81e10b6f958.jpg)

**Comment by Woganog** [comment]
This happens to me too. Your GPU drivers need updating, someone else can tell you how I have low IQ

**Comment by AjaxS21** [comment]
> This happens to me too. Your GPU drivers need updating, someone else can tell you how I have low IQ

I don't know that much about emulation. How do I update my drivers?

**Comment by astronomy2021** [comment]
> > This happens to me too. Your GPU drivers need updating, someone else can tell you how I have low IQ
> 
> I don't know that much about emulation. How do I update my drivers?

Hi, you can join discord of Skyline or Adreno telegram group for help with updating GPU drivers on Snapdragon SOC device.
I can help personally.
https://discord.gg/XnbXNQM
 https://t.me/adreno_konabess

**Comment by AjaxS21** [comment]
> > > This happens to me too. Your GPU drivers need updating, someone else can tell you how I have low IQ
> > 
> > 
> > I don't know that much about emulation. How do I update my driv

Can you tell me

> > > This happens to me too. Your GPU drivers need updating, someone else can tell you how I have low IQ
> > 
> > 
> > I don't know that much about emulation. How do I update my drivers?
> 
> Hi, you can join discord of Skyline or Adreno telegram group for help with updating GPU drivers on Snapdragon SOC device. I can help personally. https://discord.gg/XnbXNQM https://t.me/adreno_konabess

Could you perhaps tell me your username on discord so I can message you?

**Comment by AjaxS21** [comment]
> As far as we know, crashes/freezes are likely due to #416. Not due to outdated drivers but it could be the case.

Forgive me if I'm wrong but isn't that thread about the Mali gpu? I have an Adreno.

**Comment by PixelyIon** [comment]
Not necessarily, that bug affects both vendors. It just has a higher incidence rate on Mali. I'll be closing this issue and superseding it with #416 for the time being, if that doesn't fix it just drop a comment here and I'll re-open and investigate the issue.
