### ISSUE TITLE
not installing

### ISSUE THREAD

**Issue by vicius13** [skyline-emu/skyline#876]
Hello, I'm a Brazilian and I own a Galaxy Note 8, I know this emulator through Brazilian reviews, and when I go to install the application the error "There was a problem parsing the package". 
I would like to know if the app works with the Galaxy Note 8, Or also, from which version of Android the application works.

**Comment by JustAChicken97** [comment]
i think your phone can't run skyline, because it's exynos probably, and because of old Android version
