### ISSUE TITLE
Galaxy note 9 exynos

### ISSUE THREAD

**Issue by Jannatuul** [skyline-emu/skyline#883]
Not a single game is working on my galaxy note 9 exynos 
Most of the game crashed some of them show only sound 
When will it fixed for note 9 exynos gpu

**Comment by Gvenkzi** [comment]
Last version is broken, Try to Install the previous one

**Comment by PixelyIon** [comment]
The Note 9 is extremely old, don't expect it to run a lot especially the Exynos version. A lot of devices have crashes due to #416, track that issue for a resolution of crashes if they aren't fixed by installing the last CI build.

**Comment by Techguy791** [comment]
> The Note 9 is extremely old
Is 4 years really _extremely_ old? The Snapdragon version, which is what I have, runs Sonic Mania at fullspeed.

**Comment by MrKing202981** [comment]
> > The Note 9 is extremely old 
> >
> Is 4 years really _extremely_ old? The Snapdragon version, which is what I have, runs Sonic Mania at fullspeed.
> 
> 

Given how quickly mobile hardware advances, A Galaxy Note 9 is quite out of date. Most devices can run Sonic Mania as it doesn't require as much GPU Infrastructure or Power compared to other games.
