### ISSUE TITLE
GPU GPFIFO Implementation

### ISSUE THREAD

**Issue by PixelyIon** [skyline-emu/skyline#89]
GPFIFO is a FIFO queue of GPFIFO entries which point to a pushbuffer that are a list of commands and inline data that is used to dispatch data to a specific GPU Engine. GPFIFO also has synchronization in the form of syncpoints to ensure proper ordering of push buffers.

**Comment by bylaws** [comment]
GPFIFO is a FIFO queue of GPFIFO entries which point to a pushbuffer.
