### ISSUE TITLE
Gpu malli.

### ISSUE THREAD

**Issue by davyson123** [skyline-emu/skyline#897]
Quando eu abro o jogo Sonic fecha sozinho. Mark tem como vc arrumar o driver gráficos na programação da gpu malli ? Obg irmão.

**Comment by GENROGAMER** [comment]
Troque seu aparelho e melhor que refazer qualquer tipo de programação

Em seg, 4 de abr de 2022 00:55, davyson123 ***@***.***>
escreveu:

**Comment by sauradipdebnath** [comment]
Try to fix Mali GPU crash

**Comment by QuackingCanary** [comment]
Please be patient, Mali fix is on his way and will come soon enough
