### ISSUE TITLE
External saved data

### ISSUE THREAD

**Issue by Jons-1** [skyline-emu/skyline#901]
Place the saved data folder,, in an external folder,, or in android data,. (as you know the skyline emu emulates several games, however when you want to update the app, you must restart the progress),.

**Comment by chostdz** [comment]
That's really good idea

**Comment by Lancelito** [comment]
True

**Comment by MuhSlam** [comment]
IIRC Dev planned to store/move save data to.. 
Android/data/  .. so that no root phone can have access it

**Comment by PixelyIon** [comment]
Yes, we already plan doing this and will do so at some point. I'll leave this issue open until then.

**Comment by lynxnb** [comment]
Skyline data folder is now located at `/sdcard/Android/data/emu.skyline/`. I'll close the issue now.
