### ISSUE TITLE
渎神运行错误

### ISSUE THREAD

**Issue by Chengzhi77** [skyline-emu/skyline#914]
游戏渎神一点进去就闪退，并且许多2d游戏也无法运行

**Comment by kolyapichkur** [comment]
English only please. Here is compatibility list, it can run only 2d or simple 3d games.
https://docs.google.com/spreadsheets/d/1oFND6f0vcQKsb8dMiVuhrwY-_Tkzf2RyEbjBM64b_eM/edit#gid=990708478

**Comment by Chengzhi77** [comment]
I think most 2D games should be optimized to make them playable. Big 2D games like Blasphemy can be optimized first. If the production team is short of funds, my friends and I can donate $15 to your research and development work. Come on, you guys are really good!

**Comment by Chengzhi77** [comment]
Calling the performance of the gpu more should be able to run the game more smoothly.

**Comment by Chengzhi77** [comment]
Hello, respected production teamI would like to ask when Skylien can play Pokemon. My friends and I are concerned about it. If the progress is slow due to the cost problem, my friends and I agree that we can accept the payment within 15 DOLLARS.Thank you very much for your efforts and wish you all the best.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月06日 14:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [skyline-emu/skyline] 渎神运行错误 (Issue #914) |

English only please. Here is compatibility list, it can run only 2d or simple 3d games.
https://docs.google.com/spreadsheets/d/1oFND6f0vcQKsb8dMiVuhrwY-_Tkzf2RyEbjBM64b_eM/edit#gid=990708478
