### ISSUE TITLE
wrong orientation and language in little busters converted edition

### ISSUE THREAD

**Issue by pokegamer5547** [skyline-emu/skyline#917]
The game doesnt get past title screen as of now but it boots up and displays title screen in wrong language and orientation even tho i had default language as american english and british english. 
![Screenshot_20220406-144143_Skyline](https://user-images.githubusercontent.com/65234485/161940987-d3d81c64-4f91-4433-bd1d-5fe09cf38133.png)

**Comment by PixelyIon** [comment]
Sorry but you'll have to just stick to upvoting a game request for this rather than directly reporting issues. We'll get to a game and attempt to fix issues with it if it is high enough on the list.
