### ISSUE TITLE
Save Game External Not Function for latest version #981 , Please Fix

### ISSUE THREAD

**Issue by TeamSOTD** [skyline-emu/skyline#918]
always repeat the game from the beginning
even though the save game results have been backed up

**Comment by MuhSlam** [comment]
Save game backup are working fine for me , maybe you put into the wrong folder or something 

Backup save ( id folder ) f. e Celeste
![IMG_20220406_182023](https://user-images.githubusercontent.com/97679544/161963644-eb924284-df10-4831-a843-cd84bdfe7872.jpg)
