### ISSUE TITLE
An error has occurred: com.android.externalstorage has no access to...

### ISSUE THREAD

**Issue by rushcancercartwheel** [skyline-emu/skyline#923]
Device: realme GT 2 (Snapdragon 888 5G) - https://m.gsmarena.com/realme_gt2-11307.php
System version: Android 12, realme UI 3.0
App version: https://github.com/skyline-emu/skyline/commit/882b9393356572611c0951c49f85e07bce520a6c

**Description:**
Skyline app has no access.

**Steps to reproduce:**
1. Select the folder with the Nintendo Switch game and key. Settings -> Search Location

2. In this case it shows this path: content://com.android.externalstorage.documents/tree/primary:game

3. Then the error message appears: An error has occurred: com.android.externalstorage has no access to...

**Comment by PixelyIon** [comment]
It would be faster to resolve this if you can bring it up in the [Discord server](https://discord.gg/XnbXNQM) but it does seem like a SAF implementation issue with your ROM.

**Comment by rushcancercartwheel** [comment]
@PixelyIon 

![Screenshot_2022-04-07-16-09-44-44_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/103147182/162219040-a7daf5c5-23cc-439e-a7bf-528e70f7df28.jpg)



Here the logcat
[logcat.txt](https://github.com/skyline-emu/skyline/files/8443628/logcat.txt)

**Comment by PixelyIon** [comment]
You're doing something which is causing SF to trip, are you selecting the Downloads folder or another protected directory? This won't work. There's very little we can do on our end to resolve this, it's an issue with the OEM's SAF implementation.

**Comment by PixelyIon** [comment]
Right, that part isn't broken but something else is on the OEM's side. It should work as we're not doing anything that violates the guarantees provided by Android APIs and does work on other devices.
