### ISSUE TITLE
Sonic Mania FC in GPU Mali

### ISSUE THREAD

**Issue by FrenklintonManalu** [skyline-emu/skyline#935]
Please fix FC Sonic Mania,i want to play because the game is so great,but i'm so disappointed because i cant play Sonic Mania smoothly because FC,please fix this one

**Comment by FrenklintonManalu** [comment]
> What is "FC"? Do you mean FPS?

No,FC is force close

**Comment by PixelyIon** [comment]
What device are you using, what are the specs?

**Comment by FrenklintonManalu** [comment]
> What device are you using, what are the specs?

My Spec is Infinix Hot 10s

**Comment by PixelyIon** [comment]
Not a device in our targeted support range but send over a log, it's the button in the upper-right corner right besides settings.

**Comment by sauradipdebnath** [comment]
#372 because of being in pre alpha. It has poor compatibility try to fix it

**Comment by FrenklintonManalu** [comment]
> #372 because of being in pre alpha. It has poor compatibility try to fix it

Yes is true,but i can play Sonic Mania in previous version and new version is force close please fix it

**Comment by sauradipdebnath** [comment]
Will sleep loop rather than abort fix it
