### ISSUE TITLE
How to download direct app 

### ISSUE THREAD

**Issue by VISHAWANATH953** [skyline-emu/skyline#94]
We want app

**Comment by alexbgameson** [comment]
Skyline is very far from being ready to use. They wont release direct downloads until its feature complete. If you want to try it you can compile it yourself with android studio.

**Comment by PixelyIon** [comment]
Hey there, the application isn't useful for anyone who isn't a developer at the moment due to not running commercial games. So, we won't offer public releases till we decide we're at a point where it's ready for that. (also thanks @alexbgameson 😄)

**Comment by faroukabd000** [comment]
Especially now a damned Chinese company (gamesir)steal the yuzu souce code to use it with their controllers

**Comment by NielsGx** [comment]
Why is there always somebody talking about this shitty app all the time ?
