### ISSUE TITLE
GPU MALLI 

### ISSUE THREAD

**Issue by davyson123** [skyline-emu/skyline#942]
Gpu malli crashes (freezes) cupirred.  I would like to know if there is a way to fix the gpu malli Future. Obg

**Comment by davyson123** [comment]
![Screenshot_2022-04-09-12-53-26-159_skyline emu](https://user-images.githubusercontent.com/51521229/162581585-9a57b785-69dc-418a-a104-c1a5dd10ba98.jpg)

**Comment by VladimirMihailov** [comment]
Cuphead works for me, when I turn on respect display cutout,but without sound (poco x3 pro)

**Comment by davyson123** [comment]
O meu xiaomi e uma héliog85 sabe mais ele tem uma gpu de 2021 sendo que também a velocidade e de @1000 mhz

**Comment by MrKing202981** [comment]
This is a known issue with Mali GPUs and will be resolved in the future.

**Comment by davyson123** [comment]
Tanks. 🙂

**Comment by davyson123** [comment]
thanks🙂

**Comment by sauradipdebnath** [comment]
> This is a known issue with Mali GPUs and will be resolved in the future.

I hope this should be fixed. Thanks
