### ISSUE TITLE
broken level selection model in Celeste

### ISSUE THREAD

**Issue by frans4080** [skyline-emu/skyline#943]
heres proof:
![Screenshot_20220409-221529](https://user-images.githubusercontent.com/85518684/162588700-9135578b-2b42-4f85-8f10-5b50e617e1c6.jpg)
![Screenshot_20220409-221656](https://user-images.githubusercontent.com/85518684/162588701-accd608a-8ad1-435b-80f4-285d6cfc287e.jpg)
p.s: only the front of the model is like this the back of the model is fine.

**Comment by Aztroloe** [comment]
What build are you using?

**Comment by Dr0bac** [comment]
For me is like that also. Oneplus 6, snapdragon 845, latest ftx1 build

**Comment by frans4080** [comment]
> What build are you using?

the latest one.

**Comment by Dr0bac** [comment]
I was on android 10 (snapdragon 845, drivers v408) and was seeing same red mountain. After upgrading to android 11, drivers v502, mountain looks ok now.
