### ISSUE TITLE
[BUG] Skyline is using lowest GPU clock

### ISSUE THREAD

**Issue by josesilveiraa** [skyline-emu/skyline#947]
Title says it all. It doesn't use a frequency different from the lowest

**Comment by davyson123** [comment]
![Screenshot_2022-04-09-12-53-26-159_skyline emu](https://user-images.githubusercontent.com/51521229/162595990-c7fce8eb-35fc-496c-a437-92333239b3ca.jpg)

Poxa o corred não abre por aqui

**Comment by bylaws** [comment]
Yeah that's cause we don't put any load on gpu atm, we're entirely CPU bottlenexked die to missing shader cache

**Comment by Eliasbeyg** [comment]
Acho que falta compatibilidade com os processadores, o emulador não usa todo o poder de processamento dos celulares
