### ISSUE TITLE
Descargar 

### ISSUE THREAD

**Issue by NickoGH** [skyline-emu/skyline#949]
Dónde puedo descargar la versión más reciente ?

**Comment by bolshoytoster** [comment]
@NickoGH Tendrás que construirlo tú mismo.

**Comment by PixelyIon** [comment]
You can get it off [our CI in the Actions tab](https://github.com/skyline-emu/skyline/actions). I should mention that GitHub Issues are not for support requests and are English-only due to the issues with moderating multiple languages.
