### ISSUE TITLE
Mo ganes work

### ISSUE THREAD

**Issue by Jojojojojoq9q99q919** [skyline-emu/skyline#950]
Just a black screen please help me please sit and make it like egg okay yes

**Comment by Jojojojojoq9q99q919** [comment]
Brother

**Comment by Jojojojojoq9q99q919** [comment]
Mario 3d willint boot

**Comment by Woganog** [comment]
It doesn't work yet give the devs some time

**Comment by Jojojojojoq9q99q919** [comment]
Brother you make me wooden thank you

**Comment by MrKing202981** [comment]
Please do not open irrelevant issues, game compatibility is being worked on. In the mean time please be patient.

**Comment by Jojojojojoq9q99q919** [comment]
Would you rather have unlimited games but no more bacon or unlimited games but no more games

**Comment by Jojojojojoq9q99q919** [comment]
Pokemon kegs go ?

**Comment by Jojojojojoq9q99q919** [comment]
상어 가족)
아기 상어 뚜루루 뚜루
귀여운 뚜루루 뚜루
바닷속 뚜루루 뚜루
아기 상어!
엄마 상어 뚜루루 뚜루
어여쁜 뚜루루 뚜루
바닷속 뚜루루 뚜루
엄마 상어!
아빠 상어 뚜루루 뚜루
힘이 센 뚜루루 뚜루
바닷속 뚜루루 뚜루
아빠 상어!
할머니 상어 (뚜루루 뚜루)
자상한 (뚜루루 뚜루)
바닷속 뚜루루 뚜루
할머니 상어!
할아버지 상어 (뚜루루 뚜루)
멋있는 (뚜루루 뚜루)
바닷속 뚜루루 뚜루
할아버지 상어!
우리는 뚜루루 뚜루
바다의 뚜루루 뚜루
사냥꾼 뚜루루 뚜루
상어 가족!
상어다 뚜루루 뚜루
도망쳐 뚜루루 뚜루
도망쳐 뚜루루 뚜루
숨자! 으악!
살았다 뚜루루 뚜루
살았다 뚜루루 뚜루
오늘도 뚜루루 뚜루
살았다 휴!
신난다 (뚜루루 뚜루)
신난다 (뚜루루 뚜루)
춤을 춰 뚜루루 뚜루

**Comment by Jojojojojoq9q99q919** [comment]
Helloooo I need help on my pokemon let's go

**Comment by Woganog** [comment]
Just wait it'll work soon
