### ISSUE TITLE
no sound in Steins;Gate 0

### ISSUE THREAD

**Issue by frans4080** [skyline-emu/skyline#960]
heres proof:

https://user-images.githubusercontent.com/85518684/162623055-54223969-b9f2-41c4-b9a6-3fead43244a2.mp4

the voices for the characters also have no sound.

**Comment by PixelyIon** [comment]
This is likely due to the lack of a proper `audren` implementation which is going to take a while, you can share a log here so that we can more or less confirm it.

**Comment by frans4080** [comment]
heres the log: https://mega.nz/file/AIhW3SqZ
code for oppening the log: 0D5-o2m7qR2XULH-ZzNT0RrKuvibU3fIflbAyMpRrXg

**Comment by frans4080** [comment]
is it a audren issue?

**Comment by ArbestRi** [comment]
You can check my Skyline compatibility list here: https://docs.google.com/spreadsheets/d/e/2PACX-1vRY2RyAZPV2DdN242ElcotA3jTFO3twuvRO1QhORZpDmJ-aUo3hr4T-k1WLEz8GDHcFja-CnXddNbv4/pubhtml
Since I don't have an Android device, I got info from YouTube and this website.

**Comment by PixelyIon** [comment]
@frans4080 It is according to `^^W^]1836^]HOS-0^]HandleRequest: Cannot find function in service 'audio::IAudioDevice': 0xC (12)`. @bylaws will work on an implementation at some point in the future. However, I noticed that there is the name of a piracy site at the end of your ROM's filename, we have a strict anti-piracy policy as a result I'll be banning you from the repository.
