### ISSUE TITLE
Skyline não instala no Android 11 no Redmi Note 8 Pro

### ISSUE THREAD

**Issue by Vaniatin** [skyline-emu/skyline#965]
Tentei fazer o download do aplicativo,mas sempre mostrava erro ao analizar o pacote.

**Comment by ezequielbsb25** [comment]
You mean, skyline can't install on Redmi note 8 Pro Android 11.

**Comment by PixelyIon** [comment]
Refer to https://github.com/skyline-emu/skyline/issues/288, this is not an issue on our end and I will be closing the issue as a result of this.

**Comment by Vaniatin** [comment]
Yes
Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
