### ISSUE TITLE
Skyline emulator

### ISSUE THREAD

**Issue by kayjballer** [skyline-emu/skyline#972]
Salut je suis youtubeur et j'aimerais réaliser avec skyline pour tester les jeux switch ainsi aider à améliorer skyline merci de. Me faire signe si c'est possible

**Comment by PixelyIon** [comment]
I'm not sure why this is a GitHub Issues comment, if you want help you can come to our [Discord server](https://discord.gg/XnbXNQM). I should add that this is an English-only forum so you'll want to translate your comments prior to posting them, I'll be closing this issue due to no stated goal.

**Comment by kayjballer** [comment]
sorry I'm not well taken but a little help will not be refused and sorry
again
