### ISSUE TITLE
Snapdragon 8 Gen 1 no Switch game that is over 4 GB in size is playable, only crashes or black screen

### ISSUE THREAD

**Issue by sparrowvirgabaseball** [skyline-emu/skyline#979]
- https://github.com/skyline-emu/skyline/actions/runs/2144286465
- [app-release.apk.zip](https://github.com/skyline-emu/skyline/files/8463619/app-release.apk.zip)

prod.keys (version 14.0.0)
- https://www.reddit.com/r/SwitchEmulators/comments/tm5cyb/here_are_the_prodkeys_firmware_version_1400/
- [Keys 14.0.0.zip](https://github.com/skyline-emu/skyline/files/8463742/Keys.14.0.0.zip)

Roms (under 200 MB size)

- https://nswrom.com/2021/02/05/sonic-1-2-classic/
- https://nswrom.com/2020/02/16/sega-ages-sonic-the-hedgehog-2/

Roms (about 4 GB size)

- https://nswrom.com/2018/12/11/pokemon-lets-go-pikachu-switch-xci-nsp/
- https://nswrom.com/2022/01/20/pokemon-legends-arceus/

Roms (about 10 GB size)

- https://taodung.com/fire-emblem-warriors-switch-xci-nsp-nsz/

Results:
When I play the roms under 200 MB size on an Android device with Snapdragon 8 Gen 1, it launches normally in Skyline and there are no problems, everything runs smoothly.

When I start the roms over 4GB and 10GB size it does not work, the app crashes, there is black screen or sometimes can happen that the Android system hangs.

When I install and use the EG NS Emulator (version 2.1.8), the roms above 4GB and 10GB only give less FPS (10 - 25 FPS), but it starts and runs moderately, but it is playable.

http://www.eggns.xyz/Forums/?page_id=7
[EGGNS_2.1.8.zip](https://github.com/skyline-emu/skyline/files/8463847/EGGNS_2.1.8.zip)

Can you optimize Skyline so that it has similar performance to EG NS Emulator?

**Comment by bylaws** [comment]
Going to have to ban you from repo for piracy
