### ISSUE TITLE
Snapdragon 8 Gen 1 no Switch game that is over 4 GB in size is playable, only crashes or black screen

### ISSUE THREAD

**Issue by sparrowvirgabaseball** [skyline-emu/skyline#980]
- https://github.com/skyline-emu/skyline/actions/runs/2144286465
- [app-release.apk.zip](https://github.com/skyline-emu/skyline/files/8463619/app-release.apk.zip)

Roms (under 200 MB size)

- sonic-1-2-classic
- SEGA AGES Sonic The Hedgehog 2

Roms (about 4 GB size)

- Pokémon: Let's Go, Pikachu!
- Pokémon Legends: Arceus

Roms (about 10 GB size)
- Fire Emblem Warriors

Results:
When I play the roms under 200 MB size on an Android device with Snapdragon 8 Gen 1, it launches normally in Skyline and there are no problems, everything runs smoothly.

When I start the roms over 4GB and 10GB size it does not work, the app crashes, there is black screen or sometimes can happen that the Android system hangs.

When I install and use the Egg NS Emulator (version 2.1.8), the roms above 4GB and 10GB only give less FPS (10 - 25 FPS), but it starts and runs moderately, but it is playable. Can you optimize Skyline so that it has similar performance to Egg NS Emulator?

**Comment by sparrowvirgabaseball** [comment]
I have not added any links now because of the roms.

**Comment by Lamzas1234** [comment]
That's considered to be **piracy.**

**Comment by MrKing202981** [comment]
I don't believe this to be a valid issues as every game you've tested doesn't currently work on the emulator to my knowledge. The correlation between file size and the game not launch is a mild coincidence at best.

**Comment by sparrowvirgabaseball** [comment]
> I don't believe this to be a valid issues as every game you've tested currently doesn't work on the emulator to my knowledge. The correlation between file size and the game not launching is a mild coincidence at best.

How do you know that, can you prove otherwise? The games under 200MB size are very old games from the 90s. The games over 4GB are current games with good graphics for mobile devices.

**Comment by sauradipdebnath** [comment]
> That's considered to be **piracy.**

BE AWARE THAT PIRACY IS A CRIME

**Comment by PixelyIon** [comment]
@sauradipdebnath Okay, that's it. I'm permanently banning you from the repository, I've issued enough warnings about pointless messages.
