### ISSUE TITLE
Skyline crashed on recent bulid

### ISSUE THREAD

**Issue by HalogenGam3r** [skyline-emu/skyline#982]
I have Huawei P40 lite, and on the recent bulid, it just crashed.

**Comment by julssama** [comment]
Your phone has a mali gpu which is probably the cause of the crashes, crashes with regards to mali gpu's will be fixed soon-ish, Thank you for the patience and have fun ^^.

**Comment by R0X-IT** [comment]
Here too. Realme gt 5g soc 888 Android 12

**Comment by R0X-IT** [comment]
I open skyline and after selecting the folder it closes and does not open anymore.

**Comment by xxRaiyanxxYT** [comment]
same it does not open in the recent ft1x build
(Using android 12L, Snapdragon 860)

**Comment by PixelyIon** [comment]
We're aware of the issue, it'll be fixed tomorrow due to scheduling conflicts.

**Comment by bylaws** [comment]
Yeah I think we just need thread pinning hopefully and that should be enough, also didn't you say you were gonna work on it with unity stuff too?

**Comment by PixelyIon** [comment]
This should be resolved by [97557494a440dce78d5d1bb76e46e1227e74e299](https://github.com/skyline-emu/skyline/commit/97557494a440dce78d5d1bb76e46e1227e74e299), you can test the corresponding CI build after it's done. I'll be closing the issue in the meantime as the issue should be resolved, if it isn't just drop a comment here.
