### ISSUE TITLE
Save File Location

### ISSUE THREAD

**Issue by Kraqqen** [skyline-emu/skyline#991]
I've been having problems with using backups of save files with games. The app data folder I'm supposed to place the save in is not writeable so I can't use my save files after I install a new version of skyline. Is there a reason we couldn't have an option to load in save data or change which folder the save data is stored in, manually? I'm on the s21u btw. Thanks so much.

**Comment by PixelyIon** [comment]
We're aware of the limitations of the fixes, they were mostly temporary while we worked on better solutions. We will eventually implement a Skyline `DocumentProvider` which should work across all devices and have the ability to retain app data across installs.
