### ISSUE TITLE
Ram usage

### ISSUE THREAD

**Issue by chalebmydia** [skyline-emu/skyline#993]
Incredibly impressed so far with recent developments. Stubb's the Zombie loads to start and Pokemon Snap loading screen loads. You guys are doing amazing however the ram usage seems odd. Not using enough ram on my OnePlus 9 Pro

**Comment by bylaws** [comment]
No, the ram usage is normal, this is how much ram well programmed emus use :) (dw though big games like maybe botw will use like 4+gb)
