### ISSUE TITLE
Crash after Intro [Loadable] - Ori and the Blind Forest (Definitive Edition)

### ISSUE THREAD

**Issue by marcoluc97** [skyline-emu/skyline#999]
**DESCRIPTION**:
Hi team, with recent build now "Ori the blind forest" boot, but the emulator crash or freeze reaching the point were usually boot the menu, also the audio seems to not works but I'm not sure before at least load the first part of the game. For what I see there are still some Unimplemented in the logs about Unity engine and a lot of VK errors to something not Validated or supported. I attach a video and the logs.

**DEVICE**:
Galaxy S7 (SM-T875)
Android 11(Nov 2021 patches)
6 GB LPDDR5
Qualcomm Snapdragon 865 (SM8250)
Adreno (TM) 650
Vulkan API 1.1.128

**VIDEO**

https://user-images.githubusercontent.com/9196583/163063794-31c126e5-60b2-471e-adf7-f4b4de5073ae.mp4

**LOGS**
[emulation.zip](https://github.com/skyline-emu/skyline/files/8484902/emulation.zip)

**Comment by Mkotov42** [comment]
Some games need updated Vulcan driver which would help the process. I ran into One issue requesting Vk 1.2 which can be installed manually if you are rooted. Please be patient friend.

**Comment by marcoluc97** [comment]
With commit https://github.com/skyline-emu/skyline/commit/f261a41e64c057c631e508a15e3c5e55477005a8 now Ori seems to have seizures and more artifacts, also new logs if useful 

**VIDEO**
https://user-images.githubusercontent.com/9196583/163276520-8a4fe2d6-58c8-4d00-bcb5-e2ce25238ce0.mp4

**LOGS**

**Comment by PixelyIon** [comment]
While this is fairly useful, I think @bylaws is already aware about this, he's working on GPU feature support while I'm working on optimizations. I should add that we do indeed vastly prefer testing on Discord and we have a dedicated section for it, you can ping us on the server if you want to be added to it.

**Comment by marcoluc97** [comment]
Ok thanks
